package com.flipcheck.nativebeta;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Arrays;
import java.util.List;
import org.json.JSONArray;
import org.json.JSONObject;

/** Production-path regressions for scoped OCR, typed identifiers and catalog states. */
public final class V129UniversalCatalogEvidenceRegressionTest {
    private static JSONObject cases;
    public static void main(String[] args)throws Exception{cases=load();
        uiTextIsExternal();marketplaceTextIsExternal();biographyAndStatisticsAreNotIdentifiers();seasonIsNotCollector();
        alphanumericCollectorSurvives();ocrSeparatorAlternativesAreGenerated();serialStaysSeparate();
        queryLadderIsBounded();queryLadderHasNoNulls();tcgCodeIsFirstQuery();
        sportsChecklistResolvesUncertainReading();sportsStateIsCoherent();webContributionIsReal();
        tcgPartialAttacksAreSupporting();tcgWrongIdentifierIsVetoed();tcgStateIsCoherent();
        sealedDistinctiveTokenRemainsHard();externalTextNeverEntersQueries();missingWebBiographyIsNeutral();
        noFixtureSpecificProductionBranch();
        System.out.println("V129UniversalCatalogEvidenceRegressionTest: PASS (20/20)");}

    private static void uiTextIsExternal(){require(TextScopePolicy.SCREEN_UI_TEXT.equals(TextScopePolicy.scope(raw("visual_description","1 di 2","screen_ui_text","status bar"))),"gallery UI not excluded");}
    private static void marketplaceTextIsExternal(){require(TextScopePolicy.MARKETPLACE_LISTING_TEXT.equals(TextScopePolicy.scope(raw("visual_description","Il mio eBay €299","marketplace_listing_text","listing"))),"marketplace text not excluded");}
    private static void biographyAndStatisticsAreNotIdentifiers(){Models.Identification id=new Models.Identification();Models.LocalScan l=new Models.LocalScan();l.textByImage.add("23/8/78\n23/78\n8/23\nPTS 24.5 18.2\n1 di 2");LocalEvidenceBootstrap.apply(id,l);PhotographicFactNormalizer.normalize(id,"typed_numbers");PhysicalCardNumberPolicy.normalize(id);require(id.physicalCardNumber.isEmpty(),"date/statistic became card number: "+id.physicalCardNumber);}
    private static void seasonIsNotCollector(){Models.Identification id=new Models.Identification();EvidenceLedger.addPhotoFact(id,"collector_marking","2025/26","direct_photo_observation",90,0,"front","season mark","season");NormalizedPhotoIdentity n=PhotographicFactNormalizer.normalize(id,"season");PhysicalCardNumberPolicy.normalize(id);require(id.collectorNumberCandidate.isEmpty()&&"2025-26".equals(n.physicalYear()),"season became collector number; collector="+id.collectorNumberCandidate+" year="+n.physicalYear()+" canonical="+id.canonicalPhotoFields+" rejected="+id.factsRejectedWithReason);}
    private static void alphanumericCollectorSurvives(){NumericTokenClassifier.Result r=NumericTokenClassifier.classify(nf("collector_marking","TG12/TG30","collector_number","lower corner"));require(r.kind==NumericTokenClassifier.Kind.COLLECTOR_NUMBER&&"TG12/TG30".equals(r.normalized),"alphanumeric collector lost");}
    private static void ocrSeparatorAlternativesAreGenerated(){NumericTokenClassifier.Result r=NumericTokenClassifier.classify(nf("collector_marking","H23IH32","collector_number","lower corner"));require(r.alternatives.contains("H23/H32"),"plausible separator alternative missing: "+r.alternatives);}
    private static void serialStaysSeparate(){Models.Identification id=new Models.Identification();EvidenceLedger.addPhotoFact(id,"physical_serial","004/100","direct_photo_observation",99,1,"back","stamped serial","physical_serial");PhotographicFactNormalizer.normalize(id,"serial");PhysicalSerialPolicy.normalize(id);PhysicalCardNumberPolicy.normalize(id);require("004/100".equals(id.physicalSerial)&&id.physicalCardNumber.isEmpty(),"physical serial crossed into card number");}
    private static void queryLadderIsBounded()throws Exception{Models.Identification id=run("tcg_wrong_first_candidate",false);require(id.exactResolutionQueries.size()<=4,"query cap exceeded");}
    private static void queryLadderHasNoNulls()throws Exception{Models.Identification id=run("tcg_wrong_first_candidate",false);for(String q:id.exactResolutionQueries)require(!q.toLowerCase().matches(".*\\b(?:null|empty|not visibly specified)\\b.*"),"query contains empty sentinel: "+q);}
    private static void tcgCodeIsFirstQuery()throws Exception{Models.Identification id=run("tcg_wrong_first_candidate",false);require(!id.exactResolutionQueries.isEmpty()&&id.exactResolutionQueries.get(0).contains("H23/H32"),"strong collector code not queried first: "+id.exactResolutionQueries);}
    private static void sportsChecklistResolvesUncertainReading()throws Exception{Models.Identification id=run("sports_reversed_identifier",true);require("81".equals(id.sourceConfirmedCatalogNumber)&&!id.title.contains("#18")&&!"CONFLICTED".equals(id.identityStatus),"checklist did not resolve uncertain photo reading: "+id.title+" "+id.numberConflicts);}
    private static void sportsStateIsCoherent()throws Exception{Models.Identification id=run("sports_reversed_identifier",true);require("CATALOG_MATCHED".equals(id.identifierStatus)&&id.exactIdentityStatus.equals(id.exactCatalogStatus)&&"PASS".equals(id.consistencyInvariants),"sports final state drift");}
    private static void webContributionIsReal()throws Exception{Models.Identification id=run("sports_reversed_identifier",true);require(id.webContributionScore>0&&id.exactIdentityConfidence<100,"catalog contribution/confidence invalid");}
    private static void tcgPartialAttacksAreSupporting()throws Exception{JSONObject x=cases.getJSONObject("tcg_wrong_first_candidate");JSONObject web=new JSONObject(x.getJSONObject("web").toString());JSONObject good=new JSONObject(web.getJSONArray("candidates").getJSONObject(1).toString());good.put("attacks",new JSONArray().put("Ranabalzo"));web.put("candidates",new JSONArray().put(good));Models.Identification id=runCustom(x,web);require(id.catalogVerified&&!id.catalogConflicts.contains("ATTACKS_PARTIAL_CONFLICT"),"partial/translated attacks became hard conflict: "+id.catalogConflicts);}
    private static void tcgWrongIdentifierIsVetoed()throws Exception{JSONObject x=cases.getJSONObject("tcg_wrong_first_candidate");JSONObject web=new JSONObject(x.getJSONObject("web").toString());JSONObject wrong=new JSONObject(web.getJSONArray("candidates").getJSONObject(0).toString());web.put("candidates",new JSONArray().put(wrong));web.put("source_url",wrong.getString("source_url"));Models.Identification id=runCustom(x,web);require(!id.catalogVerified&&id.catalogConflicts.contains("IDENTIFIER_CONFLICT"),"incompatible collector number accepted");}
    private static void tcgStateIsCoherent()throws Exception{Models.Identification id=run("tcg_wrong_first_candidate",true);require("H23/H32".equals(id.sourceConfirmedCatalogNumber)&&"CATALOG_MATCHED".equals(id.exactCatalogStatus)&&"VARIANT_CONFIRMED".equals(id.variantStatus)&&id.nextPhotoRequest.isEmpty(),"TCG exact/variant/photo state drift: "+id.exactCatalogStatus+" "+id.variantStatus+" "+id.nextPhotoRequest);}
    private static void sealedDistinctiveTokenRemainsHard()throws Exception{JSONObject x=cases.getJSONObject("sealed_distinctive_token");JSONObject web=new JSONObject(x.getJSONObject("web").toString());JSONObject c=new JSONObject(web.getJSONArray("candidates").getJSONObject(0).toString());c.put("product_line","Topps Chrome").put("product_name","Topps Chrome Hobby Box").remove("sub_series");web.put("candidates",new JSONArray().put(c));Models.Identification id=runCustom(x,web);require(!id.catalogVerified&&id.catalogConflicts.contains("DISTINCTIVE_TOKEN_LOST"),"sealed sub-series token loss accepted");}
    private static void externalTextNeverEntersQueries()throws Exception{Models.Identification id=run("sports_reversed_identifier",false);for(String q:id.exactResolutionQueries)require(!q.contains("1 di 2")&&!q.contains("23/78")&&!q.contains("8/23"),"external/statistical OCR entered query: "+q);}
    private static void missingWebBiographyIsNeutral()throws Exception{Models.Identification id=run("sports_reversed_identifier",true);require(id.catalogVerified&&!id.catalogConflicts.contains("DISTINCTIVE_TOKEN_LOST"),"missing biography/statistics rejected a valid catalog candidate");}
    private static void noFixtureSpecificProductionBranch()throws Exception{String all="";for(java.nio.file.Path p:(Iterable<java.nio.file.Path>)Files.walk(Paths.get("app/src/main/java")).filter(Files::isRegularFile)::iterator)all+=new String(Files.readAllBytes(p),StandardCharsets.UTF_8);require(!all.matches("(?s).*if\\s*\\([^)]*(Kobe Bryant|Politoed|H23/H32|SkyBox|Skyridge).*"),"fixture-specific production condition found");}

    private static Models.Identification run(String key,boolean web)throws Exception{JSONObject x=cases.getJSONObject(key);return IdentificationPipelineV082.identify(local(x),Arrays.asList("data:image/jpeg;base64,AA"),"",new ScriptedClient(vision(x.getJSONObject("vision")),web?web(x.getJSONObject("web")):unavailable()),new Models.Usage());}
    private static Models.Identification runCustom(JSONObject x,JSONObject web)throws Exception{return IdentificationPipelineV082.identify(local(x),Arrays.asList("data:image/jpeg;base64,AA"),"",new ScriptedClient(vision(x.getJSONObject("vision")),web(web)),new Models.Usage());}
    private static Models.LocalScan local(JSONObject x){Models.LocalScan l=new Models.LocalScan();JSONArray a=x.optJSONArray("ocr");StringBuilder b=new StringBuilder();for(int i=0;a!=null&&i<a.length();i++){if(b.length()>0)b.append('\n');b.append(a.optString(i));}l.textByImage.add(b.toString());return l;}
    private static OpenAiClient.Response vision(JSONObject p){OpenAiClient.Response r=new OpenAiClient.Response();r.payload=p;r.complete=true;r.technicalStatus="COMPLETED";r.usage.visionCalls=1;r.usage.requests=1;r.usage.costUsd=.006;return r;}
    private static OpenAiClient.Response web(JSONObject p){OpenAiClient.Response r=new OpenAiClient.Response();r.payload=p;r.complete=true;r.technicalStatus="COMPLETED";r.usage.webCalls=1;r.usage.requests=1;r.usage.costUsd=.012;addSource(r,p.optString("source_url"));JSONArray a=p.optJSONArray("candidates");for(int i=0;a!=null&&i<a.length();i++)addSource(r,a.optJSONObject(i).optString("source_url"));return r;}
    private static OpenAiClient.Response unavailable(){OpenAiClient.Response r=new OpenAiClient.Response();r.complete=false;r.parseError="network";r.technicalStatus="NETWORK_ERROR";return r;}
    private static void addSource(OpenAiClient.Response r,String u){if(u==null||u.isEmpty())return;Models.Source s=new Models.Source();s.url=u;s.title="retrieved";r.sources.add(s);}
    private static Models.EvidenceFact raw(String k,String v,String role,String location){return new Models.EvidenceFact(k,v,EvidenceLedger.LOCAL_OCR,"local_ocr_hint",80,0,"unknown",location,role,"");}
    private static NormalizedPhotoIdentity.Fact nf(String k,String v,String role,String location){return new NormalizedPhotoIdentity.Fact(CanonicalFieldKey.fromAlias(k),v,k,role,location,"front","local_ocr_hint",NormalizedPhotoIdentity.Quality.LOCAL_OCR_HINT,82,0,EvidenceLedger.LOCAL_OCR,0L,"test");}
    private static JSONObject load()throws Exception{return new JSONObject(new String(Files.readAllBytes(Paths.get("tools/regression/fixtures/v127_catalog_compatibility_replays.json")),StandardCharsets.UTF_8));}
    private static void require(boolean ok,String message){if(!ok)throw new AssertionError(message);}
    private static final class ScriptedClient extends OpenAiClient{final Response first,web;ScriptedClient(Response first,Response web){super("test");this.first=first;this.web=web;}@Override Response observe(List<String>x,String p){return first;}@Override Response enrichConfirmedIdentity(String p){return web;}@Override Response webStage(String s,String p){return web;}}
}
