package com.flipcheck.nativebeta;

import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.security.MessageDigest;
import javax.imageio.ImageIO;
import org.json.JSONObject;

/** Real-image fixture integrity, deterministic API replay and metamorphic reducer tests. */
public final class V132UniversalIdentityEngineV2RegressionTest {
    private static JSONObject fixtures;private static int passed;
    public static void main(String[] args)throws Exception{
        fixtures=new JSONObject(new String(Files.readAllBytes(Paths.get("tools/regression/fixtures/v132_real_image_replays.json")),StandardCharsets.UTF_8));
        realImagesArePermanentFixtures();toppsInferenceCannotMasqueradeAsObservation();kobeKeepsPhysicalNumberAndSemanticYear();
        vileplumeRepairsContextualOcrWithoutFalseConflict();philipsUsesLayoutRetrievalAndRequestsRearModel();
        contextualGrammarPreservesAlphanumericCollectors();singleReducerOwnsProductionRoute();metamorphicImageVariantsKeepReplayIdentity();
        historicalSourceGuaranteesRemainPresent();noFixtureSpecificProductionHardcode();
        System.out.println("V132UniversalIdentityEngineV2RegressionTest: PASS ("+passed+"/10)");
    }
    private static void realImagesArePermanentFixtures()throws Exception{String[]names={"topps-front.jpg","kobe-back.jpg","kobe-front.jpg","vileplume-front.jpg","philips-front.jpg"};String[]sha={"205f9daef98308b6dc2d85a472424f818a5ae9d99b47e080211e26dc5f0ea883","717ab1814def0ce5bb3930db7b74f0816d97181cd11ef6e44e40b0ee94a712b1","54f16d9e5c6a888df7d6ad0612a9e3c96a9751d03d85d0d76ab2311d4484eb82","25cd597509a77517eb163d752d1866203d14c571650e85d3c98122da3b0fb2ec","bd26e4a6b2bca3348fef87914c4bda6a89a1232209d7cc9103b0e3e42c3b108c"};for(int i=0;i<names.length;i++){String name=names[i];Path p=Paths.get("tools/regression/fixtures/v132-real-images",name);require(Files.isRegularFile(p)&&Files.size(p)>100000,"missing real image "+name);require(sha[i].equals(hex(MessageDigest.getInstance("SHA-256").digest(Files.readAllBytes(p)))),"fixture hash changed "+name);BufferedImage image=ImageIO.read(p.toFile());require(image!=null&&image.getWidth()>=700&&image.getHeight()>=1500,"invalid original image "+name);}pass();}
    private static void toppsInferenceCannotMasqueradeAsObservation()throws Exception{Models.Identification id=replay("topps");require(id.title.contains("Topps")&&!id.title.contains("Upper Deck"),"inferred brand defeated observed text: "+id.title);require(id.v2InferredFacts.contains("Upper Deck")&&!id.v2ObservedFacts.contains("Upper Deck"),"epistemic provenance collapsed");require("CONFIRMED".equals(id.coreIdentityStatus)&&"FORMAT_PENDING".equals(id.exactIdentityStatus),"sealed core blocked by format");require("1 autograph card in every box".equalsIgnoreCase(id.productConfiguration),"printed configuration changed");require(id.blockingReason.isEmpty(),"false sealed conflict");pass();}
    private static void kobeKeepsPhysicalNumberAndSemanticYear()throws Exception{Models.Identification id=replay("kobe");require(id.title.contains("1997-98")&&id.title.contains("Kobe Bryant")&&id.title.contains("#81"),"sports identity incomplete: "+id.title);require("81".equals(id.physicalCardNumber)&&"81".equals(id.sourceConfirmedCatalogNumber)&&id.numberAgreement,"photo/catalog number provenance missing");require("1997-98".equals(id.physicalReleaseYear)&&"1996-97".equals(id.statisticsSeason),"statistics season contaminated product release");require("PHOTO_PLUS_CATALOG".equals(id.combinedVerification)&&"CONFIRMED".equals(id.coreIdentityStatus),"sports closure/provenance invalid");pass();}
    private static void vileplumeRepairsContextualOcrWithoutFalseConflict()throws Exception{Models.Identification id=replay("vileplume");require(id.title.contains("Vileplume")&&id.title.contains("#15/64"),"TCG title incomplete: "+id.title);require("15/64".equals(id.physicalCollectorNumber)&&id.numberConflicts.isEmpty(),"I/1 OCR repair produced conflict: "+id.numberConflicts);require("FIRST_EDITION".equals(id.edition)&&"HOLO".equals(id.finish),"edition/finish lost");require("CONFIRMED".equals(id.coreIdentityStatus)&&"CONFIRMED".equals(id.exactEditionStatus)&&id.nextPhotoRequest.isEmpty(),"complete TCG did not close");pass();}
    private static void philipsUsesLayoutRetrievalAndRequestsRearModel()throws Exception{Models.Identification id=replay("philips");require("television_remote_control".equals(id.v2Profile),"remote profile lost");require("Philips".equals(id.brand)&&!id.title.contains("LG"),"remote brand not resolved by disproof: "+id.title);require("CONFIRMED".equals(id.coreIdentityStatus)&&"TO_VERIFY".equals(id.exactModelStatus),"remote hierarchy wrong");require("rear_label_or_model_code".equals(id.requestedPhotoReason)&&!id.nextPhotoRequest.isEmpty(),"specific rear request missing");require(id.v2ObservedFacts.contains("controlLayout")&&id.v2ObservedFacts.contains("shortcutButtons"),"remote features discarded");pass();}
    private static void contextualGrammarPreservesAlphanumericCollectors(){require("15/64".equals(TypedFieldNormalizerV2.normalizeValue("collectorNumber","I5/64","collector_number")),"numeric OCR repair failed");ImmutableEvidenceLedgerV2 ledger=new ImmutableEvidenceLedgerV2();ledger.append("collectorNumber","I5/64",EvidenceAtom.EpistemicLevel.OBSERVED,EvidenceAtom.Modality.LOCAL_OCR,"local",0,"front","bottom-right","","collector_number",88,80,"test","");TypedFieldNormalizerV2.normalize(ledger);require("I5/64".equals(ledger.strongest("collectorNumber",EvidenceAtom.EpistemicLevel.OBSERVED).normalizedValue),"uncorroborated OCR repair became canonical");ledger.append("collectorNumber","15/64",EvidenceAtom.EpistemicLevel.OBSERVED,EvidenceAtom.Modality.FOCUSED_VISION,"focused",0,"front","bottom-right","crop-number","collector_number",96,90,"test","");TypedFieldNormalizerV2.normalize(ledger);require("15/64".equals(ledger.strongest("collectorNumber",EvidenceAtom.EpistemicLevel.OBSERVED).normalizedValue),"corroborated OCR repair did not converge");String[]codes={"H23/H32","TG01/TG30","SWSH001","XY123","SM-P"};for(String code:codes)require(code.equals(TypedFieldNormalizerV2.normalizeValue("collectorNumber",code,"collector_number")),"alphanumeric identifier damaged: "+code);pass();}
    private static void singleReducerOwnsProductionRoute()throws Exception{String engine=read("app/src/main/java/com/flipcheck/nativebeta/IdentificationEngine.java"),v2=read("app/src/main/java/com/flipcheck/nativebeta/UniversalIdentityEngineV2.java");require(engine.indexOf("UniversalIdentityEngineV2.enabled()")<engine.indexOf("IdentificationPipelineV082.enabled()"),"legacy route still precedes v2");require(!v2.contains("FinalIdentityDecisionEngine.freeze")&&!v2.contains("IdentificationEngine.finalizeOutput"),"legacy composer called after v2 reducer");require(v2.contains("FinalStateReducerV2.reduce"),"single reducer not wired");ImmutableEvidenceLedgerV2 sports=new ImmutableEvidenceLedgerV2();observed(sports,"athlete","Player");observed(sports,"productLine","Series");observed(sports,"productReleaseYear","2020-21");require(AdaptiveRecoveryPlannerV2.afterPrimary(DomainProfileRouterV2.Profile.SPORTS_CARD,sports,new Models.Usage()).action==AdaptiveRecoveryPlannerV2.Action.FOCUSED_VISION,"missing card number did not trigger focused recovery");ImmutableEvidenceLedgerV2 tcg=new ImmutableEvidenceLedgerV2();observed(tcg,"cardName","Card");observed(tcg,"setName","Set");observed(tcg,"collectorNumber","1/100");require("edition_and_finish".equals(AdaptiveRecoveryPlannerV2.afterPrimary(DomainProfileRouterV2.Profile.TCG_CARD,tcg,new Models.Usage()).discriminator),"missing TCG edition did not trigger focused recovery");pass();}
    private static void metamorphicImageVariantsKeepReplayIdentity()throws Exception{String[]keys={"topps","kobe","vileplume","philips"};String[]files={"topps-front.jpg","kobe-front.jpg","vileplume-front.jpg","philips-front.jpg"};for(int i=0;i<keys.length;i++){BufferedImage src=ImageIO.read(Paths.get("tools/regression/fixtures/v132-real-images",files[i]).toFile());String expected=replay(keys[i]).title;BufferedImage[]variants={resize(src,.72),brightness(src,.88),rotate(src,2.0),centerCrop(src,.94)};long base=signature(src);for(BufferedImage variant:variants){require(variant.getWidth()>400&&variant.getHeight()>800,"metamorphic transform invalid");require(distance(base,signature(variant))<.62,"visual signature changed excessively for "+keys[i]);require(expected.equals(replay(keys[i]).title),"deterministic identity changed under equivalent evidence");}}pass();}
    private static void historicalSourceGuaranteesRemainPresent()throws Exception{String all=readTree(Paths.get("app/src/main/java/com/flipcheck/nativebeta"));require(all.contains("physicalSerial")&&all.contains("shadowStatus")&&all.contains("firstEditionMark")&&all.contains("Barcode"),"historical axes removed");require(read("app/src/main/java/com/flipcheck/nativebeta/AnalysisForegroundService.java").contains("startForeground"),"background analysis removed");require(read("app/src/main/java/com/flipcheck/nativebeta/MainActivity.java").contains("CameraCaptureProvider"),"camera flow removed");pass();}
    private static void noFixtureSpecificProductionHardcode()throws Exception{String x=readTree(Paths.get("app/src/main/java/com/flipcheck/nativebeta")).toLowerCase();require(!x.contains("kobe bryant")&&!x.contains("vileplume")&&!x.contains("upper deck chrome")&&!x.contains("cooper flagg"),"fixture-specific production hardcode detected");pass();}
    private static Models.Identification replay(String key)throws Exception{JSONObject f=fixtures.getJSONObject(key);Models.Usage u=new Models.Usage();u.visionCalls=f.has("focused")?2:1;u.webCalls=1;u.requests=u.visionCalls+1;u.costUsd=u.visionCalls==2?.019:.015;Models.Identification id=UniversalIdentityEngineV2.replay(new Models.LocalScan(),f.getJSONObject("primary"),f.optJSONObject("focused"),f.getJSONObject("web"),u);require(id.estimatedAnalysisCostUsd<=.025,"replay cost exceeded budget for "+key);return id;}
    private static BufferedImage resize(BufferedImage src,double scale){int w=(int)(src.getWidth()*scale),h=(int)(src.getHeight()*scale);BufferedImage out=new BufferedImage(w,h,BufferedImage.TYPE_INT_RGB);Graphics2D g=out.createGraphics();g.setRenderingHint(RenderingHints.KEY_INTERPOLATION,RenderingHints.VALUE_INTERPOLATION_BILINEAR);g.drawImage(src,0,0,w,h,null);g.dispose();return out;}
    private static BufferedImage brightness(BufferedImage src,double factor){BufferedImage out=new BufferedImage(src.getWidth(),src.getHeight(),BufferedImage.TYPE_INT_RGB);for(int y=0;y<src.getHeight();y++)for(int x=0;x<src.getWidth();x++){Color c=new Color(src.getRGB(x,y));int r=(int)Math.min(255,c.getRed()*factor),g=(int)Math.min(255,c.getGreen()*factor),b=(int)Math.min(255,c.getBlue()*factor);out.setRGB(x,y,new Color(r,g,b).getRGB());}return out;}
    private static BufferedImage rotate(BufferedImage src,double degrees){BufferedImage out=new BufferedImage(src.getWidth(),src.getHeight(),BufferedImage.TYPE_INT_RGB);Graphics2D g=out.createGraphics();g.setColor(Color.WHITE);g.fillRect(0,0,out.getWidth(),out.getHeight());g.rotate(Math.toRadians(degrees),src.getWidth()/2d,src.getHeight()/2d);g.drawImage(src,0,0,null);g.dispose();return out;}
    private static BufferedImage centerCrop(BufferedImage src,double scale){int w=(int)(src.getWidth()*scale),h=(int)(src.getHeight()*scale);return src.getSubimage((src.getWidth()-w)/2,(src.getHeight()-h)/2,w,h);}
    private static long signature(BufferedImage src){BufferedImage small=resize(src,16d/src.getWidth());long bits=0;for(int y=0;y<Math.min(8,small.getHeight());y++)for(int x=0;x<8;x++){Color a=new Color(small.getRGB(x,y)),b=new Color(small.getRGB(x+1,y));int ga=a.getRed()+a.getGreen()+a.getBlue(),gb=b.getRed()+b.getGreen()+b.getBlue();bits=(bits<<1)|(ga>gb?1:0);}return bits;}
    private static double distance(long a,long b){return Long.bitCount(a^b)/64d;}
    private static String read(String path)throws Exception{return new String(Files.readAllBytes(Paths.get(path)),StandardCharsets.UTF_8);}
    private static String readTree(Path root)throws Exception{StringBuilder b=new StringBuilder();try(java.util.stream.Stream<Path>s=Files.walk(root)){s.filter(p->p.toString().endsWith(".java")).forEach(p->{try{b.append(read(p.toString()));}catch(Exception e){throw new RuntimeException(e);}});}return b.toString();}
    private static void observed(ImmutableEvidenceLedgerV2 ledger,String field,String value){ledger.append(field,value,EvidenceAtom.EpistemicLevel.OBSERVED,EvidenceAtom.Modality.PRIMARY_VISION,"test",0,"front","specific "+field+" region","",field,95,90,"test","");}
    private static String hex(byte[] bytes){StringBuilder b=new StringBuilder();for(byte value:bytes)b.append(String.format("%02x",value&255));return b.toString();}
    private static void require(boolean ok,String message){if(!ok)throw new AssertionError(message);}private static void pass(){passed++;}
}
