[versions]
agp = "9.0.1"
junit = "4.13.2"
json = "20240303"
jsoup = "1.18.3"
mlkit-text-recognition = "16.0.1"
mlkit-barcode-scanning = "17.3.0"
mlkit-object-detection = "17.0.2"

[libraries]
junit = { module = "junit:junit", version.ref = "junit" }
json = { module = "org.json:json", version.ref = "json" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
mlkit-text-recognition = { module = "com.google.mlkit:text-recognition", version.ref = "mlkit-text-recognition" }
mlkit-barcode-scanning = { module = "com.google.mlkit:barcode-scanning", version.ref = "mlkit-barcode-scanning" }
mlkit-object-detection = { module = "com.google.mlkit:object-detection", version.ref = "mlkit-object-detection" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
