const {test}=require('node:test'),assert=require('node:assert/strict'),E=require('../src/main/assets/catalogue-engine'),M=require('../src/main/assets/card-market');
const hill=require('./fixtures/physical-236-hill.json');
function resolve(v=hill.vision){return E.reduce(E.ingestVision(new E.Ledger(v),v),hill.entries);}
test('236 real Hill report closes printed Superfractor, retains provenance and discards Tie dye prices',()=>{const r=resolve();assert.equal(r.market_ready,true);assert.equal(r.catalogue_verified,false);assert.match(r.identity_display,/2025.*University.*Anthony Hill Jr.*Superfractor.*1\/1/);assert.equal(r.derived_serial.origin,'parallel_definition');assert.equal(r.physical_serial,null);assert.equal(r.provider_conflicts[0].reported,'Tie dye');assert.equal(M.target(r).one_of_one,true);});
test('236 uncertain label, conflicting name/number/serial cannot close from physical data',()=>{for(const mutate of [v=>{v.observations.find(o=>/SUPERFRACTOR/.test(o.text)).certainty='uncertain';},v=>v.observations.push({field:'subject',text:'John Mateer',certainty:'clear',image_index:2}),v=>v.observations.push({field:'model_code',text:'BCA-JM',certainty:'clear',image_index:2}),v=>v.observations.push({field:'serial',text:'2/5',certainty:'clear',image_index:2})]){const v=structuredClone(hill.vision);mutate(v);assert.notEqual(resolve(v).identity_origin,'original_photo');}});
const identity={market_ready:true,category:'basketball card',card_identity:{subject:'Luka Dončić',set:'Panini Prizm',number:'280',date:'2018-19',variant:'Green Prizm',language:'en'}};
const source='https://www.sportscardspro.com/game/basketball-cards-2018-panini-prizm/luka-doncic-green-prizm-280';
function row(n,patch={}){return {source_url:source,url:'https://www.ebay.com/itm/'+(100000000000+n),title:'2018-19 Luka Doncic #280 Panini Prizm Green Prizm',quote:'Sold 2026-07-27 '+(100+n)+' USD',date:'2026-07-27',price:100+n,currency:'USD',price_kind:'sold',subject:'Luka Doncic',set:'Panini Prizm',year:'2018',number:'280',subset:'',variant:'Green Prizm',language:'en',edition:'',shadow:'',autograph:'',print_run:null,condition:'',grading:'raw',grader:'',grade:'',...patch};}
function evaluate(sales,patch={},i=identity){return M.evaluate({access:'readable',page_url:source,page_title:'Luka Doncic [Green Prizm] #280',sales,guide:{price:186.75,currency:'USD',quote:'Ungraded $186.75',label:'Ungraded'},...patch},i,[{url:source}],new Date('2026-09-11'));}
test('236 query contains exact season, set, number and parallel; domains separate Pokemon/sports',()=>{const p=M.plan(identity);assert.deepEqual(p.domains,['sportscardspro.com']);assert.match(p.query,/Luka Doncic 2018-19 Panini Prizm #280 Green Prizm/);const t=M.plan({category:'Pokemon',card_identity:{subject:'Machamp',set:'Base Set',number:'8/102',date:'1999',language:'en'},pokemon_printing:{is_pokemon:true,first_edition_stamp:'present',artwork_shadow:'absent'}});assert.deepEqual(t.domains,['pricecharting.com']);assert.match(t.query,/1st Edition Shadowless/);});
test('236 median uses only compatible individual sold records, deduplicating cross-domain eBay URLs',()=>{const r=evaluate([row(1),row(2),row(3),row(1,{url:'https://www.ebay.ca/itm/100000000001?tracking=abc'}),row(4,{variant:'Green Pulsar'}),row(5,{title:'Luka Doncic Green Parallel 2/5'}),row(6,{price_kind:'asking'}),row(7,{language:'it'}),row(8,{grading:'graded',grader:'PSA',grade:'10',price:700})]);assert.equal(r.stat.median,102);assert.equal(r.stat.count,3);assert.equal(r.rejected.length,5);assert.equal(r.state,'raw_condition_unspecified');assert.equal(r.grade_rows[5].stat,null);});
test('236 a missing currency or language, future dates and inferred count never create a price',()=>{for(const patch of [{currency:''},{language:''},{date:'2030-01-01'},{price_kind:'unknown'},{price:null}])assert.equal(evaluate([row(1,patch),row(2,patch),row(3,patch)]).stat,null);assert.equal(evaluate([]).stat,null);assert.equal(evaluate([]).guide,null);});
test('236 all source URLs must be retrieved; failed access differs from no comps',()=>{assert.equal(evaluate([],{access:'unavailable'}).state,'source_unavailable');assert.equal(evaluate([],{page_url:'https://evil.test/game/foo'}).state,'unverified_source');assert.equal(evaluate([]).state,'no_comparables');});
test('236 one of one never uses a site guide or generic graded aggregate',()=>{const r=evaluate([],{page_url:source},resolve());assert.equal(r.stat,null);assert.equal(r.guide,null);assert.equal(r.state,'one_of_one_no_sales');assert.match(M.html(r),/1\/1/);});
test('236 slab only uses same grader and exact grade; no cross currency mean',()=>{const slab={...identity,grading:{company:'PSA',grade:'8'}};const sales=[row(1),row(2,{grading:'graded',grader:'BGS',grade:'8'}),...[3,4,5].map(n=>row(n,{grading:'graded',grader:'PSA',grade:'8'}))];assert.equal(evaluate(sales,{},slab).stat.median,104);assert.equal(evaluate([row(1),row(2,{currency:'EUR'}),row(3)]).stat,null);});
test('236 prices and source text cannot inject HTML',()=>{const r=evaluate([row(1,{title:'<img src=x onerror=alert(1)>'})]);assert.doesNotMatch(M.html(r),/<img/);});
test('236 Machamp composite printing accepts matching holo sales but excludes shadowed and Trainer Deck A',()=>{
 const i={category:'Pokemon',card_identity:{subject:'Machamp',set:'Base Set',number:'8/102',date:'1999',language:'en',variant:'Holo · 1st Edition · Shadowless'},pokemon_printing:{is_pokemon:true,first_edition_stamp:'present',artwork_shadow:'absent'}},page='https://www.pricecharting.com/game/pokemon-base-set/machamp-shadowless-8';
 const sales=[1,2,3,4,5].map(n=>row(n,{source_url:page,subject:'Machamp',set:'Base Set',year:'1999',number:'8/102',variant:'Holo',edition:'1st Edition',shadow:n===4?'Shadowed':'Shadowless',title:n===5?'Machamp Trainer Deck A':'Machamp 1st Edition Shadowless English #8/102 Holo'}));
 const r=M.evaluate({access:'readable',page_url:page,sales},i,[{url:page}],new Date('2026-09-11'));assert.equal(r.stat?.count,3);assert.equal(r.rejected.length,2);
});
