const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),zlib=require('zlib'),path=require('path');
const E=require('../src/main/assets/catalogue-engine'),C=require('../src/main/assets/catalogue-sources');
const D=JSON.parse(zlib.gunzipSync(fs.readFileSync(path.join(__dirname,'fixtures/diagnostics-201.json.gz'))));
function replay(i){const d=D[i],l=E.ingestVision(new E.Ledger(d.vision),d.vision);E.ingestOcr(l,d.photoOcr);const entries=C.records(d.pages,l).concat(d.phases.filter(p=>p.stage==='flipcheck_catalogue_search').flatMap(p=>C.groundedExtraction(p.result,d.pages,l).accepted));return {d,l,entries};}
const absence={surfaces:[{image_index:1,side:'front',fully_visible:true,legible:true},{image_index:2,side:'back',fully_visible:true,legible:true}],serial_presence:'absent',serial:{text:'',certainty:'uncertain',evidence_found:false,image_index:1}};
test('201 Doncic deduplicates catalogue representations before checking Green RC',()=>{const {l,entries}=replay(4);for(const es of [entries,[...entries].reverse(),[...entries,...entries]]){let r=E.reduce(l,es);assert.equal(r.core_identity.status,'confirmed');assert.equal(E.candidateGroups(l,es).length,1);assert.equal(E.recoveryRequests(l,r).some(r=>r.field==='collector_number'),false);assert.doesNotMatch(r.title,/DALLAS MAVERICKS/);}assert.equal(E.reduce(l,entries).market_ready,false);E.applySurfaceInspection199(l,absence,[1,2]);const r=E.reduce(l,entries);assert.equal(r.market_ready,true);assert.match(r.title,/#280.*Green · RC$/);});
test('201 Yamal uses the printed insert and scoped /9 parallel without re-reading #8',()=>{const {l,entries}=replay(5);for(const es of [entries,[...entries].reverse(),[...entries,...entries]]){const r=E.reduce(l,es);assert.equal(r.market_ready,true);assert.match(r.title,/Obsidian Soccer.*Supernova.*#8.*Electric Etch Contra.*Seriale 8\/9/);assert.equal(E.candidateGroups(l,es).length,1);assert.equal(r.card_identity.subset,'Supernova');assert.deepEqual(E.recoveryRequests(l,r),[]);}assert.match(E.query(l),/Supernova/);});
test('201 Boniface retains verified Green /5 and displays product and Terrace',()=>{const {d,l,entries}=replay(3);E.applyDetails(l,d.phases.find(p=>p.stage==='flipcheck_evidence_detail').result.details,E.recoveryRequests(l,E.reduce(l,entries)));const r=E.reduce(l,entries);assert.equal(r.market_ready,true);assert.match(r.title,/ROAD TO FIFA WORLD CUP.*Terrace.*Green.*Seriale 2\/5/);});
test('201 Glurak never promotes attack 50x; German lookup remains German',()=>{const {d,l,entries}=replay(0),requests=E.recoveryRequests(l,E.reduce(l,entries));E.applyDetails(l,d.phases.find(p=>p.stage==='flipcheck_evidence_detail').result.details,requests);assert.equal(l.pick('collector_number'),null);assert.doesNotMatch(E.query(l),/50X/);assert.equal(E.keyValues(l).language,'de');assert.match(C.requestPlan(l)[0].url,/\/de\/cards/);assert.ok(l.active('statistics_number').some(a=>/50x/i.test(a.value)));assert.equal(E.reduce(l,entries).market_ready,false);});
test('201 Mewtwo query uses translated name full number year SR without site restriction',()=>{const {l,entries}=replay(1);assert.match(E.query(l),/Mewtwo V "135\/127" 2024 SR/);assert.doesNotMatch(E.query(l),/site:/);assert.ok(entries.some(e=>e.family==='Gallant Galaxy'));const r=E.reduce(l,entries);assert.match(r.title,/SR/);assert.doesNotMatch(r.title,/Rarity Symbol|Promotion/);assert.equal(r.market_ready,false,'new visual/catalog evidence is still required');});
test('201 One Piece retains official variant images and separates promo badge from rarity',()=>{const {l,entries}=replay(2),g=E.candidateGroups(l,entries)[0];assert.equal(g.entry.number,'P-110');assert.equal(l.pick('rarity_text'),null);assert.match(E.query(l),/4th Anniversary/);assert.equal(g.entry.variants.length,2);assert.ok(g.entry.variants.every(v=>v.image_url));assert.equal(E.reduce(l,entries).market_ready,false);});
test('specimen serial survives unresolved catalogue and canonical reread removes No. prefix',()=>{const {l}=replay(5);let r=E.reduce(l,[]);assert.equal(r.physical_serial.value,'8/9');assert.match(r.title,/Seriale 8\/9/);E.applyDetails(l,[{field:'collector_number',text:'No. 8',certainty:'clear',evidence_found:true,image_index:1}],[{field:'collector_number',image_index:1,region:l.pick('collector_number').region,key:'test',reason:'catalogue_number_conflict'}]);assert.equal(l.pick('collector_number').value,'8');});
test('crop plan scales relative to each card region; bands preserve provenance and do not invent unreadable fields',()=>{const {l}=replay(0),panels=E.pokemonPanels202(l.base);assert.deepEqual(panels.map(p=>p.role),['whole','upper','lower','artwork']);for(const p of panels){const c=l.base.object_regions[0];assert.ok(p.region.x>=c.x);assert.ok(p.region.y+p.region.height<=c.y+c.height+.00001);}const r=panels[2].region;E.applyIdentityBands202(l,{observations:[{field:'collector_number',text:'9/12',certainty:'clear',image_index:1,region:r},{field:'copyright',text:'',certainty:'clear',image_index:1,region:r}]});assert.deepEqual(E.keyValues(l).numbers,['9/12']);assert.equal(l.pick('collector_number').source,'identity_band');});
test('incompatible modern First Edition is reread; ordinary absent shadow cannot create Shadowless',()=>{const l=E.ingestVision(new E.Ledger({domain:'pokemon'}),{language:'en',observations:[{field:'subject',text:'Example',certainty:'clear',image_index:1},{field:'collector_number',text:'1/99',certainty:'clear',image_index:1}],features:[{field:'stamp',value:'present',description:'First Edition stamp',certainty:'clear',image_index:1},{field:'shadow',value:'absent',description:'No shadow',certainty:'clear',image_index:1}]});const e={subject:'Example',family:'Modern',number:'1/99',year:'2024',language:'en',variants:[{name:'Holo',finish:'holo'}],grounded:true,source:{url:'https://www.pokemon.com/example'}};let r=E.reduce(l,[e]);assert.equal(r.market_ready,false);assert.doesNotMatch(r.title,/Shadowless|1st Edition/);const req=E.recoveryRequests(l,r).find(r=>r.field==='stamp');assert.equal(req.reason,'printing_compatibility');E.applyDetails(l,[{field:'stamp',text:'absent',certainty:'clear',evidence_found:true,image_index:1}],[req]);assert.equal(E.reduce(l,[e]).market_ready,true);});
test('unknown subset cannot merge two genuinely different documented inserts',()=>{const l=E.ingestVision(new E.Ledger({domain:'sports'}),{observations:[{field:'subject',text:'Example',certainty:'clear',image_index:1},{field:'collector_number',text:'8',certainty:'clear',image_index:1}]});const e={subject:'Example',family:'Product',number:'8',grounded:true,source:{url:'https://www.beckett.com/test'}};const r=E.reduce(l,[{...e,subset:'Insert A',subset_known:true},{...e,subset:'Insert B',subset_known:true},{...e,subset:'',subset_known:false}]);assert.equal(r.core_identity.status,'partial');});
