/* Production build-193 UI + HTTP/native boundary. Synthetic pixels carry recorded
   observations; these tests verify decisions and calls, not fresh model accuracy. */
const {test,before,after,afterEach}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),{chromium}=require('playwright');
const D=JSON.parse(require('node:zlib').gunzipSync(require('node:fs').readFileSync(require('node:path').join(__dirname,'fixtures/diagnostics-192.json.gz')))),E=require('../src/main/assets/catalogue-engine');
const root=path.join(__dirname,'../src/main/assets'),nativeSource=fs.readFileSync(path.join(__dirname,'../src/main/java/com/flipcheck/legacy26/ScanSession.java'),'utf8'),allow=new RegExp('^'+JSON.parse(nativeSource.match(/path\.matches\(("(?:[^"\\]|\\.)*")\)/)[1])+'$');
let server,browser,page,origin,d,options,api=[],native=[],errors=[],events=[],ocrIndex=0,release,carrier;
const stages=()=>api.map(b=>b.text.format.name);
const envelope=(payload,web=[])=>({status:'completed',output:[...(web.length?[{type:'web_search_call',status:'completed',action:{type:'search',sources:web},results:web}]:[]),{type:'message',content:[{type:'output_text',text:JSON.stringify(payload)}]}],usage:{input_tokens:350,output_tokens:150}});
async function reset(name,opts={}){
 d=structuredClone(D[name]);options=opts;opts.mutate?.(d);api=[];native=[];errors=[];events=[];ocrIndex=0;release=null;
 await page.goto(origin);await page.waitForFunction(()=>typeof resolveCatalogue193==='function');
 await page.evaluate(lens=>{$('lensServer205').value=lens?'https://lens.example':'';$('lensAccess205').value=lens?'access-testing-123456':'';$('lensEnabled205').checked=true;lensSettingsChanged205();trial={attempts:2,free:true,credits:0};saveTrial();$('apiKey').value='offline-secret-never-export';$('googleApiKey').value='';$('scanBudget').value='.03';window.FlipCheckTestMode='offline-catalogue-engine';},!!opts.lens);
 const count=opts.photoCount||Math.max(1,...d.vision.photo_clues?.map(c=>c.image_index)||[]);
 const images=await page.evaluate(count=>Array.from({length:count},(_,i)=>{const c=document.createElement('canvas');c.width=900;c.height=1200;const g=c.getContext('2d');g.fillStyle=i?'#bbc':'#ccb';g.fillRect(0,0,900,1200);g.fillStyle='#000';g.font='35px sans-serif';g.fillText('SYNTHETIC CARRIER '+i,20,40);return c.toDataURL('image/png');}),count);carrier=images[0];
 await page.locator('#photoBatch').setInputFiles(images.map((s,i)=>({name:'carrier-'+i+'.png',mimeType:'image/png',buffer:Buffer.from(s.split(',')[1],'base64')})));await page.waitForFunction(()=>!photoBusy);
}
async function scan(){await page.locator('#identifyBtn').click();await page.waitForFunction(()=>!apiBusy,{}, {timeout:25000});return page.evaluate(()=>diagnostic26());}
before(async()=>{
 server=http.createServer((req,res)=>{const name=req.url==='/'?'index.html':req.url.slice(1);if(!allow.test('/'+name)||!fs.existsSync(path.join(root,name))){res.writeHead(404);return res.end();}res.setHeader('Content-Type',name.endsWith('.js')?'application/javascript':'text/html');res.end(fs.readFileSync(path.join(root,name)));});await new Promise(r=>server.listen(0,'127.0.0.1',r));origin='http://127.0.0.1:'+server.address().port;
 browser=await chromium.launch({executablePath:process.env.FLIPCHECK_BROWSER_EXECUTABLE||undefined,headless:true,args:['--no-sandbox']});page=await browser.newPage({viewport:{width:412,height:915},serviceWorkers:'block'});
 page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.dismiss());await page.exposeFunction('hostEvent',e=>events.push(e));
 await page.addInitScript(()=>{const send=(id,action,payload)=>fetch('https://offline-native.invalid/'+action,{method:'POST',body:JSON.stringify(payload)}).then(r=>r.json()).then(r=>FlipCheckDirect.receive(id,r));window.FlipCheckGoogle={ocrAvailable(){return true;},request(id,action,payload){send(id,action,JSON.parse(payload));},readText(id,image_data){send(id,'ocr',{image_data});},readTextScript(id,image_data,script){send(id,'ocr',{image_data,script});},cancel(id){hostEvent({kind:'cancel',id});},storeEvidence(kind,data,meta){hostEvent({kind:'evidence',type:kind,bytes:data.length});},evidenceInfo(){return '{}';}};window.FlipCheckHost={buildInfo(){return JSON.stringify({versionCode:193,versionName:'offline',sourceCommit:'offline'});},beginScan(id){hostEvent({kind:'begin',id});queueMicrotask(()=>FlipCheckBackground.started(id,true,''));},endScan(id,snapshot,outcome){hostEvent({kind:'end',id,outcome,snapshot:JSON.parse(snapshot)});},backgroundInfo(){return '{}';},lastScan(){return '{}';},photoPickerInfo(){return '{}';},saveDiagnostic(snapshot){hostEvent({kind:'diagnostic',snapshot});}};});
 await page.route('**/*',async route=>{
  const url=route.request().url();if(url.startsWith(origin+'/'))return route.continue();
  if(url==='https://api.openai.com/v1/responses'){
   const body=JSON.parse(route.request().postData());api.push(body);const kind=body.text.format.name;events.push({kind:'api',stage:kind});
   if(options.hold&&kind==='flipcheck_identification')await new Promise(r=>release=r);
   if(options.httpError&&kind==='flipcheck_identification')return route.fulfill({status:401,json:{error:{message:'Offline unauthorized'}}}).catch(()=>{});
   if(options.incomplete&&kind==='flipcheck_identification'&&api.length===1)return route.fulfill({json:{status:'incomplete',incomplete_details:{reason:'max_output_tokens'},output:[{type:'message',content:[{type:'output_text',text:'{'}]}],usage:{input_tokens:350,output_tokens:150}}});
   let payload=kind==='flipcheck_identification'?(options.packet||d.vision):kind==='flipcheck_pokemon_identity_bands'?{observations:options.bandObservations||[],features:options.bandFeatures||[]}:kind==='flipcheck_evidence_detail'?{details:options.details||[]} :kind==='flipcheck_lens_image_comparison'?{comparisons:options.lensComparisons||[]}:kind==='flipcheck_catalogue_comparison'?{comparisons:options.coreComparisons||[]}:kind==='flipcheck_variant_comparison'?{comparisons:options.comparisonReplies?.[stages().filter(s=>s==='flipcheck_variant_comparison').length-1]||options.comparisons||[]}:kind==='flipcheck_surface_inspection'?(options.surfaceInspections?.[stages().filter(s=>s==='flipcheck_surface_inspection').length-1]||options.surfaceInspection||{surfaces:[],serial_presence:'unclear',serial:{text:'',certainty:'uncertain',evidence_found:false,image_index:1}}): {entries:options.catalogueEntries||[]};
   if(options.malformed&&kind==='flipcheck_identification'){const r=envelope(payload);r.output[0].content[0].text='bad-json';return route.fulfill({json:r});}
   const pages=(options.pagesBySearch?.[stages().filter(s=>s==='flipcheck_catalogue_search').length-1]||d.pages||[]).filter(p=>p.url),web=kind==='flipcheck_catalogue_search'?pages.map(p=>({...p,source_text:p.source_text||p.text||'',snippet:p.text||p.source_text||''})):[];
   const reply=envelope(payload,web),record=options.recordedPhases?.find(p=>p.stage===({flipcheck_identification:'vision',flipcheck_catalogue_search:'flipcheck_catalogue_search'})[kind]);if(record?.usage){reply.usage=record.usage;if(record.webCalls===2&&web.length)reply.output.unshift({...reply.output[0]});}
   return route.fulfill({json:reply}).catch(()=>{});
  }
  if(url.startsWith('https://offline-native.invalid/')){
   const action=url.split('/').pop(),b=JSON.parse(route.request().postData());native.push({action,...b});events.push({kind:'native',action});let reply={status:503};
   if(action==='lens_config')reply=options.lensConfigReplies?.[Math.min(native.filter(n=>n.action==='lens_config').length-1,options.lensConfigReplies.length-1)]||{status:200,body:{enabled:true,protocol:2,provider:'searchapi_google_lens',unitUsd:.004}};
   if(action==='lens')reply={status:200,body:options.lensReply||{state:'ok',providerCalls:1,accountCalls:1,estimatedUsd:.004,billingUnknown:false,candidates:options.lensCandidates||[]}};
   if(action==='ocr')reply=options.noOcr?{state:'ocr_unavailable'}:d.photoOcr?.[ocrIndex++]||{state:'ok',lines:[],text:''};
   if(action==='page'){
    const pages=(options.pagesBySearch?.[Math.max(0,stages().filter(s=>s==='flipcheck_catalogue_search').length-1)]||d.pages).filter(p=>p.url===b.url).sort((a,b)=>(b.text||b.source_text||'').length-(a.text||a.source_text||'').length);if(pages.length)reply={status:200,...pages[0]};
    if(options.certificate&&/psacard.com\/cert\//.test(b.url))reply={status:200,url:b.url,structured_fields:options.certificate};
   }
   if(action==='catalogue'&&options.tcgdex){if(/\/cards\?/.test(b.url))reply={status:200,body:[{id:'ecard3-H23',localId:'H23',name:'Politoed'}]};else if(/\/cards\//.test(b.url))reply={status:200,body:{id:'ecard3-H23',localId:'H23',name:'Politoed',hp:110,attacks:[{name:'Crescita Improvvisa'},{name:'Ranabalzo'},{name:'Spruzza Energia'}],set:{id:'ecard3',name:'Skyridge'},rarity:'Rare Holo',variants:{holo:true}}};else reply={status:200,body:{releaseDate:'2003-05-12'}};}
   if(action==='catalogue'&&options.catalogueReply)reply=options.catalogueReply(b);
   if(action==='image')reply={status:200,image_data:carrier};
   return route.fulfill({json:reply}).catch(()=>{});
  }
  errors.push('Unmocked request '+url);return route.abort();
 });
});
afterEach(async()=>{assert.deepEqual(errors,[]);});after(async()=>{await browser?.close();await new Promise(r=>server.close(r));});
test('193 native host serves every production engine module',async()=>{await reset('politoed');assert.equal(await page.evaluate(()=>FlipCheckCatalogueEngine&&FlipCheckCatalogueSources&&typeof resolveCatalogue193),'function');assert.ok(allow.test('/catalogue-runtime.js'));});
const politoedKeys204=[['collector_number','H23/H32'],['copyright','© 2003 Pokémon / Nintendo']].map(([field,text])=>({field,text,certainty:'clear',image_index:1,region:{image_index:1,x:.1,y:.8,width:.8,height:.1},zone:'footer',alternatives:[]}));
test('202 Politoed closes from structured catalogue after initial and identity-band reads',async()=>{await reset('politoed',{tcgdex:true,bandObservations:politoedKeys204});const out=await scan();assert.equal(out.identification.engine_final,true);assert.equal(out.identification.family,'Skyridge');assert.equal(out.identification.market_ready,true,JSON.stringify(out.identification));assert.deepEqual(stages(),['flipcheck_identification','flipcheck_pokemon_identity_bands']);assert.equal(out.visualAssistance.route,'catalogue_engine');assert.ok(native.some(n=>n.action==='catalogue'));assert.ok(out.visualAssistance.engine.observations.length>0);assert.ok(events.some(e=>e.kind==='end'));assert.equal(await page.locator('#marketBtn').isDisabled(),false);assert.equal(await page.locator('#identNote .confrow').count(),0);assert.equal(await page.locator('#identNote .need').count(),0);});
test('204: missing Italian catalogue searches again without assigning the English edition',async()=>{
 await reset('politoed',{bandObservations:politoedKeys204,mutate(d){d.pages=[];},catalogueReply(b){
  if(b.url.includes('/it/'))return {status:200,body:[]};
  if(/\/cards\?/.test(b.url))return {status:200,body:[{id:'ecard3-H23',localId:'H23',name:'Politoed'},{id:'xy3-18',localId:'18',name:'Politoed'}]};
  if(/\/cards\//.test(b.url))return {status:200,body:{id:'ecard3-H23',localId:'H23',name:'Politoed',hp:110,set:{id:'ecard3',name:'Skyridge'},rarity:'Rare Holo',variants:{holo:true}}};
  return {status:200,body:{releaseDate:'2003-05-12'}};
 }});
 const out=await scan();assert.equal(out.identification.core_identity.status,'partial',JSON.stringify(out.visualAssistance.engine));assert.equal(out.identification.market_ready,false);assert.equal(out.identification.language,'it');assert.equal(out.identification.catalogue_reference_language,null);
 assert.deepEqual(stages(),['flipcheck_identification','flipcheck_pokemon_identity_bands','flipcheck_catalogue_search']);assert.equal(out.visualAssistance.catalogueCoverage.truncated,false);assert.ok(native.some(n=>n.url?.includes('/en/cards?')));assert.ok(!native.some(n=>n.url?.includes('/cards/xy3-18')));
 assert.equal(out.identification.card_identity.rarity,null);assert.equal(await page.locator('#marketBtn').isDisabled(),true);
});
test('a complete local catalogue needs no cross-language fallback',async()=>{
 await reset('politoed',{tcgdex:true,bandObservations:politoedKeys204});const out=await scan();assert.equal(out.identification.market_ready,true);assert.ok(!native.some(n=>n.url?.includes('/en/cards')));assert.deepEqual(stages(),['flipcheck_identification','flipcheck_pokemon_identity_bands']);
});
test('204 clear Politoed keys find the local web entry without the guessed set',async()=>{await reset('politoed',{bandObservations:politoedKeys204});const out=await scan();assert.equal(out.identification.family,'Skyridge',JSON.stringify(out.visualAssistance.engine?.events));assert.equal(out.identification.market_ready,true);assert.equal(stages().filter(s=>s==='flipcheck_catalogue_search').length,1);assert.ok(out.visualAssistance.queries.every(q=>!q.includes('Aquapolis')));});
test('193 Boniface consumes one serial crop and no further search once /5 is read',async()=>{await reset('boniface',{details:[{field:'serial',text:'2/5',certainty:'clear',image_index:2}]});const out=await scan();assert.equal(out.identification.market_ready,true,JSON.stringify(out.visualAssistance.engine?.events));assert.equal(out.identification.variant,'Green');assert.equal(out.identification.physical_serial.value,'2/5');assert.deepEqual(stages(),['flipcheck_identification','flipcheck_evidence_detail','flipcheck_catalogue_search']);assert.equal(out.visualAssistance.detailReread.requested[0].rotation,90);assert.ok(events.filter(e=>e.type==='original').length===2);});
test('193 unreadable serial retains card identity without inventing /5',async()=>{await reset('boniface');const out=await scan();assert.equal(out.identification.core_identity.status,'confirmed');assert.equal(out.identification.market_ready,false);assert.equal(out.identification.serial_number,null);assert.match(out.identification.next_photo_request,/numerazione/);assert.equal(stages().filter(s=>s==='flipcheck_evidence_detail').length,1);});
test('193 Doncic keeps green and number 280; no statistic-based serial crop',async()=>{await reset('doncic');const out=await scan();assert.equal(out.identification.core_identity.status,'confirmed',JSON.stringify(out.visualAssistance.engine?.events));assert.match(out.identification.model,/280/);assert.ok(out.visualAssistance.queries.every(q=>/green/.test(q)));assert.ok(!stages().includes('flipcheck_evidence_detail'));assert.equal(out.identification.market_ready,false);});
test('193 box retains printed product, rejects incompatible formats and avoids duplicate crops',async()=>{await reset('topps');const out=await scan();assert.equal(out.identification.core_identity.status,'confirmed');assert.equal(out.identification.market_ready,false);assert.match(out.identification.title,/Chrome/i);assert.doesNotMatch(out.identification.variant,/Hobby|Jumbo/);assert.deepEqual(stages(),['flipcheck_identification','flipcheck_catalogue_search']);assert.match(out.identification.next_photo_request,/confezione/);});
test('193 PSA label fallback makes no OCR, web or further vision requests',async()=>{await reset('psa');const out=await scan();assert.equal(out.identification.market_ready,true,JSON.stringify(out.identification));assert.match(out.identification.normalized_query,/PSA.*9|9.*PSA/);assert.deepEqual(stages(),['flipcheck_identification']);assert.ok(!native.some(n=>n.action==='ocr'||n.action==='catalogue'));assert.equal(out.visualAssistance.route,'slab_label');});
test('complete PSA label closes in the production UI despite uncertain secondary text',async()=>{
 await reset('psa',{mutate(d){Object.assign(d.vision.slab_reading,{certainty:'uncertain',title_certainty:'clear',grade_certainty:'clear',certificate_certainty:'clear',secondary_text_incomplete:true,subgrades:[]});}});
 const out=await scan();assert.equal(out.identification.closure_status,'resolved');assert.equal(out.identification.next_photo_request,null);assert.equal(out.identification.grading.certificate_verified,false);assert.equal(out.visualAssistance.jobStatus,'variant_resolved');assert.equal(await page.locator('#marketBtn').isDisabled(),false);assert.deepEqual(stages(),['flipcheck_identification']);
});
function stampPacket(description='Edition area unreadable'){
 return {domain:'pokemon',kind:'card',category:'Pokémon',language:'en',object_unit:'single',object_regions:[],observations:[['subject','Example'],['collector_number','1/64'],['season','1999']].map(([field,text])=>({field,text,certainty:'clear',image_index:1,region:null,zone:'front',alternatives:[]})),features:[{field:'finish',value:'holo',description:'Holo finish',certainty:'clear',image_index:1,region:null,zone:'artwork'},{field:'stamp',value:'unclear',description,certainty:'clear',image_index:1,region:null,zone:'other'}],hypotheses:[],slab_reading:null};
}
function stampPages(d){d.pages=[{url:'https://www.beckett.com/test-jungle',title:'1999 Jungle Example 1/64',text:'1999 Jungle Example 1/64',catalogue_rows:[{headers:['Card Number','Player','Set','Year'],cells:['1/64','Example','Jungle','1999'],text:'1/64 Example Jungle 1999'}]}];}
test('detail confirmation reaches final identity, diagnostics and visible stamp text together',async()=>{
 for(const [value,label] of [['present','Timbro 1st Edition visibile'],['absent','Timbro 1st Edition assente']]){
  await reset('politoed',{packet:stampPacket(),noOcr:true,mutate:stampPages,details:[{field:'stamp',text:value,certainty:'clear',evidence_found:true,image_index:1}]});
  const out=await scan(),r=out.identification;assert.equal(r.printing_check?.stamp,'confirmed',JSON.stringify(out.visualAssistance.engine));assert.equal(r.printing_check.stamp_presence,value);assert.equal(r.pokemon_printing.first_edition_stamp,value);assert.equal(r.job_status,'variant_resolved');assert.equal(out.visualAssistance.jobStatus,r.job_status);assert.ok(out.visualAssistance.detailReread.committed_revision<=out.visualAssistance.stateRevision);assert.equal(r.next_photo_request,null);assert.match(await page.locator('#printingPanel').innerText(),new RegExp(label));assert.equal(await page.locator('#marketBtn').isDisabled(),false);assert.deepEqual(stages(),['flipcheck_identification','flipcheck_catalogue_search','flipcheck_evidence_detail']);
 }
});
test('affirmative original-photo text resolves an unclear stamp before another detail call',async()=>{
 await reset('politoed',{packet:stampPacket('Stamp 1st Edition visibile sotto l’illustrazione'),noOcr:true,mutate:stampPages});const out=await scan();assert.equal(out.identification.printing_check?.stamp,'confirmed');assert.equal(out.identification.market_ready,true);assert.ok(!stages().includes('flipcheck_evidence_detail'));assert.match(await page.locator('#printingPanel').innerText(),/Timbro 1st Edition visibile/);
});
test('193 malformed response cannot publish identity and releases lifecycle',async()=>{await reset('politoed',{malformed:true});const out=await scan();assert.equal(out.identification,null);assert.deepEqual(stages(),['flipcheck_identification']);assert.ok(events.some(e=>e.kind==='end'));assert.equal(await page.locator('#identifyBtn').isDisabled(),false);});
test('193 provider failure releases controls without retries',async()=>{await reset('politoed',{httpError:true});const out=await scan();assert.equal(out.identification,null);assert.equal(api.length,1);assert.ok(events.some(e=>e.kind==='end'));});
test('193 incomplete initial response retries once and records both costs',async()=>{await reset('politoed',{incomplete:true,tcgdex:true,bandObservations:politoedKeys204});const out=await scan();assert.equal(out.identification.market_ready,true);assert.equal(stages().filter(s=>s==='flipcheck_identification').length,2);assert.equal(out.phases.filter(p=>p.stage==='vision').length,1);assert.ok(out.visualAssistance.budget.spentOrReservedUsd>0);});
test('193 cancellation ignores late response and starts no retrieval',async()=>{await reset('politoed',{hold:true});await page.locator('#identifyBtn').click();await page.waitForFunction(()=>apiBusy);while(!release)await new Promise(r=>setTimeout(r,10));await page.locator('#cancelScan').click();release();await page.waitForFunction(()=>!apiBusy);assert.equal(await page.evaluate(()=>ident),null);assert.equal(api.length,1);assert.equal(native.length,0);});
test('193 final result cannot be reopened by the legacy final policy',async()=>{await reset('politoed',{tcgdex:true,bandObservations:politoedKeys204});await scan();const x=await page.evaluate(()=>{const saved=JSON.stringify(ident);ident=enforceIdentificationPolicy(ident);ident=syncIdentity169(ident);return {same:JSON.stringify(ident)===saved,ready:ident.market_ready};});assert.deepEqual(x,{same:true,ready:true});});
test('193 exports omit API keys and image payloads but include the immutable ledger',async()=>{await reset('boniface');const out=await scan(),text=JSON.stringify(out);assert.doesNotMatch(text,/offline-secret-never-export|data:image|Bearer/);assert.ok(out.visualAssistance.engine.observations.some(o=>o.source==='local_ocr'));await page.screenshot({path:'/tmp/flipcheck26-printing.png',fullPage:true});});

test('193 new observation schema reaches the final UI, without legacy identity fields',async()=>{
 const v=D.politoed.vision,packet={domain:'pokemon',kind:'card',category:'Pokémon',language:'Italian',object_unit:'single',object_regions:v.object_regions,observations:v.photo_clues.map(c=>({field:c.role==='text'?(c.text==='110 PV'?'hp':'attack'):c.role,text:c.text,certainty:c.certainty,image_index:c.image_index,region:c.region,zone:'front',alternatives:[]})),features:[{field:'finish',value:'holo',description:'Holographic foil finish',certainty:'clear',image_index:1,region:null,zone:'artwork'}],hypotheses:[{field:'family',value:'Aquapolis'}],slab_reading:null};
 await reset('politoed',{packet,tcgdex:true,bandObservations:politoedKeys204});const out=await scan();assert.equal(out.identification.family,'Skyridge');assert.equal(out.identification.market_ready,true,JSON.stringify(out.visualAssistance.engine));assert.equal(out.identification.language,'it');assert.ok(api[0].text.format.schema.required.includes('observations'));assert.ok(!api[0].text.format.schema.required.includes('model'));assert.deepEqual(stages(),['flipcheck_identification','flipcheck_pokemon_identity_bands']);
});

test('193 official PSA certificate closes identity with the stored grade and no later AI',async()=>{await reset('psa',{certificate:[['Cert Number','64613920'],['Year','1999'],['Set Name','P.M. Japanese CD Promo'],['Card Name','Charizard'],['Card Number','6'],['Variation','Holo'],['Grade','MINT 9']].map(([label,value])=>({label,value}))});const out=await scan();assert.equal(out.visualAssistance.route,'slab_certificate');assert.equal(out.identification.slab_verification.certificate_verified,true);assert.equal(out.identification.market_ready,true);assert.deepEqual(stages(),['flipcheck_identification']);assert.equal(native.length,1);});
test('193 variant comparison needs independent visual details, not just local similarity',async()=>{
 for(const features of [1,2]){
  await reset('boniface',{comparisons:[{reference_id:'variant0',match:true,conflicts:[],features:[{field:'border_color',original:'green',reference:'green',agrees:true,certainty:'clear'},{field:'pattern',original:'wave',reference:'wave',agrees:true,certainty:'clear'}].slice(0,features)}]});
  const out=await page.evaluate(async vision=>{scan164=newContext164();lastVisionReading=vision;const E=FlipCheckCatalogueEngine,l=E.ingestVision(new E.Ledger(vision),vision),entry={subject:'Victor Boniface',number:'21',family:'Select Road to FIFA World Cup 2026',year:'2025-26',source:{url:'https://www.beckett.com/green-wave'},grounded:true,variants:[{name:'Green Wave',colors:['green'],patterns:['wave'],visual_required:true}]},pages=[{url:entry.source.url,image_details:[{image_url:'https://images.beckett.com/green-wave.jpg',caption:'Victor Boniface Green Wave'}]}];const before=E.reduce(l,[entry]);await compareVariants193(l,before,scan164,pages);return {result:E.reduce(l,[entry]),measurements:scan164.localReferenceComparisons};},d.vision);
  assert.equal(out.result.market_ready,features===2);assert.ok(out.measurements.length>0);assert.deepEqual(stages(),['flipcheck_variant_comparison']);assert.ok(native.some(n=>n.action==='image'));
 }
});

test('193 fragmented Jordan name launches candidate comparison without requiring a back photo',async()=>{
 await reset('jordan191',{photoCount:1,coreComparisons:[{reference_id:'core1',match:true,ambiguous:false,reference_subject:'MICHAEL JORDAN',reference_number:'141',conflicts:[],features:[{field:'artwork',original:'portrait',reference:'portrait',agrees:true,certainty:'clear'},{field:'layout',original:'horizontal frame and flag',reference:'horizontal frame and flag',agrees:true,certainty:'clear'}]}],mutate(d){d.pages=['A','B'].map(id=>({url:'https://www.paniniamerica.net/test-product-'+id,title:'2031 Product '+id+' #141 MICHAEL JORDAN',text:'Set:\n2031 Panini Product '+id+'\nPlayer:\nMICHAEL JORDAN\nCard Number: 141',image_details:[{image_url:'https://www.paniniamerica.net/test-'+id+'.jpg',caption:'MICHAEL JORDAN #141 Product '+id}]}));}});
 const out=await scan();assert.equal(out.identification.core_identity.status,'confirmed',JSON.stringify(out.visualAssistance.engine?.events));assert.equal(out.identification.family,'Product B');assert.ok(out.visualAssistance.queries[0].includes('MICHAEL JORDAN'));assert.ok(out.visualAssistance.queries[0].includes('USA'));assert.ok(stages().includes('flipcheck_catalogue_comparison'));assert.equal(out.uploadedImageCount,1);
});

function promoPacket(){return {domain:'onepiece',kind:'card',category:'One Piece',language:'en',object_unit:'single',object_regions:[],observations:[['subject','Example'],['collector_number','P-110'],['product','CHARACTER'],['subset','Straw Hat Crew'],['text','4th Anniversary']].map(([field,text])=>({field,text,certainty:'clear',image_index:1,region:null,zone:'front',alternatives:[]})),features:[],hypotheses:[],slab_reading:null};}
test('196 catalogue outages finish the scan without demanding another photo or leaking Pokemon fields',async()=>{
 await reset('politoed',{packet:promoPacket(),noOcr:true,mutate(d){d.pages=[];}});const out=await scan(),r=out.identification;
 assert.equal(r.core_identity.status,'partial');assert.equal(r.market_ready,false);assert.equal(r.next_photo_request,null);assert.equal(r.pokemon_printing,undefined);assert.equal(out.visionResult.pokemon_printing,undefined);
 assert.equal(stages().filter(s=>s==='flipcheck_catalogue_search').length,1);assert.ok(native.some(n=>n.url?.includes('asia-en.onepiece-cardgame.com/cardlist/?freewords=P-110')));assert.match(out.visualAssistance.queries[0],/P-110.*4th Anniversary/);
 assert.ok(out.visualAssistance.catalogueRequests.every(r=>r.state!=='requested'&&r.reason));assert.equal(await page.locator('#addConfirmPhoto').isVisible(),false);assert.equal(await page.locator('#identNote .need').count(),0);assert.ok(events.some(e=>e.kind==='end'));
});
test('196 regional official lookup confirms the base while the promo artwork remains unconfirmed',async()=>{
 await reset('politoed',{packet:promoPacket(),noOcr:true,mutate(d){d.pages=[{url:'https://asia-en.onepiece-cardgame.com/cardlist/?freewords=P-110',text:'P-110 | P | CHARACTER\nExample\nCard Set(s)\nPromotional Cards'}];}});
 const out=await scan();assert.equal(out.identification.core_identity.status,'confirmed');assert.equal(out.identification.market_ready,false);assert.deepEqual(out.identification.variant_resolution.pending,['variant']);assert.equal(out.identification.pokemon_printing,undefined);
});
test('196 evolution text no longer blocks structured Pokemon identity or launches a redundant catalogue search',async()=>{
 const packet=stampPacket();packet.observations.push({field:'product',text:'Evolves from Another; Stage 2',certainty:'clear',image_index:1,region:null,zone:'front',alternatives:[]});
 packet.features=packet.features.filter(f=>f.field!=='stamp');packet.features.push({field:'stamp',value:'present',description:'1st Edition stamp visible under artwork',certainty:'clear',image_index:1,region:null,zone:'other'});
 await reset('politoed',{packet,noOcr:true,catalogueReply(b){if(/\/cards\?/.test(b.url))return {status:200,body:[{id:'base1-1',localId:'1',name:'Example'}]};if(/\/cards\//.test(b.url))return {status:200,body:{id:'base1-1',localId:'1',name:'Example',set:{id:'base1',name:'Base Set',cardCount:{official:64}},variants:{holo:true}}};return {status:200,body:{releaseDate:'1999-01-09'}};},mutate(d){d.pages=[];}});
 const out=await scan();assert.equal(out.identification.core_identity.status,'confirmed');assert.equal(out.identification.family,'Base Set');assert.ok(!stages().includes('flipcheck_catalogue_search'));assert.equal(out.identification.market_ready,false);assert.deepEqual(out.identification.variant_resolution.pending,['shadow']);
});

async function exportedFailure(opts){
 await reset('politoed',opts);const out=await scan();
 assert.equal(await page.locator('#saveScanDiagnostic').isVisible(),true);assert.equal(await page.locator('#saveScanDiagnostic').isDisabled(),false);
 await page.locator('#saveScanDiagnostic').click();await page.waitForTimeout(100);
 const saved=JSON.parse(events.find(e=>e.kind==='diagnostic').snapshot);
 assert.equal(saved.identification?.exact_identity_status||null,out.identification?.exact_identity_status||null);
 assert.doesNotMatch(JSON.stringify(saved),/offline-secret-never-export|data:image|Bearer/);return saved;
}
test('197 scan-page diagnostic export works after an initial API failure without identity',async()=>{
 const saved=await exportedFailure({httpError:true});assert.equal(saved.identification,null);assert.equal(saved.scanStatus,'technical_error');assert.ok(saved.visualAssistance);assert.equal(api.length,1);
});
test('197 malformed identity responses remain exportable with null identity',async()=>{
 const saved=await exportedFailure({malformed:true});assert.equal(saved.identification,null);assert.equal(saved.scanStatus,'technical_error');
});
test('197 unavailable catalogue report is saved without confirming identity',async()=>{
 const saved=await exportedFailure({packet:promoPacket(),noOcr:true,mutate(d){d.pages=[];}});assert.equal(saved.identification.market_ready,false);assert.equal(saved.identification.core_identity.status,'partial');assert.ok(saved.visualAssistance.catalogueRequests.length>=2);
});
test('197 large reports retain all data beyond the old native 400k limit and cap extreme reports explicitly',async()=>{
 await reset('politoed');const checks=await page.evaluate(()=>{
  const normal={identification:null,scanStatus:'technical_error',text:'x'.repeat(500000)},plain=diagnosticPayload197(normal);
  const large={identification:null,scanStatus:'technical_error',visualAssistance:{state:'service_unavailable',textReferences:[{url:'https://catalog.example/card',text:'x'.repeat(8000000)}]}},bounded=diagnosticPayload197(large);
  return {lossless:JSON.stringify(JSON.parse(plain))===JSON.stringify(normal),plainLength:plain.length,boundedLength:bounded.length,reduced:JSON.parse(bounded),originalLength:large.visualAssistance.textReferences[0].text.length};
 });assert.equal(checks.lossless,true);assert.ok(checks.plainLength>400000);assert.ok(checks.boundedLength<8000000);assert.equal(checks.reduced.diagnosticExport.truncated,true);assert.equal(checks.reduced.scanStatus,'technical_error');assert.equal(checks.originalLength,8000000);
});

const D197=JSON.parse(require('node:zlib').gunzipSync(fs.readFileSync(path.join(__dirname,'fixtures/diagnostics-197.json.gz'))));
function replay197Options(n,extra={}){const recorded=D197[n];return {packet:recorded.vision,photoCount:n>1?2:1,catalogueEntries:recorded.phases.find(p=>p.stage==='flipcheck_catalogue_search')?.result.entries||[],mutate(d){d.pages=recorded.pages;d.photoOcr=recorded.photoOcr;},...extra};}
test('198 actual Boniface pipeline resolves recorded /5 after canonical checklist grouping',async()=>{
 await reset('boniface',replay197Options(2,{details:D197[2].phases.find(p=>p.stage==='flipcheck_evidence_detail').result.details}));const out=await scan();assert.equal(out.identification.market_ready,true,JSON.stringify(out.identification));assert.equal(out.identification.physical_serial.value,'2/5');assert.equal(out.identification.variant,'Green');assert.equal(stages().filter(s=>s==='flipcheck_catalogue_search').length,1);assert.ok(events.some(e=>e.kind==='end'));
});
test('198 actual Doncic pipeline preserves base and unresolved parallel without a redundant search',async()=>{
 await reset('doncic',replay197Options(3));const out=await scan();assert.equal(out.identification.core_identity.status,'confirmed');assert.equal(out.identification.market_ready,false);assert.equal(stages().filter(s=>s==='flipcheck_catalogue_search').length,1);assert.equal(out.identification.assistance_state,'physical_detail_needed');
});
const artworkMatch=id=>({reference_id:id,match:true,conflicts:[],features:[{field:'artwork',original:'Distinct foreground pose and buildings',reference:'Distinct foreground pose and buildings',agrees:true,certainty:'clear'},{field:'stamp',original:'4th Anniversary lower-left emblem',reference:'4th Anniversary lower-left emblem',agrees:true,certainty:'clear'}]});
test('198 official same-code artworks are compared before search, with the selected image preserved',async()=>{
 await reset('politoed',replay197Options(1,{comparisons:[artworkMatch('variant1')]}));const out=await scan();assert.equal(out.identification.market_ready,true,JSON.stringify(out.identification));assert.match(out.identification.variant_resolution.proof[0].image_url,/P-110_p1/);assert.deepEqual(stages(),['flipcheck_identification','flipcheck_variant_comparison']);assert.equal(native.filter(n=>n.action==='image').length,2);assert.equal(await page.locator('#marketBtn').isDisabled(),false);
});
test('198 matching both official artworks leaves the print unresolved and still allows saving the report',async()=>{
 await reset('politoed',replay197Options(1,{comparisons:[artworkMatch('variant0'),artworkMatch('variant1')]}));const out=await scan();assert.equal(out.identification.core_identity.status,'confirmed');assert.equal(out.identification.market_ready,false);assert.match(out.identification.next_photo_request,/illustrazione/);await page.locator('#saveScanDiagnostic').click();await page.waitForTimeout(30);const saved=events.find(e=>e.kind==='diagnostic');assert.ok(saved);assert.equal(JSON.parse(saved.snapshot).identification.core_identity.status,'confirmed');
});

const D198=JSON.parse(require('zlib').gunzipSync(fs.readFileSync(path.join(__dirname,'fixtures/diagnostics-198.json.gz'))));
const fullSurface199=()=>({surfaces:[{side:'front',image_index:1,fully_visible:true,legible:true},{side:'back',image_index:2,fully_visible:true,legible:true}],serial_presence:'absent',serial:{text:'',certainty:'uncertain',evidence_found:false,image_index:2}});
function replay198Options(n,extra={}){const recorded=D198[n];return {packet:recorded.vision,photoCount:2,recordedPhases:recorded.phases,catalogueEntries:recorded.phases.find(p=>p.stage==='flipcheck_catalogue_search')?.result.entries||[],mutate(d){d.pages=recorded.pages;d.photoOcr=recorded.photoOcr;},...extra};}
for(const [n,name] of [[0,'Boniface serial crop'],[1,'Doncic green rc declaration'],[2,'Doncic inspected front/back'],[3,'Kobe corrected number and base printing']])test('199 recorded scan: '+name+' completes with explicit new evidence inside the recorded budget',async()=>{
 const extra=n===0?{details:[{field:'serial',text:'2/5',certainty:'clear',evidence_found:true,image_index:2}]}:n===3?{details:[{field:'collector_number',text:'81',certainty:'clear',evidence_found:true,image_index:2}],surfaceInspection:fullSurface199()}:n===2?{surfaceInspection:fullSurface199()}:{};
 await reset('boniface',replay198Options(n,extra));if(n===1)await page.locator('#details').fill('green rc');const out=await scan(),r=out.identification;assert.equal(r.market_ready,true,JSON.stringify({r,events:out.visualAssistance.engine?.events}));assert.equal(r.variant,n===3?'Base':'Green');assert.ok(out.visualAssistance.budget.spentOrReservedUsd<=.03);assert.equal(stages().filter(s=>s==='flipcheck_catalogue_search').length,1);assert.equal(await page.locator('#marketBtn').isDisabled(),false);
 if(n===0){assert.equal(r.physical_serial.value,'2/5');assert.equal(out.visualAssistance.detailReread.requested[0].rotation,90);assert.ok(out.visualAssistance.detailReread.requested[0].region.x<.8);}
 if(n===1){assert.equal(r.variant_resolution.variant_origin,'user_declaration');assert.ok(!stages().includes('flipcheck_surface_inspection'));}
 if(n===2||n===3){assert.ok(stages().includes('flipcheck_surface_inspection'));const body=api.find(b=>b.text.format.name==='flipcheck_surface_inspection');assert.equal(body.input[0].content.filter(c=>c.type==='input_image').length,1);}
 if(n===3){assert.equal(r.card_identity.number,'81');assert.equal(r.source_confirmed_year,'1997-98');}
});
test('199 user can apply green rc after a pending scan with no new API calls and coherent exported state',async()=>{
 await reset('doncic',replay198Options(1));let out=await scan();assert.equal(out.identification.market_ready,false);const before=api.length,revision=out.visualAssistance.stateRevision;
 await page.locator('#details').fill('green rc');await page.locator('#applyUserDetails').click();out=await page.evaluate(()=>diagnostic26());assert.equal(api.length,before);assert.equal(out.identification.market_ready,true);assert.equal(out.visualAssistance.jobStatus,'variant_resolved');assert.equal(out.visualAssistance.stateRevision,revision+1);assert.equal(out.visualAssistance.engine.user_details,'green rc');assert.equal(await page.locator('#marketBtn').isDisabled(),false);assert.match(await page.locator('#runStatus').innerText(),/dichiarata dall’utente/);
 await page.locator('#saveScanDiagnostic').click();await page.waitForTimeout(30);assert.equal(JSON.parse(events.find(e=>e.kind==='diagnostic').snapshot).identification.variant_resolution.variant_origin,'user_declaration');
});
test('199 unclear surface check does not close a parallel or request another catalogue search',async()=>{
 const reply=fullSurface199();reply.surfaces[1].legible=false;await reset('doncic',replay198Options(2,{surfaceInspection:reply}));const out=await scan();assert.equal(out.identification.market_ready,false);assert.equal(out.identification.core_identity.status,'confirmed');assert.equal(stages().filter(s=>s==='flipcheck_catalogue_search').length,1);assert.ok(await page.locator('#saveScanDiagnostic').isVisible());
});

const D199=JSON.parse(require('zlib').gunzipSync(fs.readFileSync(path.join(__dirname,'fixtures/diagnostics-199.json.gz'))));
function replay199Options(n,extra={}){const r=D199[n];return {packet:r.vision,photoCount:n===3?1:2,recordedPhases:r.phases,catalogueEntries:r.phases.find(p=>p.stage==='flipcheck_catalogue_search')?.result.entries||[],mutate(d){d.pages=r.pages;d.photoOcr=r.photoOcr;},...extra};}
test('200 real Boniface serial appears in visible identity and exported title',async()=>{
 await reset('boniface',replay199Options(0,{details:D199[0].phases.find(p=>p.stage==='flipcheck_evidence_detail').result.details}));const out=await scan();assert.equal(out.identification.market_ready,true);assert.match(await page.locator('#identTitle').innerText(),/Green.*Seriale 2\/5/);assert.equal(out.identification.title,out.identification.identity_display);
});
test('200 real Doncic retries only the illegible inspection and closes when new original evidence proves absence',async()=>{
 const first=D199[1].phases.find(p=>p.stage==='flipcheck_surface_inspection').result;
 await reset('doncic',replay199Options(1,{surfaceInspections:[first,fullSurface199()]}));const out=await scan();assert.equal(out.identification.market_ready,true,JSON.stringify(out.visualAssistance.engine.events));assert.match(await page.locator('#identTitle').innerText(),/Green · RC/);assert.equal(stages().filter(s=>s==='flipcheck_surface_inspection').length,2);assert.equal(stages().filter(s=>s==='flipcheck_catalogue_search').length,1);assert.ok(out.usage.cost<=.03);assert.equal(out.identification.card_identity.rookie_origin,'original_photo');
});
test('200 real declared Doncic keeps Green and RC without further vision',async()=>{
 await reset('doncic',replay199Options(2));await page.locator('#details').fill('Green rc');const out=await scan();assert.equal(out.identification.market_ready,true);assert.match(await page.locator('#identTitle').innerText(),/Green · RC/);assert.ok(!stages().includes('flipcheck_surface_inspection'));
});
test('200 real Kobe recovers first-page PMG catalogue and closes after number correction and physical inspection',async()=>{
 await reset('boniface',replay199Options(4,{details:D199[4].phases.find(p=>p.stage==='flipcheck_evidence_detail').result.details,surfaceInspection:fullSurface199(),mutate(d){d.pages=D199[4].pages.slice(0,17);d.photoOcr=D199[4].photoOcr;}}));const out=await scan();assert.equal(out.identification.market_ready,true,JSON.stringify(out.visualAssistance.engine.events));assert.match(out.identification.title,/#81.*Base/);assert.doesNotMatch(out.identification.title,/RC/);assert.equal(stages().filter(s=>s==='flipcheck_catalogue_search').length,1);assert.ok(out.usage.cost<=.03);
});
test('200 Luffy set-code crop runs before retrieval and a newly verified P-110 uses official artwork',async()=>{
 await reset('politoed',replay199Options(3,{details:[{field:'collector_number',text:'P-110',certainty:'clear',evidence_found:true,image_index:1}],comparisons:[artworkMatch('variant1')],mutate(d){d.pages=D197[1].pages;d.photoOcr=D199[3].photoOcr;}}));const out=await scan();assert.equal(out.identification.market_ready,true,JSON.stringify(out.visualAssistance.engine.events));assert.equal(out.identification.card_identity.number,'P-110');assert.deepEqual(stages().slice(0,2),['flipcheck_identification','flipcheck_evidence_detail']);assert.ok(native.some(n=>n.url?.includes('freewords=P-110')));assert.ok(!native.some(n=>n.url?.includes('freewords=P-010')));assert.equal(out.identification.pokemon_printing,undefined);assert.ok(out.usage.cost<=.03);
});
test('200 newly available variants after a later catalogue phase trigger physical inspection when budget permits',async()=>{
 const url='https://www.beckett.com/test-later',base={url,title:'2018-19 Prizm Basketball Checklist',text:'Base\n280 Luka Doncic'},rich={...base,text:base.text+'\nGreen\nGreen Pulsar /25'};
 await reset('doncic',{packet:D199[1].vision,photoCount:2,noOcr:true,pagesBySearch:[[base],[rich]],surfaceInspection:fullSurface199(),mutate(d){d.pages=[];}});await page.evaluate(()=>{const previous=newContext164;newContext164=function(){const ctx=previous();ctx.budget.maxUsd=.05;return ctx;};});const out=await scan();assert.equal(out.identification.market_ready,true,JSON.stringify(out.visualAssistance.engine.events));assert.deepEqual(stages(),['flipcheck_identification','flipcheck_catalogue_search','flipcheck_catalogue_search','flipcheck_surface_inspection']);
});

const D200=JSON.parse(require('zlib').gunzipSync(fs.readFileSync(path.join(__dirname,'fixtures/diagnostics-200.json.gz'))));
function replay200Options(n,extra={}){const r=D200[n];return {packet:r.vision,photoCount:[4,5,6,7,8,9].includes(n)?1:2,recordedPhases:r.phases,catalogueEntries:r.phases.find(p=>p.stage==='flipcheck_catalogue_search')?.result.entries||[],mutate(d){d.pages=r.pages;d.photoOcr=r.photoOcr;},...extra};}
test('201 real Glurak reaches visible Box Topper identity with original fraction and matching export state',async()=>{await reset('politoed',replay200Options(6,{details:D200[6].phases.find(p=>p.stage==='flipcheck_evidence_detail').result.details}));const out=await scan();assert.equal(out.identification.market_ready,true,JSON.stringify(out.visualAssistance.engine.events));assert.match(await page.locator('#identTitle').innerText(),/2003.*BOX TOPPER.*9\/12/i);assert.equal(out.identification.exact_identity_status,'confirmed');assert.equal(out.visualAssistance.jobStatus,'variant_resolved');assert.equal(await page.locator('#marketBtn').isDisabled(),false);});
test('201 CD Promo false positive stays unconfirmed after the actual Expedition search and Holo result',async()=>{await reset('politoed',replay200Options(9,{details:D200[9].phases.find(p=>p.stage==='flipcheck_evidence_detail').result.details}));const out=await scan();assert.equal(out.identification.market_ready,false);assert.doesNotMatch(out.identification.title,/Expedition|6\/165/);assert.equal(out.identification.pokedex_number,'006');assert.equal(await page.locator('#marketBtn').isDisabled(),true);assert.ok(out.visualAssistance.queries.every(q=>!q.includes('"6"')));assert.ok(!api.some(b=>b.text.format.name==='flipcheck_evidence_detail'&&JSON.stringify(b.input).includes('"field":"collector_number"')));await page.evaluate(()=>exportDiagnostic197());await page.waitForTimeout(30);assert.ok(events.some(e=>e.kind==='diagnostic'));});
test('201 real Curry search excludes OFF90 and never spends a Vision call on the activation code',async()=>{await reset('doncic',replay200Options(2));const out=await scan();assert.equal(out.identification.market_ready,false);assert.ok(out.visualAssistance.queries.length>0);assert.ok(out.visualAssistance.queries.every(q=>!q.includes('"90"')&&!q.includes('XPJP')));assert.ok(!api.filter(b=>b.text.format.name==='flipcheck_evidence_detail').some(b=>JSON.stringify(b.input).includes('XPJP')));assert.equal(out.identification.serial_number,null);});
test('201 Boniface serial is reread before paid search and reaches the title after catalogue recovery',async()=>{await reset('boniface',replay200Options(0,{details:[{field:'serial',text:'2/5',certainty:'clear',evidence_found:true,image_index:2}],mutate(d){d.pages=D199[0].pages;d.photoOcr=D200[0].photoOcr;}}));const out=await scan();assert.equal(out.identification.market_ready,true,JSON.stringify(out.visualAssistance.engine.events));assert.ok(stages().indexOf('flipcheck_evidence_detail')<stages().indexOf('flipcheck_catalogue_search'));assert.match(await page.locator('#identTitle').innerText(),/Green.*Seriale 2\/5/);assert.ok(out.visualAssistance.budget.spentOrReservedUsd<=.03);});
test('201 repeated Bandai SAMPLE conflict triggers one cached-image recheck, never promotes WINNER',async()=>{const first=D200[4].phases.find(p=>p.stage==='flipcheck_variant_comparison').result.comparisons;await reset('politoed',replay200Options(4,{comparisonReplies:[first,[artworkMatch('variant0')]]}));const out=await scan();assert.equal(out.identification.market_ready,true,JSON.stringify(out.visualAssistance.engine.events));assert.equal(stages().filter(s=>s==='flipcheck_variant_comparison').length,2);assert.equal(native.filter(n=>n.action==='image').length,2);assert.ok(out.identification.variant_resolution.proof.some(p=>p.image_url?.includes('/P-110.png')));assert.ok(!out.identification.variant_resolution.proof.some(p=>p.image_url?.includes('_p1')));});

test('201 conservative budget stops a second paid discovery while preserving base identity and report export',async()=>{const base={url:'https://www.beckett.com/test-budget',title:'2018-19 Prizm Basketball Checklist',text:'Base\n280 Luka Doncic'};await reset('doncic',{packet:D199[1].vision,photoCount:2,noOcr:true,pagesBySearch:[[base],[{...base,text:base.text+'\nGreen\nGreen Pulsar /25'}]],mutate(d){d.pages=[];}});const out=await scan();assert.equal(out.identification.core_identity.status,'confirmed');assert.equal(out.identification.market_ready,false);assert.equal(out.identification.assistance_state,'budget_exhausted');assert.equal(out.identification.next_photo_request,null);assert.equal(stages().filter(s=>s==='flipcheck_catalogue_search').length,1);assert.ok(out.visualAssistance.budget.spentOrReservedUsd<=.03);await page.evaluate(()=>exportDiagnostic197());await page.waitForTimeout(30);assert.ok(events.some(e=>e.kind==='diagnostic'));});

const D201=JSON.parse(require('zlib').gunzipSync(fs.readFileSync(path.join(__dirname,'fixtures/diagnostics-201.json.gz'))));
function replay201Options(n,extra={}){const r=D201[n];return {packet:r.vision,photoCount:n>=3?2:1,recordedPhases:r.phases,catalogueEntries:r.phases.find(p=>p.stage==='flipcheck_catalogue_search')?.result.entries||[],mutate(d){d.pages=r.pages;d.photoOcr=r.photoOcr;},...extra};}
test('202 recorded Doncic closes Green RC after the physical inspection, with no false number reread',async()=>{await reset('doncic',replay201Options(4,{surfaceInspection:fullSurface199()}));const out=await scan();assert.equal(out.identification.market_ready,true,JSON.stringify(out.visualAssistance.engine.events));assert.match(out.identification.title,/Green · RC$/);assert.ok(!stages().includes('flipcheck_evidence_detail'));assert.equal(stages().filter(s=>s==='flipcheck_catalogue_search').length,1);});
test('202 recorded Yamal closes Supernova Contra /9 with no redundant Vision or search',async()=>{await reset('doncic',replay201Options(5));const out=await scan();assert.equal(out.identification.market_ready,true,JSON.stringify(out.visualAssistance.engine.events));assert.match(await page.locator('#identTitle').innerText(),/Supernova.*Electric Etch Contra.*Seriale 8\/9/);assert.deepEqual(stages(),['flipcheck_identification','flipcheck_catalogue_search']);});
test('202 recorded Boniface preserves working serial closure and enriches the identity',async()=>{await reset('boniface',replay201Options(3,{details:D201[3].phases.find(p=>p.stage==='flipcheck_evidence_detail').result.details}));const out=await scan();assert.equal(out.identification.market_ready,true);assert.match(out.identification.title,/Terrace.*Green.*Seriale 2\/5/);});
test('202 Mewtwo prepares and caches four contextual views before web, removes duplicate rarity, exports failure',async()=>{await reset('politoed',replay201Options(1));const out=await scan();assert.equal(out.visualAssistance.pokemonPanels.panels.length,4);assert.equal(out.visualAssistance.pokemonPanels.state,'read');assert.ok(stages().indexOf('flipcheck_pokemon_identity_bands')<stages().indexOf('flipcheck_catalogue_search'));assert.match(out.visualAssistance.queries[0],/Mewtwo V.*135\/127.*SR/);assert.doesNotMatch(out.identification.title,/Rarity Symbol/);assert.ok(events.filter(e=>e.kind==='evidence'&&e.type==='crop').length>=4);assert.ok(out.visualAssistance.budget.spentOrReservedUsd<=.03);await page.evaluate(()=>exportDiagnostic197());await page.waitForTimeout(30);assert.ok(events.some(e=>e.kind==='diagnostic'));});
test('202 Glurak band reread uses full fraction and rejects the recorded attack number',async()=>{const region=D201[0].vision.object_regions[0];await reset('politoed',replay201Options(0,{bandObservations:[{field:'collector_number',text:'9/12',certainty:'clear',image_index:1,region:{...region,y:region.y+region.height*.7,height:region.height*.3}}],details:[{field:'collector_number',text:'50x',certainty:'clear',evidence_found:true,image_index:1}]}));const out=await scan();assert.equal(out.identification.physical_card_number,'9/12');assert.equal(out.identification.language,'de');assert.ok(out.visualAssistance.queries.every(q=>!q.includes('50X')));assert.equal(out.identification.market_ready,false,'new catalogue evidence was not supplied');});
test('202 uncertain One Piece code uses official variant image for core comparison before paid discovery',async()=>{const core={reference_id:'core0',match:true,ambiguous:false,reference_subject:'Monkey.D.Luffy',reference_number:'P-110',conflicts:[],features:[{field:'artwork',original:'Pose and buildings',reference:'Pose and buildings',agrees:true,certainty:'clear'},{field:'text',original:'4th Anniversary',reference:'4th Anniversary',agrees:true,certainty:'clear'}]};await reset('politoed',replay201Options(2,{coreComparisons:[core],comparisons:[artworkMatch('variant0')]}));const out=await scan();assert.equal(out.identification.market_ready,true,JSON.stringify(out.visualAssistance.engine.events));assert.ok(stages().includes('flipcheck_catalogue_comparison'));assert.ok(!stages().includes('flipcheck_catalogue_search'));assert.ok(native.some(n=>n.action==='image'&&n.url.includes('P-110.png')));assert.equal(out.identification.card_identity.rarity,'P');assert.equal(native.filter(n=>n.action==='image').length,2);});

const D203=JSON.parse(require('node:zlib').gunzipSync(fs.readFileSync(path.join(__dirname,'fixtures/diagnostics-203-pokemon.json.gz'))));
test('204: Mewtwo reuses the downloaded PriceCharting image in the complete production pipeline',async()=>{
 const row=D203[0];await reset('politoed',{packet:row.vision,noOcr:true,bandObservations:row.bands.observations,bandFeatures:row.bands.features,mutate(d){d.pages=row.pages;},coreComparisons:[{reference_id:'core0',reference_subject:'Mewtwo V',reference_number:'135',match:true,ambiguous:false,conflicts:[],features:[{field:'artwork',original:'same pose',reference:'same pose',agrees:true,certainty:'clear'},{field:'text',original:'same Chinese printing',reference:'same Chinese printing',agrees:true,certainty:'clear'}]}]});
 const out=await scan(),r=out.identification;assert.equal(r.market_ready,true,JSON.stringify(out.visualAssistance.engine));assert.equal(r.physical_card_number,'135/127');assert.equal(r.printed_year,'2024');assert.equal(r.language,'zh');assert.equal(r.family,'CS5aC');assert.equal(r.variant,'Holo');assert.deepEqual(stages(),['flipcheck_identification','flipcheck_pokemon_identity_bands','flipcheck_catalogue_search','flipcheck_catalogue_comparison']);assert.equal(native.filter(n=>n.action==='image'&&n.url?.includes('1600.jpg')).length,1);assert.equal(await page.locator('#marketBtn').isDisabled(),false);
});

// Build205 Lens transport and production fallback. All external IO remains intercepted.
for(const failure of ['timeout','empty_results','quota_exhausted'])test('205 Lens '+failure+' continues through OCR and targeted web',async()=>{
 await reset('politoed',{lens:true,lensReply:{state:failure,providerCalls:failure==='quota_exhausted'?0:1,accountCalls:1,estimatedUsd:.004,billingUnknown:failure==='timeout',candidates:[]},bandObservations:politoedKeys204});
 const out=await scan();assert.equal(out.identification.market_ready,true);assert.equal(out.identificationPipeline.state,failure);assert.equal(native.filter(x=>x.action==='lens').length,1);
 const trace=events.filter(x=>['native','api'].includes(x.kind)).map(x=>x.action||x.stage);assert.ok(trace.indexOf('lens')<trace.indexOf('ocr'));assert.ok(trace.indexOf('ocr')<trace.indexOf('flipcheck_identification'));assert.ok(trace.indexOf('flipcheck_catalogue_search')>trace.indexOf('lens'));
 assert.ok(out.identificationPipeline.fallbacks.some(x=>x.stage==='targeted_web'));assert.ok(out.visualAssistance.budget.spentOrReservedUsd<=.03);assert.ok(events.find(x=>x.kind==='end').snapshot.identificationPipeline);assert.doesNotMatch(JSON.stringify(out),/access-testing-123456/);
});
test('205 recorded Lens candidates cannot override incompatible physical Politoed number',async()=>{
 const recorded=JSON.parse(require('node:zlib').gunzipSync(fs.readFileSync(path.join(__dirname,'fixtures/lens-205-recorded.json.gz')))).glurak;
 const L=require('../src/main/assets/lens-policy');await reset('politoed',{lens:true,lensCandidates:L.normalize(recorded),bandObservations:politoedKeys204,tcgdex:true});const out=await scan();
 assert.equal(out.identification.market_ready,true);assert.equal(out.identificationPipeline.consideredCount,20);assert.ok(out.identificationPipeline.evaluations.some(c=>c.reasons.includes('different_number')));assert.equal(native.filter(x=>x.action==='lens').length,1);assert.equal(stages().filter(x=>x==='flipcheck_catalogue_search').length,0);
});
test('205 Lens reads every uploaded photo once and saves incomplete result and pending details',async()=>{
 await reset('topps',{lens:true,photoCount:3,lensReply:{state:'empty_results',providerCalls:1,estimatedUsd:.004,billingUnknown:false,candidates:[]}});const out=await scan();
 assert.equal(native.filter(x=>x.action==='lens').length,1);assert.equal(native.filter(x=>x.action==='ocr').length,3);assert.equal(out.identification.market_ready,false);assert.equal(out.identificationPipeline.finalClosure.exact,false);assert.ok(out.identificationPipeline.finalClosure.missing.length);assert.ok(events.some(x=>x.kind==='end'&&x.snapshot.identification));
});
test('205 Glurak closes through a recorded Lens source with no paid web fallback',async()=>{
 const f=JSON.parse(require('node:zlib').gunzipSync(fs.readFileSync(path.join(__dirname,'fixtures/glurak-204-lens-verification.json.gz'))));
 const recorded=JSON.parse(require('node:zlib').gunzipSync(fs.readFileSync(path.join(__dirname,'fixtures/lens-205-recorded.json.gz')))).glurak,L=require('../src/main/assets/lens-policy');
 await reset('politoed',{lens:true,lensCandidates:L.normalize(recorded),packet:f.vision,bandObservations:f.bands.observations,bandFeatures:f.bands.features,catalogueEntries:[f.entry],mutate(d){d.pages=f.pages;d.vision=f.vision;}});
 const out=await scan();assert.equal(out.identification.market_ready,true,JSON.stringify(out.identificationPipeline));assert.match(out.identification.title,/Glurak.*Box Topper/);assert.equal(out.identification.language,'de');assert.equal(out.identification.card_identity.number,'9/12');
 assert.equal(stages().filter(s=>s==='flipcheck_catalogue_search').length,0);assert.equal(native.filter(x=>x.action==='lens').length,1);assert.ok(out.identificationPipeline.evaluations.some(c=>c.reasons.includes('different_number')));assert.ok(out.identificationPipeline.catalogueExtraction.accepted>0);assert.equal(native.filter(x=>x.action==='catalogue').length,0);
});


test('206 image-first closes from downloaded images, keeps both originals and physical language, skips text/web',async()=>{
 const reading={subject:'Politoed',number:'H23/H32',year:'2003',language:'it'};
 const ref={id:'lens-1',title:'Politoed Skyridge 2003 H23/H32 Italian Holo',snippet:'',url:'https://example.com/politoed',image_url:'https://example.com/politoed.jpg'};
 const comparison={reference_id:'lens-1',match:true,ambiguous:false,title_matches_image:true,conflicts:[],original_reading:reading,reference_reading:reading,features:[{field:'artwork',original:'frog',reference:'frog',agrees:true,certainty:'clear'},{field:'identifier',original:'H23/H32',reference:'H23/H32',agrees:true,certainty:'clear'}],identity:{subject:'Politoed',family:'Skyridge',number:'H23/H32',year:'2003',brand:'Pokémon',subset:'',proof:{subject:'Politoed',family:'Skyridge',year:'2003',subset:''},display_names:{it:'Politoed',en:'Politoed'}}};
 const packet={domain:'pokemon',kind:'card',category:'Pokémon',language:'it',object_unit:'single',object_regions:[],slab_reading:null,hypotheses:[],observations:[['subject','Politoed'],['collector_number','H23/H32'],['copyright','©2003'],['language','it']].map(([field,text])=>({field,text,certainty:'clear',image_index:1,region:null,zone:'front',alternatives:[]})),features:[{field:'finish',value:'holo',description:'Holo visible on artwork',certainty:'clear',image_index:1,region:null,zone:'artwork'}]};
 await reset('politoed',{lens:true,photoCount:2,packet,lensCandidates:[ref],lensComparisons:[comparison],noOcr:true});const out=await scan();
 assert.equal(out.identification.market_ready,true,JSON.stringify(out));assert.match(out.identification.title,/Politoed.*H23\/H32.*ITA/);assert.equal(out.identification.language,'it');
 assert.deepEqual(stages(),['flipcheck_identification','flipcheck_lens_image_comparison']);assert.equal(native.filter(n=>['page','catalogue'].includes(n.action)).length,0);
 const body=api.find(b=>b.text.format.name==='flipcheck_lens_image_comparison');assert.equal(body.input[0].content.filter(c=>c.type==='input_image').length,3);assert.equal(body.tools,undefined);
 assert.equal(out.identificationPipeline.visualComparison.entries.length,1);assert.equal(out.identificationPipeline.visualComparison.references[0].ocr.origin,'candidate_image_ocr');
 assert.ok(out.visualAssistance.budget.spentOrReservedUsd<=.03);assert.ok(events.some(e=>e.kind==='end'));assert.doesNotMatch(JSON.stringify(out),/data:image|offline-secret|access-testing/);
});

test('207 startup retry reaches one Lens search and preserves scan credit budget',async()=>{
 await reset('politoed',{lens:true,tcgdex:true,bandObservations:politoedKeys204,lensConfigReplies:[{status:503},{status:200,body:{enabled:true,protocol:2,provider:'searchapi_google_lens',unitUsd:.004}}]});
 const out=await scan();assert.equal(out.identification.market_ready,true);assert.equal(native.filter(n=>n.action==='lens_config').length,2);assert.equal(native.filter(n=>n.action==='lens').length,1);assert.equal(out.identificationPipeline.warmup.state,'ready');assert.equal(out.identificationPipeline.warmup.attempts,2);assert.ok(out.identificationPipeline.warmup.elapsedMs>=5000);assert.equal(out.visualAssistance.budget.entries.filter(e=>e.kind==='lens').length,1);assert.equal(out.visualAssistance.budget.maxUsd,.03);
});
test('207 invalid app access stops immediately with no image upload or Lens charge',async()=>{
 await reset('politoed',{lens:true,tcgdex:true,bandObservations:politoedKeys204,lensConfigReplies:[{status:401,body:{state:'unauthorized'}}]});const out=await scan();
 assert.equal(native.filter(n=>n.action==='lens_config').length,1);assert.equal(native.filter(n=>n.action==='lens').length,0);assert.equal(out.identificationPipeline.warmup.state,'unauthorized');assert.equal(out.visualAssistance.budget.entries.filter(e=>e.kind==='lens').length,0);assert.equal(out.identification.market_ready,true);
});
