const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),zlib=require('zlib'),path=require('path');
const E=require('../src/main/assets/catalogue-engine'),C=require('../src/main/assets/catalogue-sources');
const D=JSON.parse(zlib.gunzipSync(fs.readFileSync(path.join(__dirname,'fixtures/diagnostics-200.json.gz'))));
function replay(i){const d=D[i],l=E.ingestVision(new E.Ledger(d.vision),d.vision);E.ingestOcr(l,d.photoOcr);const entries=[...C.records(d.pages,l),...d.phases.filter(p=>p.stage==='flipcheck_catalogue_search').flatMap(p=>C.groundedExtraction(p.result,d.pages,l).accepted)];return {d,l,entries};}
function applyRecorded(d,l,entries){for(const p of d.phases){if(p.stage==='flipcheck_evidence_detail')E.applyDetails(l,p.result.details,E.recoveryRequests(l,E.reduce(l,entries)));if(p.stage==='flipcheck_surface_inspection')E.applySurfaceInspection199(l,p.result,[1,2]);}return E.reduce(l,entries);}
test('200 real CD Promo cannot resolve as Expedition even after the recorded Holo verification',()=>{const {d,l,entries}=replay(9),r=applyRecorded(d,l,entries);assert.equal(r.market_ready,false);assert.equal(r.catalogue_core_verified,false);assert.equal(l.pick('collector_number'),null);assert.equal(l.pick('pokedex_number').value,'006');assert.deepEqual(E.keyValues(l).numbers,[]);assert.match(E.query(l),/"006".*Japanese/);assert.match(E.query(l),/Ken Sugimori/);assert.equal(E.recoveryRequests(l,r).some(r=>r.field==='collector_number'),false);assert.ok(l.candidates.every(e=>!e.eligible));assert.ok(l.candidates.some(e=>e.reasons.includes('different_illustrator')));assert.ok(l.values('collector_number').length>0,'raw misclassification retained as superseded evidence');});
test('200 real Glurak registry and duplicate representations close one Box Topper #9/12 after the recorded reread',()=>{const {d,l,entries}=replay(6);for(const es of [entries,[...entries].reverse(),[...entries,...entries]]){const r=applyRecorded(d,l,es);assert.equal(r.market_ready,true);assert.match(r.title,/2003.*SKYRIDGE BOX TOPPER.*9\/12.*Holo.*DE/i);assert.equal(r.physical_card_number,'9/12');assert.equal(r.source_confirmed_catalog_number,'9');assert.equal(r.physical_serial,null);assert.equal(E.candidateGroups(l,es).length,1);assert.ok(!es.some(e=>e.family==='Registry'));}});
test('200 real Doncic remains automatically Green RC with atomic final state',()=>{const {d,l,entries}=replay(1),r=applyRecorded(d,l,entries);assert.equal(r.market_ready,true);assert.match(r.title,/2018-19.*280.*Green · RC$/);assert.equal(r.closure_status,'resolved');assert.equal(r.job_status,'variant_resolved');assert.deepEqual(r.variant_resolution.pending,[]);assert.equal(r.next_photo_request,null);assert.equal(r.card_identity.is_rookie,true);});
test('200 real Curry OFF 90 and game activation code cannot contaminate the query or request a serial crop',()=>{const {l,entries}=replay(2),r=E.reduce(l,entries);assert.deepEqual(E.keyValues(l).numbers,['77']);assert.deepEqual(E.keyValues(l).serials,[]);assert.equal(l.active('serial').length,0);assert.ok(l.values('activation_code').some(a=>a.value==='XPJP CMJC NCKM'));assert.ok(l.values('statistics_number').some(a=>a.value==='90'));assert.doesNotMatch(E.query(l),/"90"|XPJP/);assert.equal(E.recoveryRequests(l,r).some(r=>r.field==='serial'),false);assert.equal(r.market_ready,false,'other athletes in the recorded catalogue cannot close Curry');assert.match(E.query(l,'recovery'),/international European edition/);});
test('200 real Boniface serial crop excludes biography and retains vertical orientation',()=>{const {l,entries}=replay(0),r=E.reduce(l,entries),req=E.recoveryRequests(l,r).find(r=>r.field==='serial');assert.ok(req);assert.equal(req.rotation,90);assert.ok(req.region.width<.08);assert.ok(req.region.height>.08);assert.ok(req.readings.every(x=>!x.value.includes('Nigeria')));assert.equal(r.market_ready,false);E.applyDetails(l,[{field:'serial',text:'2/5',certainty:'clear',evidence_found:true,image_index:2}],[req]);assert.equal(l.pick('serial').value,'2/5');assert.deepEqual(E.keyValues(l).serials,['2/5']);assert.match(E.reduce(l,entries).title,/Seriale 2\/5/);});
test('malformed Markdown URL retains exact provenance while permitting the existing public source',()=>{const url='https://www.beckett.com/test/',l=new E.Ledger({domain:'sports'});const raw=url+' ([beckett.com]('+url+'?utm_source=openai))',entry={subject:'Example',family:'Select',number:'21',year:'2025',source_url:raw,entry_quote:'2025 Select #21 Example',proof:{subject:'Example',family:'Select',number:'21',year:'2025'},variants:[]},v=C.groundedExtraction({entries:[entry]},[{url,text:entry.entry_quote,title:'2025 Select'}],l);assert.equal(v.accepted.length,1);assert.equal(v.accepted[0].reported_source_url,raw);assert.equal(v.accepted[0].source.url,url);assert.equal(E.sourceUrl201('javascript:alert(1)'), '');});
test('200 Chinese searches preserve denominator and year without using an Asian name in an English API',()=>{for(const i of [7,8]){const {l}=replay(i),q=E.query(l);assert.match(q,/"135\/127" 2024/);assert.match(q,/Chinese/);assert.doesNotMatch(q,/site:/);assert.equal(E.keyValues(l).language,'zh');assert.deepEqual(C.requestPlan(l),[]);}assert.equal(E.language('Simplified Chinese'),'zh-hans');assert.equal(E.language('Traditional Chinese'),'zh-hant');assert.equal(E.printingLanguageCompatible201('zh-hans','zh-hant'),false);});
test('Chinese translated candidate requires catalogue image corroboration before closure',()=>{const {l}=replay(8),e={subject:'Mewtwo V',family:'Brave Stars (Charm)',number:'135/127',year:'2024',language:'zh-hans',variants:[{name:'Holo',finish:'holo'}],grounded:true,source:{url:'https://www.tcgcollector.com/cards/test'}};let r=E.reduce(l,[e]);assert.equal(r.market_ready,false);assert.equal(r.core_identity.status,'partial');l.add('catalogue_core',E.coreKey(e),{certainty:'clear',image_index:1,source:'catalogue_image_comparison'});r=E.reduce(l,[e]);assert.equal(r.market_ready,true);assert.equal(r.source_confirmed_catalog_number,'135/127');assert.equal(E.reduce(l,[{...e,language:'ja'}]).market_ready,false);});
test('Pokédex promotional registry entry cannot close on species and year alone; image evidence resolves it',()=>{const {l}=replay(9),e={subject:'Charizard',family:'Japanese CD Promo',number:'6',identifier_type:'pokedex',language:'ja',year:'1999',variants:[{name:'Holo',finish:'holo'}],grounded:true,source:{url:'https://www.psacard.com/cert/example/psa'}};assert.equal(E.reduce(l,[e]).market_ready,false);l.add('catalogue_core',E.coreKey(e),{certainty:'clear',image_index:1,source:'catalogue_image_comparison'});const r=E.reduce(l,[e]);assert.equal(r.market_ready,true);assert.equal(r.pokedex_number,'006');assert.equal(r.physical_card_number,null);assert.match(r.title,/CD Promo.*No\.6/);});
test('explicit illustrator and same-language attack contradictions veto an otherwise matching number',()=>{const l=E.ingestVision(new E.Ledger({domain:'pokemon'}),{language:'ja',observations:[{field:'subject',text:'Example',certainty:'clear',image_index:1},{field:'collector_number',text:'5/99',certainty:'clear',image_index:1},{field:'illustrator',text:'Artist A',certainty:'clear',image_index:1},{field:'attack',text:'Attack A',certainty:'clear',image_index:1}]});const e={subject:'Example',family:'Set',number:'5/99',language:'ja',illustrator:'Artist B',attacks:['Attack B'],attacks_language:'ja',grounded:true,source:{url:'https://www.pokemon.com/test'}};const r=E.evaluate(l,e);assert.ok(r.reasons.includes('different_illustrator'));assert.ok(r.reasons.includes('different_attacks'));assert.equal(E.reduce(l,[e]).market_ready,false);});
test('Topps aliases preserve product type and parse quantities only from literal configuration sections',()=>{const {l,entries}=replay(3),r=E.reduce(l,entries);assert.equal(r.core_identity.status,'confirmed');assert.equal(r.catalogue_core_verified,true);const sections=entries.filter(e=>e.configuration_section);assert.ok(sections.some(e=>/Hobby Box/.test(e.subject)&&/guarantees one autograph/.test(e.configuration_quote)));assert.notEqual(E.productText201('Topps Chrome Update Series'),E.productText201('Topps Chrome Black'));assert.equal(entries.filter(e=>e.configuration_quote?.includes('Hobby Box —')).length,0,'model-generated summaries are not evidence');});
test('registry navigation alone cannot create a card set',()=>{const {l}=replay(6),r=C.records([{url:'https://www.psacard.com/cert/123/psa',text:'Subject\nGLURAK\nCard Number\n9\nSet Registry\nNo sets.'}],l);assert.equal(r.length,0);});
test('Pokémon API preserves a legitimate numbered prefix, never routes it as Pokédex',()=>{const {l}=replay(5);assert.deepEqual(E.keyValues(l).numbers,['H23/H32']);assert.equal(l.evidence('pokedex_number').length,0);assert.match(E.query(l),/"H23\/H32"/);});
