const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),zlib=require('zlib'),path=require('path');
const E=require('../src/main/assets/catalogue-engine'),C=require('../src/main/assets/catalogue-sources');
const D=JSON.parse(zlib.gunzipSync(fs.readFileSync(path.join(__dirname,'fixtures/diagnostics-199.json.gz'))));
function replay(i){const d=D[i],l=E.ingestVision(new E.Ledger(d.vision),d.vision);l.userDetails=d.userDetails;E.ingestOcr(l,d.photoOcr);return {d,l,entries:C.records(d.pages,l)};}
const absence={surfaces:[{image_index:1,side:'front',fully_visible:true,legible:true},{image_index:2,side:'back',fully_visible:true,legible:true}],serial_presence:'absent',serial:{text:'',certainty:'uncertain',evidence_found:false,image_index:1}};
test('199 real Boniface detail closes with full specimen serial in identity, without inventing RC',()=>{const {d,l,entries}=replay(0);const req=E.recoveryRequests(l,E.reduce(l,entries));E.applyDetails(l,d.phases.find(p=>p.stage==='flipcheck_evidence_detail').result.details,req);const r=E.reduce(l,entries);assert.equal(r.market_ready,true);assert.match(r.title,/Green.*Seriale 2\/5/);assert.equal(r.model,r.identity_display);assert.equal(r.card_identity.is_rookie,null);assert.doesNotMatch(r.title,/\bRC\b/);assert.equal(r.core_identity.model.includes('Seriale'),false);});
test('199 real declared Doncic is Green RC, photograph and declaration remain separate',()=>{const {l,entries}=replay(2),r=E.reduce(l,entries);assert.equal(r.market_ready,true);assert.match(r.title,/Green · RC$/);assert.equal(r.card_identity.is_rookie,true);assert.equal(r.variant_resolution.variant_origin,'user_declaration');});
test('199 real contradictory surface reply does not falsely close automatic Doncic',()=>{const {d,l,entries}=replay(1);E.applySurfaceInspection199(l,d.phases.find(p=>p.stage==='flipcheck_surface_inspection').result,[1,2]);assert.equal(E.reduce(l,entries).market_ready,false);assert.equal(l.pick('serial_presence'),null);E.applySurfaceInspection199(l,absence,[1,2]);assert.equal(E.reduce(l,entries).market_ready,true);});
test('199 initial Kobe full checklist contains Base and PMG without a second web search or team insert pollution',()=>{const {d,l}=replay(4),entries=C.records(d.pages.slice(0,17),l);let r=E.reduce(l,entries);const req=E.recoveryRequests(l,r);E.applyDetails(l,d.phases.find(p=>p.stage==='flipcheck_evidence_detail').result.details,req);r=E.reduce(l,entries);assert.equal(r.core_identity.status,'confirmed');assert.deepEqual(r.variant_resolution.variant_candidates.map(v=>v.name).sort(),['Base','Precious Metal Gems']);assert.equal(r.variant_resolution.needs_catalogue,false);assert.equal(r.market_ready,false);E.applySurfaceInspection199(l,absence,[1,2]);r=E.reduce(l,entries);assert.equal(r.market_ready,true);assert.match(r.title,/#81.*Base/);assert.equal(r.card_identity.is_rookie,null);});
test('TCG set_code aliases retain original region and enter the very first query',()=>{const {l}=replay(3);assert.deepEqual(E.keyValues(l).numbers,['P-010']);assert.match(E.query(l),/"P-010"/);const a=l.pick('collector_number');assert.equal(a.reported_field,'set_code');assert.ok(a.region);assert.ok(C.requestPlan(l)[0].url.includes('P-010'));});
test('new TCG crop may correct that original code, without substituting the web candidate',()=>{const {l}=replay(3),a=l.pick('collector_number'),req={key:'preflight',field:'collector_number',image_index:1,region:a.region,reason:'code_preflight'};E.applyDetails(l,[{field:'collector_number',text:'P-110',certainty:'uncertain',evidence_found:false,image_index:1}],[req]);assert.equal(l.pick('collector_number').value,'P-010');E.applyDetails(l,[{field:'collector_number',text:'P-110',certainty:'clear',evidence_found:true,image_index:1}],[req]);assert.deepEqual(E.keyValues(l).numbers,['P-110']);assert.ok(C.requestPlan(l)[0].url.includes('P-110'));});
test('empty HTTP 200 marketplace shell is not usable catalogue evidence',()=>{assert.equal(C.usablePage200({url:'https://www.tcgplayer.com/product/123/test',text:'Your Trusted Marketplace for Collectible Trading Card Games - TCGplayer'}),false);});
test('RC catalogue suffix identifies same subject without matching another player or treating season as RC',()=>{const l=E.ingestVision(new E.Ledger({domain:'sports'}),{observations:[{field:'subject',text:'Example Player',certainty:'clear',image_index:1},{field:'collector_number',text:'23',certainty:'clear',image_index:1},{field:'season',text:'2030',certainty:'clear',image_index:1}]});const entries=C.records([{url:'https://www.beckett.com/test',title:'2030 Example Basketball Checklist',text:'Base\n23 Example Player RC\n24 Someone Else RC'}],l),r=E.reduce(l,entries);assert.equal(r.core_identity.status,'confirmed');assert.equal(r.card_identity.is_rookie,true);assert.equal(r.card_identity.rookie_origin,'catalogue');});
function pokemon(symbol){const l=E.ingestVision(new E.Ledger({domain:'pokemon'}),{language:'ja',observations:[{field:'subject',text:'Example',certainty:'clear',image_index:1},{field:'collector_number',text:'1',certainty:'clear',image_index:1}],features:symbol?[{field:'rarity_symbol',value:symbol,certainty:'clear',image_index:1}]:[]});const e={subject:'Example',number:'1',family:'Expansion Pack',year:'1996',language:'ja',rarity:'Rare',variants:[{name:'Holo',finish:'holo'}],source:{url:'https://www.pokemon.com/test'},grounded:true};return E.reduce(l,[e]);}
test('Pokemon Rare and no rarity symbol are independent attributes in the identity',()=>{const r=pokemon('absent');assert.match(r.title,/Rare/);assert.match(r.title,/No Rarity Symbol/);assert.equal(r.card_identity.has_rarity_symbol,false);assert.equal(r.market_ready,true);const u=pokemon();assert.equal(u.card_identity.has_rarity_symbol,null);assert.doesNotMatch(u.title,/No Rarity Symbol/);assert.equal(u.market_ready,false);});
test('Pokemon observed rarity symbol is displayed explicitly without declaring it absent',()=>{const r=pokemon('present');assert.equal(r.card_identity.has_rarity_symbol,true);assert.match(r.title,/Rarity Symbol/);assert.doesNotMatch(r.title,/No Rarity Symbol/);});
test('standard TCG remains on the card route, preserves full print code and allows official catalogue',()=>{const base={domain:'generic',kind:'card',category:'Yu-Gi-Oh!',observations:[{field:'subject',text:'Example',certainty:'clear',image_index:1},{field:'set_code',text:'LOB-EN001',certainty:'clear',image_index:1}]},l=E.ingestVision(new E.Ledger(base),base);assert.equal(l.domain,'tcg');assert.deepEqual(E.keyValues(l).numbers,['LOB-EN001']);assert.equal(E.sourceTrusted('https://www.db.yugioh-card.com/yugiohdb/card_search.action','tcg'),true);const r=E.reduce(l,[{subject:'Example',number:'LOB-EN001',family:'Legend',grounded:true,source:{url:'https://www.db.yugioh-card.com/test'},variants:[]}]);assert.equal(r.kind,'card');assert.equal(r.core_identity.status,'confirmed');assert.equal(r.market_ready,false);});
