/* Pure decision tests. Real 192 observations are replayed; no new image recognition is simulated. */
const {test}=require('node:test'),assert=require('node:assert/strict');
const E=require('../src/main/assets/catalogue-engine'),C=require('../src/main/assets/catalogue-sources'),D=JSON.parse(require('node:zlib').gunzipSync(require('node:fs').readFileSync(require('node:path').join(__dirname,'fixtures/diagnostics-192.json.gz'))));
const copy=structuredClone;
function replay(name){const d=copy(D[name]),l=E.ingestVision(new E.Ledger(d.vision),d.vision);E.ingestOcr(l,d.photoOcr);return {d,l,entries:C.records(d.pages,l)};}
function observed(fields,domain='pokemon'){const l=new E.Ledger({domain,kind:'card'});for(const [field,value] of Object.entries(fields))l.add(field,value,{certainty:'clear',image_index:1});return l;}
const entry=(overrides={})=>({subject:'Example',number:'H23/H32',family:'Skyridge',language:'en',year:'2003',grounded:true,source:{url:'https://api.tcgdex.net/v2/en/cards/ecard3-H23'},variants:[{name:'Holo',finish:'holo'}],...overrides});
test('recorded Politoed resolves Skyridge H23 without a mandatory year or denominator reread',()=>{const {l,entries}=replay('politoed'),r=E.reduce(l,entries);assert.equal(r.core_identity.status,'confirmed');assert.equal(r.family,'Skyridge');assert.equal(r.market_ready,true);assert.equal(r.card_identity.number,'H23/H32');assert.equal(r.printing_check.shadow,'not_applicable');assert.equal(r.printing_check.stamp,'not_applicable');assert.deepEqual(E.recoveryRequests(l,r),[]);assert.equal(l.base.family,'Aquapolis');assert.ok(!r.candidate_models.some(c=>/Pokédex/.test(c.model)));});
test('different printings on one wiki page never become aliases',()=>{const {l,entries}=replay('politoed');assert.ok(entries.some(e=>e.number==='25/144'));assert.ok(entries.some(e=>e.number==='H23/H32'));assert.ok(E.candidateGroups(l,entries).find(g=>g.entry.number==='H23/H32').score>E.candidateGroups(l,entries).find(g=>g.entry.number==='25/144').score);});
test('recorded Boniface serial alternatives survive with original-image coordinates and rotation',()=>{const {l,entries}=replay('boniface'),r=E.reduce(l,entries),req=E.recoveryRequests(l,r).find(r=>r.field==='serial');assert.equal(l.pick('serial'),null);assert.equal(req.rotation,90);assert.equal(req.image_index,2);assert.ok(req.region.x>.7&&req.region.x<.85);assert.ok(req.readings.some(r=>r.value==='2/5'));assert.equal(r.market_ready,false);assert.equal(r.core_identity.status,'confirmed');});
test('a verified serial closes documented Green /5 and retains the specimen numerator',()=>{const {l,entries}=replay('boniface'),r=E.reduce(l,entries);E.applyDetails(l,[{field:'serial',text:'2/5',certainty:'clear',image_index:2}],E.recoveryRequests(l,r));const out=E.reduce(l,entries);assert.equal(out.variant,'Green');assert.equal(out.market_ready,true);assert.equal(out.physical_serial.specimen,2);assert.equal(out.physical_serial.print_run,5);});
test('a dubious serial is never autocorrected to fit the checklist',()=>{const {l,entries}=replay('boniface'),req=E.recoveryRequests(l,E.reduce(l,entries));E.applyDetails(l,[{field:'serial',text:'215',certainty:'clear',image_index:2}],req);assert.equal(E.reduce(l,entries).market_ready,false);E.applyDetails(l,[{field:'serial',text:'2/5',certainty:'uncertain',image_index:2}],req);assert.equal(l.pick('serial'),null);});
test('recorded Doncic retains core and green; statistics 42 and wrong Blue Ice are excluded',()=>{const {l,entries}=replay('doncic'),r=E.reduce(l,entries);assert.equal(r.core_identity.status,'confirmed');assert.equal(r.family,'Prizm');assert.equal(r.card_identity.number,'280');assert.deepEqual(E.keyValues(l).serials,[]);assert.match(E.query(l),/green/);assert.doesNotMatch(E.query(l),/\b42\b/);assert.ok(!r.variant_resolution.variant_candidates.some(v=>/Blue Ice/.test(v.name)));assert.equal(r.market_ready,false);});
test('recorded box keeps the product and never forces Hobby or requests a card number',()=>{const {l,entries}=replay('topps'),r=E.reduce(l,entries);assert.equal(r.core_identity.status,'confirmed');assert.equal(r.market_ready,false);assert.match(r.title,/Chrome.*UPDATE SERIES/i);assert.doesNotMatch(r.variant,/Hobby|Jumbo/);assert.match(r.next_photo_request,/confezione/);assert.deepEqual(E.recoveryRequests(l,r),[]);assert.doesNotMatch(E.query(l),/FLAGG|WEMBANYAMA/);});
test('recorded Magikarp closes only after scoped local shadow evidence; observations stay immutable',()=>{const {d,l,entries}=replay('magikarp'),r=E.reduce(l,entries);assert.equal(r.core_identity.status,'confirmed');assert.deepEqual(r.variant_resolution.pending,['shadow']);const count=l.atoms.length;l.add('shadow','absent',{source:'local_frame_measurement',certainty:'clear',image_index:1,raw:JSON.stringify(d.localPrinting)});const out=E.reduce(l,entries);assert.equal(out.market_ready,true);assert.match(out.variant,/1st Edition.*Shadowless.*Non holo/);assert.equal(l.atoms.length,count+1);assert.equal(l.base.pokemon_printing.artwork_shadow,'unclear');});
test('same prefix/year with a different subject is rejected; number alone never identifies',()=>{let l=observed({subject:'Example',collector_number:'H23',language:'en'});const r=E.reduce(l,[entry(),entry({subject:'Another',family:'Aquapolis'})]);assert.equal(r.family,'Skyridge');l=observed({collector_number:'H23',language:'en'});assert.equal(E.reduce(l,[entry()]).core_identity.status,'partial');});
test('copyright is not a release-year veto, printed season is',()=>{let l=observed({subject:'Example',collector_number:'H23',copyright:'© 2002',language:'en'});assert.equal(E.reduce(l,[entry()]).core_identity.status,'confirmed');l.add('season','2002',{certainty:'clear',image_index:1});assert.equal(E.reduce(l,[entry()]).core_identity.status,'partial');});
test('full numbers conflict but local numbers and leading zeros can corroborate',()=>{const l=observed({collector_number:'006'});l.add('collector_number','6',{certainty:'clear',image_index:2});assert.ok(l.pick('collector_number'));assert.equal(E.numbersMatch('H23','H23/H32'),true);assert.equal(E.numbersMatch('25/144','25/165'),false);assert.equal(E.numbersMatch('OP01-001','OP02-001'),false);l.add('collector_number','7',{certainty:'clear',image_index:2});assert.equal(l.pick('collector_number'),null);});
test('candidate order and duplicate sources do not alter the decision',()=>{const {l,entries}=replay('politoed'),a=E.reduce(l,entries),b=E.reduce(l,[...entries,...entries].reverse());assert.equal(a.model,b.model);assert.equal(a.market_ready,b.market_ready);});
test('set and language scope shadow, first edition and no rarity separately',()=>{let l=observed({language:'en'});assert.equal(E.printingScope(l,entry({family:'Neo Destiny',year:'2002'})).firstEdition,true);assert.equal(E.printingScope(l,entry({family:'Skyridge'})).shadow,false);l=observed({language:'ja'});const scope=E.printingScope(l,entry({family:'Expansion Pack',language:'ja',year:'1996'}));assert.equal(scope.noRarity,true);assert.equal(scope.shadow,false);});
test('unreadable rarity symbol is not absence; English set-symbol absence is unrelated',()=>{const l=observed({subject:'Example',collector_number:'1',language:'ja',finish:'normal',set_symbol:'absent'}),e=entry({number:'1',family:'Expansion Pack',language:'ja',year:'1996',variants:[{name:'Non holo',finish:'normal'}]});let r=E.reduce(l,[e]);assert.ok(r.variant_resolution.pending.includes('rarity_symbol'));l.add('rarity_symbol','absent',{certainty:'clear',image_index:1});r=E.reduce(l,[e]);assert.match(r.variant,/No Rarity Symbol/);});
test('geometry is independent of color and cannot be invented from a serial',()=>{const l=observed({subject:'Example',collector_number:'21',serial:'2/5',border_color:'green'},'sports'),e=entry({number:'21',variants:[{name:'Green',colors:['green'],print_run:5},{name:'Green Ice',colors:['green'],patterns:['ice'],print_run:5}]});let r=E.reduce(l,[e]);assert.equal(r.market_ready,false);assert.equal(r.variant_resolution.variant_candidates.length,2);l.add('pattern','geometric',{certainty:'clear',image_index:1});r=E.reduce(l,[e]);assert.equal(r.market_ready,false);});
test('structured catalogue lookup uses name before the uncertain set hypothesis',()=>{const {l}=replay('politoed'),p=C.requestPlan(l)[0];assert.match(p.url,/\/it\/cards\?/);assert.match(p.url,/name=Politoed/);assert.doesNotMatch(p.url,/Aquapolis/);assert.doesNotMatch(E.query(l),/Aquapolis/);});
test('TCGdex keeps finish and rarity separate and does not invent a release date',()=>{const c=C.tcgdexCard({id:'set-7',name:'Example',localId:'7',set:{id:'set',name:'Example Set',cardCount:{official:100}},rarity:'Rare',variants:{normal:true,reverse:true}},null,'en','https://api.tcgdex.net/test');assert.equal(c.year,'');assert.equal(c.number,'7/100');assert.equal(c.rarity,'Rare');assert.deepEqual(c.variants.map(v=>v.finish),['normal','reverse']);});
test('structured table column mapping cannot use another player or serial as card number',()=>{const l=observed({subject:'Example',collector_number:'21'},'sports');const p={url:'https://www.paniniamerica.net/checklist',title:'2025-26 Select',catalogue_rows:[{headers:['Card Number','Player','Set','Year','Subset'],cells:['21','Example','Select','2025-26','Base'],text:'21 Example Select 2025-26 Base'},{headers:['Serial','Player'],cells:['2/5','Example']} ]};assert.equal(C.records([p],l).length,1);assert.equal(C.records([p],l)[0].number,'21');});
test('model extraction must be grounded in a retrieved page, not its own response',()=>{const l=observed({subject:'Example',collector_number:'7'}),reply={entries:[{subject:'Example',family:'Example Set',number:'7',source_url:'https://www.beckett.com/test',entry_quote:'7 Example',proof:{subject:'Example',family:'Example Set',number:'7'},variants:[]}]};assert.equal(C.groundedExtraction(reply,[],l).accepted.length,0);assert.equal(C.groundedExtraction(reply,[{url:reply.entries[0].source_url,text:'Different entry'}],l).accepted.length,0);assert.equal(C.groundedExtraction(reply,[{url:reply.entries[0].source_url,text:'Short snippet'},{url:reply.entries[0].source_url,text:'Example Set\n7 Example'}],l).accepted.length,1);});
test('an explicitly superseded measurement is retained but no longer votes twice',()=>{const l=observed({shadow:'present'}),old=l.atoms[0];l.add('shadow','absent',{source:'local_frame_measurement',certainty:'clear',image_index:1,supersedes:[old.id]});assert.equal(l.pick('shadow').value,'absent');assert.equal(l.atoms[0].value,'present');assert.ok(Object.isFrozen(old));});
test('service failure preserves confirmed card fields and asks only the variant detail',()=>{const {l,entries}=replay('doncic'),r=E.reduce(l,entries,{error:'service_unavailable'});assert.equal(r.core_identity.status,'confirmed');assert.match(r.model,/280/);assert.deepEqual(r.variant_resolution.pending,['variant']);assert.equal(r.assistance_state,'service_unavailable');});
test('generic product model uses public specifications, not sports-only sites',()=>{const l=observed({brand:'Acme',model_code:'ZX-430'},'generic'),p={url:'https://acme.example/manual',title:'Acme ZX-430',text:'Acme ZX-430 water pump technical specifications'};assert.doesNotMatch(E.query(l),/beckett|panini/);const r=E.reduce(l,C.records([p],l));assert.equal(r.market_ready,true);assert.match(r.model,/ZX-430/);});

test('Bandai card list preserves code and rarity without inferring an artwork variant',()=>{const l=observed({subject:'Roronoa Zoro',collector_number:'OP01-001',language:'en'},'onepiece'),page={url:'https://en.onepiece-cardgame.com/cardlist/?series=569101',text:'OP01-001 | L | LEADER\nRoronoa Zoro\nLife\n5\nCard Set(s)\n-ROMANCE DAWN- [OP01]\nCARD VIEW'};const r=E.reduce(l,C.records([page],l));assert.equal(r.core_identity.status,'confirmed');assert.equal(r.card_identity.rarity,'L');assert.equal(r.market_ready,false);assert.match(C.requestPlan(l)[0].url,/freewords=Roronoa/);});

test('an observed autograph cannot silently close an ordinary parallel',()=>{const l=observed({subject:'Example',collector_number:'21',border_color:'green',autograph:'present'},'sports'),r=E.reduce(l,[entry({number:'21',variants:[{name:'Green',colors:['green']} ]})]);assert.equal(r.market_ready,false);assert.ok(r.variant_resolution.pending.includes('autograph'));assert.match(E.query(l),/autograph/);assert.equal(r.card_identity.autograph,'present');});

test('Italian Base Set does not lose First Edition just because its language differs',()=>{const l=observed({language:'it'});assert.equal(E.printingScope(l,entry({family:'Set Base',language:'it',year:'1999'})).firstEdition,true);assert.equal(E.printingScope(l,entry({family:'Set Base',language:'it',year:'1999'})).shadow,false);});
test('a malformed initial serial can be resolved by a clear crop instead of blocking it',()=>{const l=observed({serial:'215'},'sports');assert.equal(l.pick('serial'),null);E.applyDetails(l,[{field:'serial',text:'2/5',certainty:'clear',image_index:1}],[{field:'serial',image_index:1,key:'detail:serial',region:null}]);assert.equal(l.pick('serial').value,'2/5');});
