/* Production build-193 UI + HTTP/native boundary. Synthetic pixels carry recorded
   observations; these tests verify decisions and calls, not fresh model accuracy. */
const {test,before,after,afterEach}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),{chromium}=require('playwright');
const D=JSON.parse(require('node:zlib').gunzipSync(require('node:fs').readFileSync(require('node:path').join(__dirname,'fixtures/diagnostics-192.json.gz')))),E=require('../src/main/assets/catalogue-engine');
const root=path.join(__dirname,'../src/main/assets'),nativeSource=fs.readFileSync(path.join(__dirname,'../src/main/java/com/flipcheck/legacy26/ScanSession.java'),'utf8'),allow=new RegExp('^'+JSON.parse(nativeSource.match(/path\.matches\(("(?:[^"\\]|\\.)*")\)/)[1])+'$');
let server,browser,page,origin,d,options,api=[],native=[],errors=[],events=[],ocrIndex=0,release,carrier;
const stages=()=>api.map(b=>b.text.format.name);
const envelope=(payload,web=[])=>({status:'completed',output:[...(web.length?[{type:'web_search_call',status:'completed',action:{type:'search',sources:web},results:web}]:[]),{type:'message',content:[{type:'output_text',text:JSON.stringify(payload)}]}],usage:{input_tokens:350,output_tokens:150}});
async function reset(name,opts={}){
 d=structuredClone(D[name]);options=opts;opts.mutate?.(d);api=[];native=[];errors=[];events=[];ocrIndex=0;release=null;
 await page.goto(origin);await page.waitForFunction(()=>typeof resolveCatalogue193==='function');
 await page.evaluate(()=>{trial={attempts:2,free:true,credits:0};saveTrial();$('apiKey').value='offline-secret-never-export';$('googleApiKey').value='';$('scanBudget').value='.03';window.FlipCheckTestMode='offline-catalogue-engine';});
 const count=opts.photoCount||Math.max(1,...d.vision.photo_clues?.map(c=>c.image_index)||[]);
 const images=await page.evaluate(count=>Array.from({length:count},(_,i)=>{const c=document.createElement('canvas');c.width=900;c.height=1200;const g=c.getContext('2d');g.fillStyle=i?'#bbc':'#ccb';g.fillRect(0,0,900,1200);g.fillStyle='#000';g.font='35px sans-serif';g.fillText('SYNTHETIC CARRIER '+i,20,40);return c.toDataURL('image/png');}),count);carrier=images[0];
 await page.locator('#photoBatch').setInputFiles(images.map((s,i)=>({name:'carrier-'+i+'.png',mimeType:'image/png',buffer:Buffer.from(s.split(',')[1],'base64')})));await page.waitForFunction(()=>!photoBusy);
}
async function scan(){await page.locator('#identifyBtn').click();await page.waitForFunction(()=>!apiBusy,{}, {timeout:25000});return page.evaluate(()=>diagnostic26());}
before(async()=>{
 server=http.createServer((req,res)=>{const name=req.url==='/'?'index.html':req.url.slice(1);if(!allow.test('/'+name)||!fs.existsSync(path.join(root,name))){res.writeHead(404);return res.end();}res.setHeader('Content-Type',name.endsWith('.js')?'application/javascript':'text/html');res.end(fs.readFileSync(path.join(root,name)));});await new Promise(r=>server.listen(0,'127.0.0.1',r));origin='http://127.0.0.1:'+server.address().port;
 browser=await chromium.launch({executablePath:process.env.FLIPCHECK_BROWSER_EXECUTABLE||undefined,headless:true,args:['--no-sandbox']});page=await browser.newPage({viewport:{width:412,height:915},serviceWorkers:'block'});
 page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.dismiss());await page.exposeFunction('hostEvent',e=>events.push(e));
 await page.addInitScript(()=>{const send=(id,action,payload)=>fetch('https://offline-native.invalid/'+action,{method:'POST',body:JSON.stringify(payload)}).then(r=>r.json()).then(r=>FlipCheckDirect.receive(id,r));window.FlipCheckGoogle={ocrAvailable(){return true;},request(id,action,payload){send(id,action,JSON.parse(payload));},readText(id,image_data){send(id,'ocr',{image_data});},readTextScript(id,image_data,script){send(id,'ocr',{image_data,script});},cancel(id){hostEvent({kind:'cancel',id});},storeEvidence(kind,data,meta){hostEvent({kind:'evidence',type:kind,bytes:data.length});},evidenceInfo(){return '{}';}};window.FlipCheckHost={buildInfo(){return JSON.stringify({versionCode:193,versionName:'offline',sourceCommit:'offline'});},beginScan(id){hostEvent({kind:'begin',id});queueMicrotask(()=>FlipCheckBackground.started(id,true,''));},endScan(id,snapshot,outcome){hostEvent({kind:'end',id,outcome});},backgroundInfo(){return '{}';},lastScan(){return '{}';},photoPickerInfo(){return '{}';},saveDiagnostic(){}};});
 await page.route('**/*',async route=>{
  const url=route.request().url();if(url.startsWith(origin+'/'))return route.continue();
  if(url==='https://api.openai.com/v1/responses'){
   const body=JSON.parse(route.request().postData());api.push(body);const kind=body.text.format.name;
   if(options.hold&&kind==='flipcheck_identification')await new Promise(r=>release=r);
   if(options.httpError&&kind==='flipcheck_identification')return route.fulfill({status:401,json:{error:{message:'Offline unauthorized'}}}).catch(()=>{});
   if(options.incomplete&&kind==='flipcheck_identification'&&api.length===1)return route.fulfill({json:{status:'incomplete',incomplete_details:{reason:'max_output_tokens'},output:[{type:'message',content:[{type:'output_text',text:'{'}]}],usage:{input_tokens:350,output_tokens:150}}});
   let payload=kind==='flipcheck_identification'?(options.packet||d.vision):kind==='flipcheck_evidence_detail'?{details:options.details||[]} :kind==='flipcheck_catalogue_comparison'?{comparisons:options.coreComparisons||[]}:kind==='flipcheck_variant_comparison'?{comparisons:options.comparisons||[]}: {entries:[]};
   if(options.malformed&&kind==='flipcheck_identification'){const r=envelope(payload);r.output[0].content[0].text='bad-json';return route.fulfill({json:r});}
   const pages=(d.pages||[]).filter(p=>p.url),web=kind==='flipcheck_catalogue_search'?pages.map(p=>({...p,source_text:p.source_text||p.text||'',snippet:p.text||p.source_text||''})):[];
   return route.fulfill({json:envelope(payload,web)}).catch(()=>{});
  }
  if(url.startsWith('https://offline-native.invalid/')){
   const action=url.split('/').pop(),b=JSON.parse(route.request().postData());native.push({action,...b});let reply={status:503};
   if(action==='ocr')reply=options.noOcr?{state:'ocr_unavailable'}:d.photoOcr?.[ocrIndex++]||{state:'ok',lines:[],text:''};
   if(action==='page'){
    const pages=d.pages.filter(p=>p.url===b.url).sort((a,b)=>(b.text||b.source_text||'').length-(a.text||a.source_text||'').length);if(pages.length)reply={status:200,...pages[0]};
    if(options.certificate&&/psacard.com\/cert\//.test(b.url))reply={status:200,url:b.url,structured_fields:options.certificate};
   }
   if(action==='catalogue'&&options.tcgdex){if(/\/cards\?/.test(b.url))reply={status:200,body:[{id:'ecard3-H23',localId:'H23',name:'Politoed'}]};else if(/\/cards\//.test(b.url))reply={status:200,body:{id:'ecard3-H23',localId:'H23',name:'Politoed',hp:110,attacks:[{name:'Crescita Improvvisa'},{name:'Ranabalzo'},{name:'Spruzza Energia'}],set:{id:'ecard3',name:'Skyridge'},rarity:'Rare Holo',variants:{holo:true}}};else reply={status:200,body:{releaseDate:'2003-05-12'}};}
   if(action==='catalogue'&&options.catalogueReply)reply=options.catalogueReply(b);
   if(action==='image')reply={status:200,image_data:carrier};
   return route.fulfill({json:reply}).catch(()=>{});
  }
  errors.push('Unmocked request '+url);return route.abort();
 });
});
afterEach(async()=>{assert.deepEqual(errors,[]);});after(async()=>{await browser?.close();await new Promise(r=>server.close(r));});
test('193 native host serves every production engine module',async()=>{await reset('politoed');assert.equal(await page.evaluate(()=>FlipCheckCatalogueEngine&&FlipCheckCatalogueSources&&typeof resolveCatalogue193),'function');assert.ok(allow.test('/catalogue-runtime.js'));});
test('193 actual scan uses structured catalogue with one initial AI call and closes Politoed',async()=>{await reset('politoed',{tcgdex:true});const out=await scan();assert.equal(out.identification.engine_final,true);assert.equal(out.identification.family,'Skyridge');assert.equal(out.identification.market_ready,true,JSON.stringify(out.identification));assert.deepEqual(stages(),['flipcheck_identification']);assert.equal(out.visualAssistance.route,'catalogue_engine');assert.ok(native.some(n=>n.action==='catalogue'));assert.ok(out.visualAssistance.engine.observations.length>0);assert.ok(events.some(e=>e.kind==='end'));assert.equal(await page.locator('#marketBtn').isDisabled(),false);assert.equal(await page.locator('#identNote .confrow').count(),0);assert.equal(await page.locator('#identNote .need').count(),0);});
test('missing Italian catalogue falls back to English and completes identification without another AI call',async()=>{
 await reset('politoed',{catalogueReply(b){
  if(b.url.includes('/it/'))return {status:200,body:[]};
  if(/\/cards\?/.test(b.url))return {status:200,body:[{id:'ecard3-H23',localId:'H23',name:'Politoed'},{id:'xy3-18',localId:'18',name:'Politoed'}]};
  if(/\/cards\//.test(b.url))return {status:200,body:{id:'ecard3-H23',localId:'H23',name:'Politoed',hp:110,set:{id:'ecard3',name:'Skyridge'},rarity:'Rare Holo',variants:{holo:true}}};
  return {status:200,body:{releaseDate:'2003-05-12'}};
 }});
 const out=await scan();assert.equal(out.identification.core_identity.status,'confirmed',JSON.stringify(out.visualAssistance.engine));assert.equal(out.identification.market_ready,true);assert.equal(out.identification.language,'it');assert.equal(out.identification.catalogue_reference_language,'en');
 assert.deepEqual(stages(),['flipcheck_identification']);assert.equal(out.visualAssistance.catalogueCoverage.truncated,false);assert.ok(native.some(n=>n.url?.includes('/en/cards?')));assert.ok(!native.some(n=>n.url?.includes('/cards/xy3-18')));
 assert.equal(out.identification.card_identity.rarity,null);assert.equal(await page.locator('#marketBtn').isDisabled(),false);
});
test('a complete local catalogue needs no cross-language fallback',async()=>{
 await reset('politoed',{tcgdex:true});const out=await scan();assert.equal(out.identification.market_ready,true);assert.ok(!native.some(n=>n.url?.includes('/en/cards')));assert.deepEqual(stages(),['flipcheck_identification']);
});
test('193 real web text fallback also finds Politoed without the guessed set',async()=>{await reset('politoed');const out=await scan();assert.equal(out.identification.family,'Skyridge',JSON.stringify(out.visualAssistance.engine?.events));assert.equal(out.identification.market_ready,true);assert.equal(stages().filter(s=>s==='flipcheck_catalogue_search').length,1);assert.ok(out.visualAssistance.queries.every(q=>!q.includes('Aquapolis')));});
test('193 Boniface consumes one serial crop and no further search once /5 is read',async()=>{await reset('boniface',{details:[{field:'serial',text:'2/5',certainty:'clear',image_index:2}]});const out=await scan();assert.equal(out.identification.market_ready,true,JSON.stringify(out.visualAssistance.engine?.events));assert.equal(out.identification.variant,'Green');assert.equal(out.identification.physical_serial.value,'2/5');assert.deepEqual(stages(),['flipcheck_identification','flipcheck_catalogue_search','flipcheck_evidence_detail']);assert.equal(out.visualAssistance.detailReread.requested[0].rotation,90);assert.ok(events.filter(e=>e.type==='original').length===2);});
test('193 unreadable serial retains card identity without inventing /5',async()=>{await reset('boniface');const out=await scan();assert.equal(out.identification.core_identity.status,'confirmed');assert.equal(out.identification.market_ready,false);assert.equal(out.identification.serial_number,null);assert.match(out.identification.next_photo_request,/numerazione/);assert.equal(stages().filter(s=>s==='flipcheck_evidence_detail').length,1);});
test('193 Doncic keeps green and number 280; no statistic-based serial crop',async()=>{await reset('doncic');const out=await scan();assert.equal(out.identification.core_identity.status,'confirmed',JSON.stringify(out.visualAssistance.engine?.events));assert.match(out.identification.model,/280/);assert.ok(out.visualAssistance.queries.every(q=>/green/.test(q)));assert.ok(!stages().includes('flipcheck_evidence_detail'));assert.equal(out.identification.market_ready,false);});
test('193 box retains printed product, rejects incompatible formats and avoids duplicate crops',async()=>{await reset('topps');const out=await scan();assert.equal(out.identification.core_identity.status,'confirmed');assert.equal(out.identification.market_ready,false);assert.match(out.identification.title,/Chrome/i);assert.doesNotMatch(out.identification.variant,/Hobby|Jumbo/);assert.deepEqual(stages(),['flipcheck_identification','flipcheck_catalogue_search']);assert.match(out.identification.next_photo_request,/confezione/);});
test('193 PSA label fallback makes no OCR, web or further vision requests',async()=>{await reset('psa');const out=await scan();assert.equal(out.identification.market_ready,true,JSON.stringify(out.identification));assert.match(out.identification.normalized_query,/PSA.*9|9.*PSA/);assert.deepEqual(stages(),['flipcheck_identification']);assert.ok(!native.some(n=>n.action==='ocr'||n.action==='catalogue'));assert.equal(out.visualAssistance.route,'slab_label');});
test('193 malformed response cannot publish identity and releases lifecycle',async()=>{await reset('politoed',{malformed:true});const out=await scan();assert.equal(out.identification,null);assert.deepEqual(stages(),['flipcheck_identification']);assert.ok(events.some(e=>e.kind==='end'));assert.equal(await page.locator('#identifyBtn').isDisabled(),false);});
test('193 provider failure releases controls without retries',async()=>{await reset('politoed',{httpError:true});const out=await scan();assert.equal(out.identification,null);assert.equal(api.length,1);assert.ok(events.some(e=>e.kind==='end'));});
test('193 incomplete initial response retries once and records both costs',async()=>{await reset('politoed',{incomplete:true,tcgdex:true});const out=await scan();assert.equal(out.identification.market_ready,true);assert.equal(stages().filter(s=>s==='flipcheck_identification').length,2);assert.equal(out.phases.filter(p=>p.stage==='vision').length,1);assert.ok(out.visualAssistance.budget.spentOrReservedUsd>0);});
test('193 cancellation ignores late response and starts no retrieval',async()=>{await reset('politoed',{hold:true});await page.locator('#identifyBtn').click();await page.waitForFunction(()=>apiBusy);while(!release)await new Promise(r=>setTimeout(r,10));await page.locator('#cancelScan').click();release();await page.waitForFunction(()=>!apiBusy);assert.equal(await page.evaluate(()=>ident),null);assert.equal(api.length,1);assert.equal(native.length,0);});
test('193 final result cannot be reopened by the legacy final policy',async()=>{await reset('politoed',{tcgdex:true});await scan();const x=await page.evaluate(()=>{const saved=JSON.stringify(ident);ident=enforceIdentificationPolicy(ident);ident=syncIdentity169(ident);return {same:JSON.stringify(ident)===saved,ready:ident.market_ready};});assert.deepEqual(x,{same:true,ready:true});});
test('193 exports omit API keys and image payloads but include the immutable ledger',async()=>{await reset('boniface');const out=await scan(),text=JSON.stringify(out);assert.doesNotMatch(text,/offline-secret-never-export|data:image|Bearer/);assert.ok(out.visualAssistance.engine.observations.some(o=>o.source==='local_ocr'));await page.screenshot({path:'/tmp/flipcheck26-printing.png',fullPage:true});});

test('193 new observation schema reaches the final UI, without legacy identity fields',async()=>{
 const v=D.politoed.vision,packet={domain:'pokemon',kind:'card',category:'Pokémon',language:'Italian',object_unit:'single',object_regions:v.object_regions,observations:v.photo_clues.map(c=>({field:c.role==='text'?(c.text==='110 PV'?'hp':'attack'):c.role,text:c.text,certainty:c.certainty,image_index:c.image_index,region:c.region,zone:'front',alternatives:[]})),features:[{field:'finish',value:'holo',description:'Holographic foil finish',certainty:'clear',image_index:1,region:null,zone:'artwork'}],hypotheses:[{field:'family',value:'Aquapolis'}],slab_reading:null};
 await reset('politoed',{packet,tcgdex:true});const out=await scan();assert.equal(out.identification.family,'Skyridge');assert.equal(out.identification.market_ready,true,JSON.stringify(out.visualAssistance.engine));assert.equal(out.identification.language,'it');assert.ok(api[0].text.format.schema.required.includes('observations'));assert.ok(!api[0].text.format.schema.required.includes('model'));assert.deepEqual(stages(),['flipcheck_identification']);
});

test('193 official PSA certificate closes identity with the stored grade and no later AI',async()=>{await reset('psa',{certificate:[['Cert Number','64613920'],['Year','1999'],['Set Name','P.M. Japanese CD Promo'],['Card Name','Charizard'],['Card Number','6'],['Variation','Holo'],['Grade','MINT 9']].map(([label,value])=>({label,value}))});const out=await scan();assert.equal(out.visualAssistance.route,'slab_certificate');assert.equal(out.identification.slab_verification.certificate_verified,true);assert.equal(out.identification.market_ready,true);assert.deepEqual(stages(),['flipcheck_identification']);assert.equal(native.length,1);});
test('193 variant comparison needs independent visual details, not just local similarity',async()=>{
 for(const features of [1,2]){
  await reset('boniface',{comparisons:[{reference_id:'variant0',match:true,conflicts:[],features:[{field:'border_color',original:'green',reference:'green',agrees:true,certainty:'clear'},{field:'pattern',original:'wave',reference:'wave',agrees:true,certainty:'clear'}].slice(0,features)}]});
  const out=await page.evaluate(async vision=>{scan164=newContext164();lastVisionReading=vision;const E=FlipCheckCatalogueEngine,l=E.ingestVision(new E.Ledger(vision),vision),entry={subject:'Victor Boniface',number:'21',family:'Select Road to FIFA World Cup 2026',year:'2025-26',source:{url:'https://www.beckett.com/green-wave'},grounded:true,variants:[{name:'Green Wave',colors:['green'],patterns:['wave'],visual_required:true}]},pages=[{url:entry.source.url,image_details:[{image_url:'https://images.beckett.com/green-wave.jpg',caption:'Victor Boniface Green Wave'}]}];const before=E.reduce(l,[entry]);await compareVariants193(l,before,scan164,pages);return {result:E.reduce(l,[entry]),measurements:scan164.localReferenceComparisons};},d.vision);
  assert.equal(out.result.market_ready,features===2);assert.ok(out.measurements.length>0);assert.deepEqual(stages(),['flipcheck_variant_comparison']);assert.ok(native.some(n=>n.action==='image'));
 }
});

test('193 fragmented Jordan name launches candidate comparison without requiring a back photo',async()=>{
 await reset('jordan191',{photoCount:1,coreComparisons:[{reference_id:'core1',match:true,ambiguous:false,reference_subject:'MICHAEL JORDAN',reference_number:'141',conflicts:[],features:[{field:'artwork',original:'portrait',reference:'portrait',agrees:true,certainty:'clear'},{field:'layout',original:'horizontal frame and flag',reference:'horizontal frame and flag',agrees:true,certainty:'clear'}]}],mutate(d){d.pages=['A','B'].map(id=>({url:'https://www.paniniamerica.net/test-product-'+id,title:'2031 Product '+id+' #141 MICHAEL JORDAN',text:'Set:\n2031 Panini Product '+id+'\nPlayer:\nMICHAEL JORDAN\nCard Number: 141',image_details:[{image_url:'https://www.paniniamerica.net/test-'+id+'.jpg',caption:'MICHAEL JORDAN #141 Product '+id}]}));}});
 const out=await scan();assert.equal(out.identification.core_identity.status,'confirmed',JSON.stringify(out.visualAssistance.engine?.events));assert.equal(out.identification.family,'Product B');assert.ok(out.visualAssistance.queries[0].includes('MICHAEL JORDAN'));assert.ok(out.visualAssistance.queries[0].includes('USA'));assert.ok(stages().includes('flipcheck_catalogue_comparison'));assert.equal(out.uploadedImageCount,1);
});
