const {test}=require('node:test'),assert=require('node:assert/strict'),E=require('../src/main/assets/catalogue-engine'),S=require('../src/main/assets/catalogue-sources'),X=require('../src/main/assets/ximilar-policy');
function ledger(zone='back'){const v={domain:'sports',kind:'card',observations:[['subject','Kobe Bryant','back'],['product','SP Authentic','front'],['subset','First Class','front'],['collector_number','FC7','back'],['season','1999-2000',zone]].map(([field,text,zone])=>({field,text,zone,certainty:'clear',image_index:1}))};return E.ingestVision(new E.Ledger(v),v);}
const entry=(subject,year)=>({subject,year,number:'FC7',family:'SP Authentic',subset:'First Class',grounded:true,source:{url:'https://www.beckett.com/basketball/example'},variants:[]});
test('234 sports alias cannot change photographed Kobe into Kidd',()=>{const r=E.evaluate(ledger(),{...entry('Jason Kidd','1999-00'),aliases:['Kobe Bryant']});assert.equal(r.eligible,false);assert.ok(r.reasons.includes('different_subject'));});
test('234 back season stays observed but no longer excludes matching 2000-01 Kobe',()=>{const l=ledger(),r=E.reduce(l,[entry('Jason Kidd','1999-00'),entry('Kobe Bryant','2000-01')]);assert.equal(l.pick('season').value,'1999-2000');assert.equal(E.keyValues(l).year,'');assert.equal(r.core_identity.status,'confirmed');assert.equal(r.card_identity.subject,'Kobe Bryant');assert.equal(r.card_identity.date,'2000-01');});
test('234 explicit front or label product season still rejects another year',()=>{for(const zone of ['front','label'])assert.ok(E.evaluate(ledger(zone),entry('Kobe Bryant','2000-01')).reasons.includes('different_product_season'));});
test('234 same subject and number in multiple seasons remains ambiguous',()=>{const r=E.reduce(ledger(),[entry('Kobe Bryant','1999-00'),entry('Kobe Bryant','2000-01')]);assert.notEqual(r.core_identity.status,'confirmed');});
test('234 shared checklist page does not invent person aliases',()=>{const url='https://www.tcdb.com/Checklist.cfm/sid/123',text='1999-00 SP Authentic First Class\nFC2 Kobe Bryant\nFC7 Jason Kidd',page={url,title:'1999-00 SP Authentic First Class',text},e={...entry('Jason Kidd','1999-00'),source_url:url,entry_quote:'FC7 Jason Kidd',proof:{subject:'FC7 Jason Kidd',number:'FC7 Jason Kidd',family:'SP Authentic',year:'1999-00'}};const out=S.groundedExtraction({entries:[e]},[page],ledger());assert.equal(out.accepted.length,1);assert.deepEqual(out.accepted[0].aliases,[]);});
test('234 surname-first Beckett quote grounds Kobe without accepting other people',()=>{const url='https://www.beckett.com/basketball/example',text='2000-01 SP Authentic First Class\nPlayer: Bryant, Kobe\nCard Number: FC7',e={...entry('Kobe Bryant','2000-01'),source_url:url,entry_quote:text,proof:{subject:'Player: Bryant, Kobe',number:'Card Number: FC7',family:'SP Authentic',year:'2000-01'}};assert.equal(S.groundedExtraction({entries:[e]},[{url,title:'2000-01 SP Authentic First Class',text}],ledger()).accepted.length,1);});
test('234 token normalization and diagnostic redaction',()=>{const secret='secret-token-12345678901234567890';assert.equal(X.token(' Token '+secret+' '),secret);const d=X.errorDetails({detail:'Invalid Token '+secret,status:{request_id:'0d3e2338-dd87-4b0a-974a-86b1fb1d4847'}},secret);assert.ok(!JSON.stringify(d).includes(secret));assert.equal(d.request_id,'0d3e2338-dd87-4b0a-974a-86b1fb1d4847');assert.equal(X.state(401),'authentication_failed');});
test('234 actual build233 Kobe report selects 2000-01 and retains original readings',()=>{const f=require('./fixtures/identity-234-kobe.json'),l=E.ingestVision(new E.Ledger(f.vision),f.vision);for(const p of f.phases)E.applyDetails(l,p.result.details,p.result.details.map(d=>({field:d.field,image_index:d.image_index})));const r=E.reduce(l,f.entries);assert.equal(r.core_identity.status,'confirmed');assert.equal(r.card_identity.subject,'Kobe Bryant');assert.equal(r.card_identity.date,'2000-01');assert.equal(r.physical_card_number,'FC7');assert.equal(l.pick('season').value,'1999-2000');assert.ok(l.candidates.filter(e=>e.subject==='Jason Kidd').every(e=>!e.eligible));});
