const {test}=require('node:test'),assert=require('node:assert/strict');
const E=require('../src/main/assets/catalogue-engine'),L=require('../src/main/assets/lens-policy');
function fixture(name){const f=structuredClone(require('./fixtures/lens-221-'+name+'.json'));f.l=E.ingestVision(new E.Ledger(f.vision),f.vision);f.references.forEach(r=>r.image_data='recorded_download');return f;}
function run(f){for(const b of f.batches)L.reconcileOriginal208(f.l,b.reply.original_readings,f.crops);const checked=L.resolveComparisons217(f.l,f.batches,f.references),result=L.present206(E.reduce(f.l,checked.accepted),checked.accepted,f.l);return {checked,result};}
test('221 actual blurred Dragonite closes with catalogue number, never a fabricated photo number',()=>{const f=fixture('dragonite-blur'),{checked,result:r}=run(f);assert.equal(r.market_ready,true);assert.equal(r.physical_card_number,null);assert.ok(E.numbersMatch(r.source_confirmed_catalog_number,'9/165'));assert.equal(r.variant,'Holo');assert.equal(r.language,'it');assert.equal(r.core_identity.fields.find(f=>f.field==='catalog_number').origin,'catalogue');assert.ok(!checked.accepted.some(e=>E.numbersMatch(e.number,'43/165')));});
test('221 uncertain Dragonite footer cannot constrain catalogue query',()=>{const f=fixture('dragonite-blur');f.l.add('collector_number','4/62',{source:'focused_vision',certainty:'uncertain',image_index:1});assert.doesNotMatch(E.query(f.l,'reference'),/4\/62/);assert.equal(f.l.active('collector_number').at(-1).value,'4/62');});
test('221 missing number alone cannot accept a Pokemon reference with no finish distinction',()=>{const f=fixture('dragonite-blur');for(const b of f.batches)for(const c of b.reply.comparisons)c.features=c.features.filter(x=>x.field!=='configuration');assert.equal(run(f).result.market_ready,false);});
test('221 actual clear Dragonite still needs and accepts the original holo detail',()=>{const f=fixture('dragonite');let {checked,result:r}=run(f);assert.equal(r.market_ready,false);E.applyDetails(f.l,f.details.flat(),E.recoveryRequests(f.l,r));r=E.reduce(f.l,checked.accepted);assert.equal(r.market_ready,true);assert.equal(r.physical_card_number,'9/165');});
test('221 actual Topps matching Hobby configuration closes and Blaster stays excluded',()=>{const f=fixture('topps'),{checked,result:r}=run(f);assert.equal(r.market_ready,true);assert.match(r.title,/2025-26.*Topps Chrome Update Series.*Hobby Box/);assert.doesNotMatch(r.title,/Wembanyama|Flagg/);assert.ok(checked.rejected.some(e=>e.id==='lens-36'));assert.equal(r.next_photo_request,null);});
test('221 actual Zagor closes from matched cover, publisher and format without inventing a model code',()=>{const f=fixture('zagor'),{result:r}=run(f);assert.equal(r.market_ready,true);assert.match(r.title,/1977.*Zagor/);assert.equal(f.l.pick('model_code'),null);assert.equal(r.next_photo_request,null);});
test('221 explicit conflicting model still rejects the matching-looking publication',()=>{const f=fixture('zagor');f.l.add('model_code','OTHER-123',{certainty:'clear',source:'vision',image_index:1});assert.equal(run(f).result.market_ready,false);});
test('221 actual unnumbered two-person panel closes while preserving photographed name separately',()=>{const f=fixture('panel'),{result:r}=run(f);assert.equal(r.market_ready,true);assert.match(r.title,/1958.*Rekord Journal.*Santos.*Pelé/);assert.equal(r.physical_card_number,null);assert.equal(f.l.pick('subject').value,'MANOEL FRANCISCO SANTOS');});
test('221 multi-person subject relaxation does not apply to a single-person card',()=>{const f=fixture('panel');f.l.base.object_unit='single';assert.equal(run(f).result.market_ready,false);});
test('221 actual Yamal retains core and closes /9 without adopting Purple /49 or Orange',()=>{const f=fixture('yamal'),{result:r}=run(f);assert.equal(r.market_ready,true);assert.match(r.title,/Obsidian.*SUPERNOVA.*\/9/);assert.equal(r.serial_number,'8/9');assert.equal(r.variant,'');assert.equal(r.variant_resolution.variant_origin,'physical_print_run');assert.doesNotMatch(r.title,/Purple|Orange|49/i);});
test('221 Yamal cannot borrow a core from a different card number',()=>{const f=fixture('yamal');for(const b of f.batches)for(const c of b.reply.comparisons)c.identity.number='18';assert.equal(run(f).result.market_ready,false);});
test('221 ambiguous serial cannot trigger print-run closure',()=>{const f=fixture('yamal');for(const a of f.l.evidence('serial'))f.l.add('serial',a.value,{certainty:'uncertain',source:'focused_vision',image_index:a.image_index,supersedes:[a.id]});assert.equal(run(f).result.market_ready,false);});
test('221 actual Doncic keeps full printed 2018-19 season, Green and photographed RC',()=>{const {result:r}=run(fixture('doncic'));assert.equal(r.market_ready,true);assert.match(r.title,/2018-19/);assert.match(r.title,/green prizm.*RC/);assert.equal(r.source_confirmed_year,'2018');});
test('221 actual Machamp bare shadow response is insufficient; simulated concordant border read closes Shadowless once',()=>{const f=fixture('machamp'),{checked,result:r}=run(f);assert.ok(r.variant_resolution.pending.includes('shadow'));const requests=E.recoveryRequests(f.l,r).map(q=>q.field==='shadow'?{...q,reason:'shadow_border_verification'}:q);E.applyDetails(f.l,f.details.flat(),requests);assert.equal(E.reduce(f.l,checked.accepted).market_ready,false);
 E.applyDetails(f.l,[{field:'shadow',text:'absent',right_border:'absent',bottom_border:'absent',visual_reason:'Simulated visible right and bottom outer edges have no printed drop shadow.',certainty:'clear',evidence_found:true,image_index:1}],requests);const out=L.present206(E.reduce(f.l,checked.accepted),checked.accepted,f.l);assert.equal(out.market_ready,true);assert.match(out.title,/Shadowless/);assert.equal((out.title.match(/1st Edition/g)||[]).length,1);
});
test('221 disagreeing shadow borders cannot create a confident classification',()=>{const f=fixture('machamp'),{checked,result:r}=run(f),requests=E.recoveryRequests(f.l,r).map(q=>({...q,reason:'shadow_border_verification'}));E.applyDetails(f.l,[{field:'shadow',text:'present',right_border:'present',bottom_border:'absent',visual_reason:'Borders disagree.',certainty:'clear',evidence_found:true,image_index:1}],requests);assert.equal(E.reduce(f.l,checked.accepted).market_ready,false);});
