const {test}=require('node:test'),assert=require('node:assert/strict');
const E=require('../src/main/assets/catalogue-engine'),L=require('../src/main/assets/lens-policy'),S=require('../src/main/assets/slab-identity');
function fixture(name){const f=structuredClone(require('./fixtures/lens-220-'+name+'.json'));f.l=E.ingestVision(new E.Ledger(f.vision),f.vision);E.ingestOcr(f.l,f.photoOcr);f.references.forEach(r=>r.image_data='recorded_download');return f;}
test('220 actual cropped Curry closes from saved comparisons without losing the subject to the rear product logo',()=>{const f=fixture('curry');for(const b of f.batches)L.reconcileOriginal208(f.l,b.reply.original_readings,f.crops);const c=L.resolveComparisons217(f.l,f.batches,f.references),r=E.reduce(f.l,c.accepted);assert.equal(r.market_ready,true);assert.equal(f.l.pick('subject').value,'Stephen Curry');assert.ok(f.l.evidence('product').some(a=>/ADRENALYN XL/.test(a.value)));assert.equal(r.physical_card_number,null);assert.equal(r.variant,'');assert.match(r.title,/2009-10.*Stephen Curry/);assert.doesNotMatch(r.title,/77/);});
test('220 product/brand/team role normalization applies across subjects and cannot supersede the real name',()=>{const b={domain:'sports',observations:[{field:'subject',text:'Another Person',certainty:'clear',image_index:1},{field:'product',text:'Topps Chrome Update',certainty:'clear',image_index:2},{field:'brand',text:'Topps',certainty:'clear',image_index:2},{field:'team',text:'Example Team',certainty:'clear',image_index:1}]};const l=E.ingestVision(new E.Ledger(b),b),name=l.pick('subject');for(const [v,field] of [['Topps Chrome Update','product'],['Topps','brand'],['Example Team','team']]){const a=l.add('subject',v,{source:'focused_vision',certainty:'clear',image_index:2,supersedes:[name.id]});assert.equal(a.field,field);assert.equal(l.pick('subject').value,'Another Person');assert.equal(a.reported_field,'subject');}l.add('subject','Different Person',{certainty:'clear',source:'vision',image_index:2});assert.equal(l.pick('subject'),null);});
test('220 actual Kobe #81 references challenge the initial 18 without becoming photo evidence',()=>{const f=fixture('kobe'),rows=L.identifierChallenges220(f.references,f.l),filtered=L.filterOcr214(f.references,f.l);assert.equal(rows.length,4);assert.ok(rows.every(r=>![...filtered.excluded].some(x=>x.id===r.id)));assert.equal(f.l.pick('collector_number').value,'18');assert.equal(E.reduce(f.l,[]).market_ready,false);const a=f.l.pick('collector_number');E.applyDetails(f.l,[{field:'collector_number',text:'81',certainty:'clear',evidence_found:true,image_index:2}],[{key:'test',field:'collector_number',reason:'catalogue_number_conflict',image_index:2,region:a.region}]);assert.equal(f.l.pick('collector_number').value,'81');assert.ok(L.rankOcr209(f.references,f.l)[0].ocrRank.reasons.includes('identifier_agrees'));assert.ok(f.l.values('collector_number').some(a=>a.value==='18'));});
test('220 unrelated names and product families cannot trigger the number recovery',()=>{const f=fixture('kobe');for(const r of f.references){r.title='Another Person Another Set #81';r.ocr={state:'ok',text:'#81'};}assert.equal(L.identifierChallenges220(f.references,f.l).length,0);});
test('220 an uncertain targeted number read cannot replace the initial number',()=>{const f=fixture('kobe'),a=f.l.pick('collector_number');E.applyDetails(f.l,[{field:'collector_number',text:'81',certainty:'uncertain',evidence_found:false,image_index:2}],[{key:'test',field:'collector_number',reason:'catalogue_number_conflict',image_index:2,region:a.region}]);assert.equal(f.l.pick('collector_number').value,'18');});
test('220 actual Mewtwo normalizes zh-Hant while retaining uncertain set text and missing overall grade',()=>{const f=fixture('mewtwo'),a=S.labelFacts(f.vision),r=S.close(f.vision,a);assert.equal(r.market_ready,true);assert.equal(r.language,'zh-hant');assert.match(r.title,/CHN-T/);assert.doesNotMatch(r.title,/zh-Hant/);assert.equal(r.grading.grade,null);assert.equal(a.set_code,'');assert.ok(a.set_code_readings.some(x=>x.text==='C5sAC'&&x.certainty==='uncertain'));});
test('220 only an explicit overall grade label can recover a missing grade; subgrades cannot',()=>{const f=fixture('mewtwo');f.vision.slab_reading.label_text+=' PRISTINE 10';assert.equal(S.labelFacts(f.vision).grade,'10 PRISTINE');f.vision.slab_reading.grade_certainty='uncertain';assert.equal(S.labelFacts(f.vision).grade,'');});
test('220 the recorded Cloyster label retains its grade and four subgrades',()=>{const f=fixture('cloyster'),r=S.close(f.vision,S.labelFacts(f.vision));assert.equal(r.market_ready,true);assert.equal(r.grading.grade,'9 MINT');assert.equal(r.grading.subgrades.length,4);assert.match(r.title,/#8.*Cloyster.*ITA/);});
