const {test}=require('node:test'),assert=require('node:assert/strict');
const E=require('../src/main/assets/catalogue-engine'),L=require('../src/main/assets/lens-policy');
function f(name){const x=structuredClone(require('./fixtures/lens-226-'+name+'.json'));x.l=E.ingestVision(new E.Ledger(x.vision),x.vision);x.references.forEach(r=>r.image_data='recorded');return x;}
function run(x){for(const b of x.batches)L.reconcileOriginal208(x.l,b.reply.original_readings,x.crops);const c=L.resolveComparisons217(x.l,x.batches,x.references);return {c,r:L.present206(E.reduce(x.l,c.accepted),c.accepted,x.l,'it')};}
test('226 actual Hill 225 closes from printed text plus pattern despite different semantic fields',()=>{const x=f('hill'),{r}=run(x);assert.equal(r.market_ready,true);assert.match(r.variant,/superfractor/i);assert.equal(r.physical_serial,null);assert.ok(x.l.evidence('printing_name')[0].derived_from);assert.equal(x.l.evidence('printing_name')[0].original_text,'BCA-AHJ SUPERFRACTOR™');});
test('226 missing corroboration or different physical identifier cannot confirm Hill variant',()=>{for(const field of ['pattern','collector_number']){const x=f('hill');x.vision.features=x.vision.features.filter(f=>f.field!==field);if(field==='collector_number')x.vision.observations.find(o=>o.field===field).text='BCA-XYZ';x.l=E.ingestVision(new E.Ledger(x.vision),x.vision);assert.equal(run(x).r.market_ready,false);}});
test('226 actual Shaq keeps numbered core despite finish disagreement and copyright rollover',()=>{const x=f('shaq'),{r,c}=run(x);assert.equal(r.core_identity.status,'confirmed');assert.equal(r.physical_card_number,'7');assert.equal(r.family,'Flair Showcase');assert.equal(r.market_ready,false);assert.equal(r.variant_resolution.status,'pending');assert.equal((r.title.match(/1999-00/g)||[]).length,1);assert.ok(!c.rejected.some(r=>r.reasons.includes('different_original_year')));assert.equal(x.l.pick('brand').value,'Fleer');assert.ok(x.l.evidence('copyright').some(a=>a.source==='lens_original_reread'));});
test('226 ending copyright year supports season rollover but not a different release season',()=>{assert.equal(L.yearReading212('2000','1999-00'),true);assert.equal(L.yearReading212('1998','1999-00'),false);assert.equal(E.sportsSeason215('2000-01','1999-00'),false);});
test('226 a product trademark cannot become a printing and unknown pattern words survive',()=>{const x=f('hill');assert.ok(!x.l.evidence('printing_name').some(a=>/bowman/i.test(a.value)));assert.ok(x.l.evidence('pattern').some(a=>/circolare/.test(a.value)));});
test('226 partial translated title goes through the same normalized title composer',()=>{const x=f('shaq');for(const b of x.batches)L.reconcileOriginal208(x.l,b.reply.original_readings,x.crops);const r=L.partialTitle208(E.reduce(x.l,[]),x.l,'it');assert.equal((r.title.match(/1999-00/g)||[]).length,1);});

test('226 plain standalone printing text without trademark retains corroborated identity',()=>{const x=f('hill');x.vision.observations.find(o=>/SUPERFRACTOR/.test(o.text)).text='SuperFractor';x.l=E.ingestVision(new E.Ledger(x.vision),x.vision);assert.equal(run(x).r.market_ready,true);});
test('226 actual Mewtwo 225 remains a one-read slab identity with set code and subgrades',()=>{const S=require('../src/main/assets/slab-identity'),x=f('mewtwo'),r=S.close(x.vision,S.labelFacts(x.vision));assert.equal(r.market_ready,true);assert.match(r.title,/CS5aC/);assert.equal(r.grading.subgrades.length,4);assert.equal(r.next_photo_request,null);});
