const {test}=require('node:test'),assert=require('node:assert/strict');
const E=require('../src/main/assets/catalogue-engine'),L=require('../src/main/assets/lens-policy');
const crop={id:'original-1-lower',image_index:1,region:{image_index:1,x:.1,y:.7,width:.8,height:.2}};
function ledger(){const l=new E.Ledger({domain:'pokemon',kind:'card'});for(const [field,value] of Object.entries({subject:'超夢 ex',collector_number:'135/127',set_code:'SV8a',rarity_text:'SAR',language:'zh'}))l.add(field,value,{certainty:'clear',source:'vision',image_index:1});return l;}
const row=(field,text)=>({field,full_text:text,crop_text:text,image_index:1,crop_id:crop.id,evidence_found:true,certainty:'clear',display_names:{it:'Mewtwo V',en:'Mewtwo V'}});
test('208 agreeing original views replace incorrect set and rarity while preserving provenance',()=>{const l=ledger(),before=l.atoms.slice();const out=L.reconcileOriginal208(l,[row('set_code','CS5aC'),row('rarity_text','SR')],[crop]);assert.equal(out.accepted.length,2);assert.equal(l.pick('set_code').value,'CS5aC');assert.equal(l.pick('rarity_text').value,'SR');assert.equal(l.pick('set_code').source,'lens_original_reread');assert.deepEqual(l.atoms.slice(0,before.length),before);assert.equal(l.values('set_code')[0].value,'SV8a');});
test('208 unreadable, mismatched or unattributed views cannot overwrite the original',()=>{for(const patch of [{crop_text:'CS4aC'},{evidence_found:false},{certainty:'uncertain'},{crop_id:'candidate-1'},{image_index:2},{full_text:''}]){const l=ledger();assert.equal(L.reconcileOriginal208(l,[{...row('set_code','CS5aC'),...patch}],[crop]).accepted.length,0);assert.equal(l.pick('set_code').value,'SV8a');}});
test('208 contradictory reread replies cannot win through array order',()=>{const l=ledger();const out=L.reconcileOriginal208(l,[row('set_code','CS5aC'),row('set_code','SV8a')],[crop]);assert.equal(out.accepted.length,0);assert.equal(l.pick('set_code').value,'SV8a');});
test('208 corrected original name supplies a localized partial title without closing identity',()=>{const l=ledger();L.reconcileOriginal208(l,[row('subject','超梦V'),row('set_code','CS5aC')],[crop]);const result=E.reduce(l,[]);L.present206(result,[],l,'it');assert.match(result.title,/Mewtwo V.*CS5aC.*135\/127.*CHN/);assert.equal(result.market_ready,false);assert.equal(l.pick('subject').value,'超梦V');assert.equal(l.pick('subject_alias'),null);});
test('208 mistranslated suffix cannot enter partial titles',()=>{const l=ledger();L.reconcileOriginal208(l,[{...row('subject','超梦V'),display_names:{it:'Mewtwo ex',en:'Mewtwo ex'}}],[crop]);const r=E.reduce(l,[]);L.present206(r,[],l,'it');assert.doesNotMatch(r.title,/Mewtwo ex/);});
test('208 stale aliases are not reused after a later physical correction',()=>{const l=ledger();L.reconcileOriginal208(l,[row('subject','超梦V')],[crop]);L.reconcileOriginal208(l,[{...row('subject','超梦ex'),display_names:{it:'',en:''}}],[crop]);const r=E.reduce(l,[]);L.present206(r,[],l,'it');assert.doesNotMatch(r.title,/Mewtwo V/);});
test('208 text-conflicting candidates remain available for visual verification',()=>{const l=ledger(),refs=[{id:'a',title:'Mewtwo V CS5aC 135/127 Chinese',url:'https://example.com/a',snippet:''},{id:'b',title:'Mewtwo V SWSH229 English',url:'https://example.com/b',snippet:''}].map(c=>L.evaluate(c,l));assert.equal(L.retrievalPool208(refs).length,2);assert.ok(refs.some(c=>!c.eligible));});
test('208 candidate values alone never amend photographed identifiers',()=>{const l=ledger();L.visualEntries206({comparisons:[{reference_id:'a',original_reading:{number:'136/127'},identity:{number:'136/127'}}]},[{id:'a',image_data:'pixels',title:'Mewtwo 136/127',snippet:''}],l);assert.equal(l.pick('collector_number').value,'135/127');});

test('208 same art and number cannot hide a different V/ex suffix',()=>{const l=ledger();const c={reference_id:'a',match:true,ambiguous:false,title_matches_image:true,conflicts:[],original_reading:{subject:'超夢 ex',number:'135/127',language:'zh'},reference_reading:{subject:'超夢V',number:'135/127',language:'zh'},identity:{}};const out=L.visualEntries206({comparisons:[c]},[{id:'a',image_data:'pixels',title:'Mewtwo V',snippet:''}],l);assert.ok(out.rejected[0].reasons.includes('different_reference_subject_suffix'));});
