const {test}=require('node:test'),assert=require('node:assert/strict');
const E=require('../src/main/assets/catalogue-engine'),L=require('../src/main/assets/lens-policy'),S=require('../src/main/assets/slab-identity');
function fixture(name){const f=structuredClone(require('./fixtures/lens-225-'+name+'.json'));f.l=E.ingestVision(new E.Ledger(f.vision),f.vision);for(const r of f.references||[])r.image_data='recorded_download';return f;}
function run(f){const c=L.resolveComparisons217(f.l,f.batches,f.references);return {c,r:E.reduce(f.l,c.accepted)};}
test('225 actual Hill 224 core is retained across finish differences; physical label and surface close printing without serial',()=>{const f=fixture('hill'),{c,r}=run(f);assert.equal(r.market_ready,true);assert.equal(r.variant,'Superfractor');assert.equal(r.physical_serial,null);assert.equal(r.variant_resolution.variant_origin,'original_photo');assert.equal(c.accepted.length,1);assert.equal(c.accepted[0].core_only,true);assert.ok(c.rejected.some(x=>x.id==='lens-27'));assert.deepEqual(E.recoveryRequests(f.l,r),[]);});
test('225 no printed variant or separate surface corroboration leaves printing pending',()=>{for(const field of ['subset','finish']){const f=fixture('hill');f.vision.observations=f.vision.observations.filter(o=>o.field!==field);f.vision.features=f.vision.features.filter(o=>o.field!==field);delete f.vision.physical_observations;delete f.vision.photo_clues;f.l=E.ingestVision(new E.Ledger(f.vision),f.vision);const {r}=run(f);assert.equal(r.core_identity.status,'confirmed');assert.equal(r.market_ready,false);}});
test('225 scoped identity never forgives incompatible subject, number, season, autograph or layout',()=>{for(const change of ['subject','number','year','autograph','layout']){const f=fixture('hill');for(const b of f.batches)for(const c of b.reply.comparisons){if(['subject','number','year'].includes(change))c.identity[change]='incompatible';else if(change==='autograph')c.conflicts.push('Different autograph configuration');else c.features.filter(x=>x.field==='layout').forEach(x=>x.agrees=false);}assert.equal(run(f).r.market_ready,false,change);}});
test('225 recovery without a prior catalogue result uses the available rear instead of throwing',()=>{const f=fixture('shaq');assert.ok(f.pipeline_errors.some(e=>e.message.includes('core_identity')));const req=E.recoveryRequests(f.l).find(r=>r.field==='collector_number');assert.equal(req.image_index,2);});
test('225 actual Mewtwo 224 closes slab without inventing uncertain set code',()=>{const f=fixture('mewtwo'),r=S.close(f.vision,S.labelFacts(f.vision));assert.equal(r.market_ready,true);assert.match(r.title,/135\/127/);assert.doesNotMatch(r.title,/CS5aC/i);assert.equal(r.next_photo_request,null);});
test('225 a single concordant sports reference closes without a number on either side',()=>{const f=structuredClone(require('./fixtures/lens-224-shaq.json'));f.l=E.ingestVision(new E.Ledger(f.vision),f.vision);f.references.forEach(r=>r.image_data='recorded');for(const b of f.batches)for(const c of b.reply.comparisons){c.identity.number='';c.reference_reading.number='';c.original_reading.number='';}const {r}=run(f);assert.equal(r.market_ready,true);assert.equal(r.physical_card_number,null);assert.equal(r.source_confirmed_catalog_number,null);assert.match(r.title,/1999-00/);});
