const {test}=require('node:test'),assert=require('node:assert/strict');
const E=require('../src/main/assets/catalogue-engine'),L=require('../src/main/assets/lens-policy'),S=require('../src/main/assets/slab-identity');
function f(name){const x=structuredClone(require('./fixtures/lens-219-'+name+'.json'));x.l=E.ingestVision(new E.Ledger(x.vision),x.vision);x.references.forEach(r=>r.image_data='downloaded');return x;}
function replay(x){for(const b of x.batches)L.reconcileOriginal208(x.l,b.reply.original_readings,x.crops);const q=L.resolveComparisons217(x.l,x.batches,x.references);return E.reduce(x.l,q.accepted);}
test('219 recorded Curry card comparison closes without using its overall as card number or RC as variant',()=>{const x=f('curry'),r=replay(x);assert.equal(r.market_ready,true);assert.equal(r.physical_card_number,null);assert.equal(r.source_confirmed_catalog_number,null);assert.ok(x.l.evidence('statistics_number').some(a=>a.value==='77'));assert.doesNotMatch(r.title,/77/);assert.equal(r.variant,'');assert.equal(r.card_identity.is_rookie,true);});
test('219 rating-panel classification applies to other subjects and other overall values',()=>{const x=f('curry');x.vision.observations=x.vision.observations.map(o=>o.field==='subject'?{...o,text:'Another Player'}:o.field==='collector_number'?{...o,text:'92'}:o);const l=E.ingestVision(new E.Ledger(x.vision),x.vision);assert.equal(l.pick('collector_number'),null);assert.equal(l.pick('statistics_number').value,'92');});
test('219 recorded Kobe preserves the real rear number, accepts the observed foil and closes',()=>{const x=f('kobe'),r=replay(x);assert.equal(r.market_ready,true,JSON.stringify(r));assert.equal(r.physical_card_number,'81');assert.equal(x.l.active('pokedex_number').length,0);assert.equal(r.source_confirmed_year,'1997-98');assert.match(r.variant,/foil/i);assert.equal((r.title.match(/foil/gi)||[]).length,1);});
test('219 omitted variants close unnamed; a serial or named unresolved parallel still needs resolution',()=>{const x=f('curry');x.l.add('serial','2/5',{source:'vision',image_index:2,certainty:'clear'});assert.equal(replay(x).market_ready,false);const y=f('curry');y.batches[0].reply.comparisons[0].ambiguous=true;assert.equal(replay(y).market_ready,false);});
test('219 number normalization separates rarity without dropping real prefixes or suffixes',()=>{assert.equal(E.number('135/127 SR'),'135/127');assert.equal(E.number('H23/H32'),'H23/H32');assert.equal(E.number('81A'),'81A');assert.equal(E.numberParts('135/127SR'),null);});
test('219 new Mewtwo label closes with empty family field and keeps normalized name and label set code',()=>{const x=f('mewtwo'),facts=S.labelFacts(x.vision),r=S.close(x.vision,facts);assert.equal(r.market_ready,true);assert.equal(r.card_identity.number,'135/127');assert.equal(r.card_identity.set_code,'CS5aC');assert.equal(r.name_identity.en,'Mewtwo V');assert.equal(r.language,'zh');assert.equal(r.grading.company,'UNKNOWN');});
test('219 slab identity also accepts a readable graded comic; unknown grade does not block it',()=>{const b={kind:'object',domain:'generic',language:'en',slab_reading:{present:true,grader:'Unknown',label_text:'1963 Amazing Spider-Man #1',card_title:'Amazing Spider-Man',subject:'Amazing Spider-Man',family:'',year:'1963',card_number:'1',certainty:'clear',title_certainty:'clear',grade_certainty:'uncertain',object_match:'matches'}};assert.equal(S.close(b,S.labelFacts(b)).market_ready,true);b.slab_reading.title_certainty='uncertain';assert.equal(S.close(b,S.labelFacts(b)).market_ready,false);});

test('219 a graded object label with an explicit model does not require an invented year',()=>{const b={kind:'object',domain:'generic',slab_reading:{present:true,label_text:'Nintendo Game Boy DMG-01',subject:'Game Boy',family:'Nintendo',model:'DMG-01',card_title:'Nintendo Game Boy DMG-01',title_certainty:'clear',object_match:'matches'}};const r=S.close(b,S.labelFacts(b));assert.equal(r.market_ready,true);assert.match(r.title,/DMG-01/);});
