const {test}=require('node:test'),assert=require('node:assert/strict'),E=require('../src/main/assets/catalogue-engine'),L=require('../src/main/assets/lens-policy');
function replay(name){const f=structuredClone(require('./fixtures/lens-215-'+name+'.json')),l=new E.Ledger(f.vision);E.ingestVision(l,f.vision);for(const r of f.references)r.image_data='downloaded';return {...f,l};}
function first(f){const b=f.batches[0];L.reconcileOriginal208(f.l,b.reply.original_readings,f.crops);return L.visualEntries206(b.reply,f.references,f.l);}
test('215 actual Charizard closes without copyright and never relabels Pokédex as collector number',()=>{const f=replay('charizard'),out=first(f),r=E.reduce(f.l,out.accepted);assert.equal(r.market_ready,true);assert.equal(r.physical_card_number,null);assert.ok(r.pokedex_number);assert.equal(r.printed_year,null);assert.equal(r.catalogue_release_year,'1999');assert.ok(out.accepted.every(e=>e.identifier_type==='pokedex'));assert.deepEqual(E.recoveryRequests(f.l,r),[]);});
test('215 actual Doncic front match plus original back number and titled release closes Green RC',()=>{const f=replay('doncic'),out=first(f),r=E.reduce(f.l,out.accepted);assert.equal(r.market_ready,true,JSON.stringify(out.rejected));assert.equal(r.physical_card_number,'280');assert.match(r.variant,/green/i);assert.equal(r.card_identity.is_rookie,true);assert.equal(out.accepted[0].field_proof.number.origin,'reference_text');assert.ok(out.rejected.some(x=>x.id==='lens-2'&&x.reasons.includes('unverified_image')));});
test('215 actual Boniface keeps serial 2/5 but cannot invent a matching parallel',()=>{const f=replay('boniface');E.applyDetails(f.l,f.details.updates,f.details.requested);const out=first(f),r=E.reduce(f.l,out.accepted);assert.equal(f.l.pick('serial').value,'2/5');assert.equal(out.accepted.length,0);assert.equal(r.market_ready,false);assert.ok(!out.rejected.some(x=>x.reasons.includes('different_number')));});
test('215 literal sports family may omit category suffix but cannot substitute another set',()=>{assert.equal(L.family214('2018 Panini Prizm Basketball','Panini','2018','2018 LUKA DONCIC PANINI PRIZM GREEN #280').value,'Panini Prizm');assert.equal(L.family214('2018 Panini Select Basketball','Panini','2018','2018 PANINI PRIZM #280').grounded,false);});
test('215 release year can abbreviate season start, never next season or season end',()=>{assert.equal(E.sportsSeason215('2018-19','2018'),true);assert.equal(E.sportsSeason215('2018-19','2019'),false);assert.equal(E.sportsSeason215('2018-19','2018-20'),false);});
test('215 strong appearance never bypasses conflicting number or explicit pattern conflict',()=>{for(const change of ['number','pattern']){const f=replay('doncic'),c=f.batches[0].reply.comparisons[0];if(change==='number')c.reference_reading.number='281';else c.conflicts=['Different Pulsar pattern'];const out=first(f);assert.equal(out.accepted.length,0);}});
test('215 missing original number and missing candidate number cannot close from colour and layout',()=>{const f=replay('doncic');f.batches[0].reply.comparisons[0].identity.number='';assert.equal(first(f).accepted.length,0);});
test('215 metadata promotes matching green card over silver and generic boxes before image download',()=>{const f=replay('doncic'),ordered=L.metadata215(f.references,f.l);assert.equal(ordered[0].id,'lens-1');assert.equal(ordered[0].metadataStrong,true);const b=replay('boniface');assert.equal(L.metadata215(b.references,b.l).some(r=>r.metadataStrong),false);});
