const {test}=require('node:test'),assert=require('node:assert/strict'),E=require('../src/main/assets/catalogue-engine'),L=require('../src/main/assets/lens-policy');
function ledger(){const l=new E.Ledger({domain:'pokemon',kind:'card'});for(const [f,v] of Object.entries({subject:'超梦V',collector_number:'135/127',language:'zh',copyright:'©2024'}))l.add(f,v,{source:'vision',certainty:'clear',image_index:1});return l;}
test('209 script names normalize and unknown explicit text does not erase valid language',()=>{for(const text of ['中文（简体字）','Cinese semplificato','simplified Chinese'])assert.equal(E.language(text),'zh-hans');assert.equal(E.language('Testo cinese'),'zh');const base={domain:'pokemon',language:'zh',observations:[{field:'language',text:'unrecognized script name',certainty:'clear',image_index:1}]},l=new E.Ledger(base);E.ingestVision(l,base);assert.equal(l.pick('language').value,'zh');});
test('209 equivalent Chinese descriptions agree while distinct scripts remain a conflict',()=>{const crop={id:'x',image_index:1,region:{image_index:1,x:.1,y:.1,width:.5,height:.5}},row={field:'language',crop_id:'x',image_index:1,evidence_found:true,certainty:'clear',full_text:'Cinese semplificato',crop_text:'Testo cinese'};const l=ledger();assert.equal(L.reconcileOriginal208(l,[row],[crop]).accepted.length,1);assert.equal(l.pick('language').value,'zh-hans');assert.equal(L.reconcileOriginal208(l,[{...row,crop_text:'Cinese tradizionale'}],[crop]).accepted.length,0);});
test('209 promo identifiers SWSH229 and SWSH 229 are parsed identically',()=>{assert.deepEqual(L.candidateFacts209('SWSH229 SWSH 229 CS5aC 135/127').codes,['SWSH229','CS5AC']);});
test('209 OCR number promotes candidate 16 without dropping candidates or modifying photo evidence',()=>{const l=ledger(),refs=Array.from({length:20},(_,i)=>({id:'lens-'+(i+1),title:'Mewtwo V SWSH229 English',ocr:{state:'ok',text:'SWSH229'}}));refs[15]={id:'lens-16',title:'Mewtwo V CS5a Brave',ocr:{state:'ok',text:'超梦V CS5aC 135/127 SR 2024'}};const before=l.atoms.length,out=L.rankOcr209(refs,l);assert.equal(out.length,20);assert.equal(out[0].id,'lens-16');assert.equal(l.atoms.length,before);});
test('209 unreadable and other-language images remain candidates',()=>{const out=L.rankOcr209([{id:'a',title:'Mewtwo V 135/127 English',ocr:{state:'ocr_unavailable'}},{id:'b',title:'Mewtwo Chinese',ocr:{text:''}}],ledger());assert.equal(out.length,2);assert.equal(out[0].id,'a');});
test('209 matching model code works for non-card objects',()=>{const l=new E.Ledger({domain:'generic'});l.add('model_code','RC-1234',{source:'vision',certainty:'clear',image_index:1});const out=L.rankOcr209([{id:'a',title:'Remote RC-5678'},{id:'b',title:'Remote',ocr:{text:'MODEL RC-1234'}}],l);assert.equal(out[0].id,'b');});

test('209 labelled local numbers keep exact catalogue pages ahead of unrelated full-art cards',()=>{const l=ledger();l.add('collector_number','9/12',{source:'lens_original_reread',certainty:'clear',image_index:1,supersedes:l.active('collector_number').map(a=>a.id)});const rows=[{id:'wrong',title:'Charizard #146 2024'},{id:'right',title:'Charizard Box Topper #9'}];assert.equal(L.rankOcr209(rows,l)[0].id,'right');});
