const {test}=require('node:test'),assert=require('node:assert/strict');
const E=require('../src/main/assets/catalogue-engine'),L=require('../src/main/assets/lens-policy');
function fixture(name){return structuredClone(require('./fixtures/lens-227-'+name+'.json'));}
function run(x){const l=E.ingestVision(new E.Ledger(x.vision),x.vision);x.references.forEach(r=>r.image_data='recorded');for(const b of x.batches)L.reconcileOriginal208(l,b.reply.original_readings,x.crops);const c=L.resolveComparisons217(l,x.batches,x.references);return {l,c,r:E.reduce(l,c.accepted)};}
test('227 recorded 226 Hill closes printed variant with independent geometry, serial stays unknown',()=>{const {r,l}=run(fixture('hill'));assert.equal(r.market_ready,true);assert.match(r.variant,/superfractor/i);assert.equal(r.physical_serial,null);assert.ok(l.pick('printing_name').corroborating_observation);});
test('227 recorded 226 Shaq revalidates candidate after number recovery and retains full product',()=>{const {r,l,c}=run(fixture('shaq'));assert.equal(r.market_ready,true);assert.equal(r.physical_card_number,'7');assert.equal(l.pick('product').value,'Flair Showcase');assert.equal(l.pick('collector_number').original_text,"7 Shaquille O'Neal");assert.ok(c.rejected.some(x=>x.id==='lens-1'));});
test('227 gold alone does not verify printed variant',()=>{const x=fixture('hill');x.vision.features=x.vision.features.filter(f=>f.field!=='pattern');assert.equal(run(x).r.market_ready,false);});
test('227 different number remains incompatible',()=>{const x=fixture('hill');x.vision.observations.find(o=>o.field==='collector_number').text='BCA-XYZ';assert.equal(run(x).r.market_ready,false);});
test('227 literal label alone and uncertain geometry cannot close',()=>{const x=fixture('hill');x.vision.features.find(f=>f.field==='pattern').certainty='uncertain';assert.equal(run(x).r.market_ready,false);});
test('227 another subject in compound number is rejected',()=>{const x=fixture('shaq');for(const b of x.batches)for(const row of b.reply.original_readings||[])if(row.field==='collector_number')row.full_text=row.crop_text='7 Another Person';const {l}=run(x);assert.equal(l.pick('collector_number'),null);});
test('227 actual front versus back mismatch stays rejected',()=>{const x=fixture('shaq');for(const b of x.batches)for(const c of b.reply.comparisons||[])c.reference_view='back';assert.equal(run(x).r.market_ready,false);});
test('227 descriptive geometry works without repeating commercial name',()=>{const x=fixture('hill');x.vision.features.find(f=>f.field==='pattern').value='Reticolo circolare metallico';assert.equal(run(x).r.market_ready,true);});
test('227 crop attribution mismatch stays rejected instead of silently moving evidence',()=>{const x=fixture('shaq'),l=E.ingestVision(new E.Ledger(x.vision),x.vision);const result=L.reconcileOriginal208(l,x.batches[0].reply.original_readings,x.crops);assert.ok(result.rejected.some(r=>r.field==='collector_number'&&r.reason==='original_views_not_confirmed'));assert.equal(l.pick('collector_number'),null);});
test('227 reported absence never replaces a read identifier',()=>{const {l}=run(fixture('shaq'));E.applyDetails(l,[{field:'collector_number',text:'assente',certainty:'clear',evidence_found:true,image_index:2}],[{field:'collector_number',image_index:2,key:'detail:test'}]);assert.equal(l.pick('collector_number').value,'7');assert.doesNotMatch(E.photoRequest(['collector_number'],'sports',{backAvailable:true}),/illeggibile/);});
