const {test}=require('node:test'),assert=require('node:assert/strict');
const E=require('../src/main/assets/catalogue-engine'),L=require('../src/main/assets/lens-policy');
function fixture(){return structuredClone(require('./fixtures/lens-228-hill.json'));}
function run(x){const l=E.ingestVision(new E.Ledger(x.vision),x.vision);x.references.forEach(r=>r.image_data='recorded');const c=L.resolveComparisons217(l,x.batches,x.references);return {l,c,r:E.reduce(l,c.accepted)};}
test('228 actual 227 Hill closes using the original back label recovered from comparison',()=>{const {r,l}=run(fixture());assert.equal(r.market_ready,true);assert.equal(r.variant,'SUPERFRACTOR');assert.equal(r.physical_serial,null);assert.equal(r.next_photo_request,null);assert.deepEqual(E.recoveryRequests(l,r),[]);assert.ok(l.pick('printing_name').derived_from);assert.equal(l.pick('pattern').source_value,'Dotted and concentric-line geometric foil pattern');});
test('228 source candidate remains core-only and never transfers Gold Refractor /25',()=>{const {r,c}=run(fixture());assert.ok(c.accepted.every(e=>e.core_only));assert.doesNotMatch(r.title,/Gold Refractor|\/25/);});
test('228 source-only label and appearance guess do not establish printed variant',()=>{for(const text of ['Candidate title identifies SUPERFRACTOR','Original back possibly identifies SUPERFRACTOR','Original back identifies SUPERFRACTOR-style']){const x=fixture();x.batches[0].reply.comparisons[0].conflicts[1]=text;const {r}=run(x);assert.equal(r.market_ready,false,text);}});
test('228 missing or uncertain pattern does not close from label alone',()=>{for(const uncertain of [true,false]){const x=fixture();if(uncertain)x.vision.features.find(f=>f.field==='pattern').certainty='uncertain';else x.vision.features=x.vision.features.filter(f=>f.field!=='pattern');assert.equal(run(x).r.market_ready,false);}});
test('228 missing original back cannot acquire a back label',()=>{const x=fixture();x.vision.image_views=x.vision.image_views.filter(v=>v.view!=='back');assert.equal(run(x).r.market_ready,false);});
test('228 autograph evidence is reusable even when source family omits autograph',()=>{const x=fixture();x.batches[0].reply.comparisons[0].conflicts.pop();const {r}=run(x);assert.ok(!r.variant_resolution.pending.includes('autograph'));assert.equal(r.market_ready,false);});
test('228 different collector number cannot be overridden by printed variant',()=>{const x=fixture();x.vision.observations.find(o=>o.field==='collector_number').text='BCA-XYZ';assert.equal(run(x).r.market_ready,false);});
test('228 structured printed variant keeps original two-view provenance',()=>{const x=fixture(),l=E.ingestVision(new E.Ledger(x.vision),x.vision),crop=x.crops.find(c=>c.image_index===2);L.reconcileOriginal208(l,[{field:'printed_variant',full_text:'SUPERFRACTOR',crop_text:'SUPERFRACTOR',image_index:2,crop_id:crop.id,evidence_found:true,certainty:'clear'}],x.crops);assert.equal(l.pick('printing_name').value,'SUPERFRACTOR');});
