const {test}=require('node:test'),assert=require('node:assert/strict'),E=require('../src/main/assets/catalogue-engine'),M=require('../src/main/assets/market-identity');
const hill=require('./fixtures/lens-232-hill.json'),poli=require('./fixtures/lens-232-politoed.json'),luffy=require('./fixtures/lens-232-luffy.json');
const ledger=x=>{const l=E.ingestVision(new E.Ledger(x.vision),x.vision);for(const p of x.phases){if(p.stage==='flipcheck_pokemon_identity_bands')E.applyIdentityBands202(l,p.result);if(p.stage==='flipcheck_evidence_detail')E.applyDetails(l,p.result.details,p.result.details.map(d=>({field:d.field,image_index:d.image_index,key:'recorded:'+d.field})));}return l;};
test('232 recorded Hill Bowman Chrome allows catalogue expansion on exact identity',()=>{const l=ledger(hill),r=E.reduce(l,hill.entries);assert.equal(r.market_ready,true,JSON.stringify(r.core_identity));assert.match(r.variant,/superfractor/i);assert.equal(r.physical_card_number,'BCA-AHJ');assert.equal(r.physical_serial,null);});
test('232 Bowman expansion cannot bypass another year, manufacturer or card number',()=>{for(const change of [{year:'2024'},{brand:'Panini'},{number:'84'}]){const r=E.reduce(ledger(hill),hill.entries.map(e=>({...e,...change})));assert.equal(r.market_ready,false);}});
test('232 Politoed catalogue alone cannot overwrite photo copyright',()=>{const l=ledger(poli);assert.equal(E.pokemonKeys204(l).year,'2001');assert.equal(E.reduce(l,poli.entries).market_ready,false);});
test('232 clear targeted reread supersedes erroneous copyright and preserves Italian',()=>{const l=ledger(poli),requests=['copyright','illustrator'].map(field=>({field,image_index:1,reason:'catalogue_discrepancy',key:'discrepancy:'+field}));E.applyDetails(l,[{field:'copyright',text:'© 2003 Pokémon / Nintendo',certainty:'clear',evidence_found:true,image_index:1},{field:'illustrator',text:'Atsuko Nishida',certainty:'clear',evidence_found:true,image_index:1}],requests);assert.equal(E.pokemonKeys204(l).year,'2003');assert.equal(l.pick('illustrator').value,'Atsuko Nishida');const r=E.reduce(l,poli.entries.map(e=>({...e,reference_core_only:true})));assert.equal(r.core_identity.status,'confirmed',JSON.stringify(r.core_identity));assert.equal(r.language,'it');assert.equal(r.card_identity.date,'2003');});
test('232 uncertain reread cannot replace copyright',()=>{const l=ledger(poli);E.applyDetails(l,[{field:'copyright',text:'2003',certainty:'uncertain',evidence_found:true,image_index:1}],[{field:'copyright',image_index:1,reason:'catalogue_discrepancy'}]);assert.equal(E.pokemonKeys204(l).year,'2001');});
const comparison=luffy.phases.find(p=>p.stage==='flipcheck_variant_comparison').result.comparisons[0],identity={...luffy.identification,market_identity:M.fromComparison(comparison,{id:'standard',image_url:'https://en.onepiece-cardgame.com/images/cardlist/card/P-110.png'})};
test('232 Luffy original no Winner marking binds standard market identity',()=>{assert.equal(identity.market_identity.edition,'standard');});
test('232 recorded incorrect Luffy Winner estimate is suppressed',()=>{const m=M.validate(luffy.phases.find(p=>p.stage==='flipcheck_market').result,identity);assert.equal(m.market_status,'insufficient');assert.equal(m.market_low,null);assert.equal(m.market_high,null);assert.equal(m.exact_completed_sales_count,0);});
const row={url:'https://example.com/sale/1',title:'P-110 Non Winner',quote:'P-110 non Winner sold for 12 USD',card_number:'P-110',language:'en',edition:'standard',price:12,currency:'USD',kind:'sold'};
test('232 proven individual standard sale can produce bounded estimate',()=>{const m=M.validate({currency:'USD',evaluated_edition:'standard',comparables:[row,row],market_low:400,market_high:700},identity);assert.equal(m.market_low,12);assert.equal(m.market_high,12);assert.equal(m.exact_completed_sales_count,1);});
test('232 mismatched edition, language, number, absent evidence and active offers cannot become sales',()=>{for(const change of [{edition:'winner'},{language:'ja'},{card_number:'P-111'},{quote:''},{title:'P-110 WINNER',quote:'Winner sold'},{kind:'active'},{price:NaN}]){const m=M.validate({currency:'USD',evaluated_edition:'standard',comparables:[{...row,...change}]},identity);assert.equal(m.market_low,null);assert.equal(m.exact_completed_sales_count,0);}});

test('232 reducer retains verified market edition with selected visual variant',()=>{const l=ledger(luffy);l.base.market_identity=identity.market_identity;l.add('catalogue_variant',luffy.entries[0].variants[0].id,{source:'variant_comparison',certainty:'clear',image_index:1});const r=E.reduce(l,luffy.entries);assert.equal(r.market_identity?.edition,'standard');});
