const {test}=require('node:test'),assert=require('node:assert/strict');
const E=require('../src/main/assets/catalogue-engine'),L=require('../src/main/assets/lens-policy');
function f(name){const x=structuredClone(require('./fixtures/lens-224-'+name+'.json'));x.l=E.ingestVision(new E.Ledger(x.vision),x.vision);x.references.forEach(r=>r.image_data='recorded_download');return x;}
function run(x){for(const b of x.batches)L.reconcileOriginal208(x.l,b.reply.original_readings,x.crops);const checked=L.resolveComparisons217(x.l,x.batches,x.references);return {checked,result:L.present206(E.reduce(x.l,checked.accepted),checked.accepted,x.l)};}
test('224 recorded alphabetic identifier survives initial and focused reads, closes with independently read printing',()=>{const x=f('hill'),{result:r}=run(x);assert.equal(r.market_ready,true);assert.equal(r.physical_card_number,'BCA-AHJ');assert.match(r.title,/BCA-AHJ/);assert.equal((r.title.match(/Bowman Chrome/g)||[]).length,1);assert.match(r.variant,/superfractor/i);assert.equal(r.variant_resolution.variant_origin,'original_photo');assert.deepEqual(E.recoveryRequests(x.l,r),[]);});
test('224 recorded Shaq normalizes printed season and closes with reference number separately attributed',()=>{const x=f('shaq'),{result:r,checked}=run(x);assert.equal(r.market_ready,true);assert.match(r.title,/1999-00.*Flair Showcase/);assert.equal(r.physical_card_number,null);assert.equal(r.source_confirmed_catalog_number,'7');assert.ok(checked.rejected.some(r=>r.id==='lens-1'&&r.reasons.includes('unverified_image')));});
test('224 alphabetic codes require delimited structure and compare exactly; serial parser remains numeric',()=>{for(const n of ['BCA-AHJ','ABC-XYZ','ABC-XYZ-AA'])assert.ok(E.numberParts(n));for(const n of ['AUTOGRAPH','First Edition','ABC-','8/102SR'])assert.equal(E.numberParts(n),null);assert.equal(E.numbersMatch('BCA-AHJ','BCA-ABC'),false);assert.equal(E.serial('BCA-AHJ'),null);assert.equal(E.numbersMatch('H23/H32','H23/H33'),false);});
test('224 century expansion requires contextual year, preserves rollover and rejects incompatible seasons',()=>{assert.equal(E.season('99-00','©2000 Publisher'),'1999-00');assert.equal(E.season('25/26','©2025 Publisher'),'2025-26');assert.equal(E.season('99-00'), '');assert.equal(E.season('99-00','2025'),'');assert.equal(E.sportsSeason215('1999-00','2000'),false);});
test('224 a missing original number schedules the existing rear image, not the front',()=>{const x=f('shaq'),req=E.recoveryRequests(x.l,E.reduce(x.l,[])).find(r=>r.field==='collector_number');assert.equal(req.image_index,2);assert.equal(req.region.image_index,2);E.applyDetails(x.l,[{field:'collector_number',text:'7',certainty:'clear',evidence_found:true,image_index:2}],[req]);assert.equal(x.l.pick('collector_number').value,'7');});
test('224 mismatched alphabetic code or subject cannot close a visually similar card',()=>{for(const field of ['number','subject']){const x=f('hill');for(const b of x.batches)for(const c of b.reply.comparisons)c.identity[field]=field==='number'?'BCA-XYZ':'Another Player';assert.equal(run(x).result.market_ready,false);}});
test('224 display phrases deduplicate normalized names, overlapping product and edition without losing distinct finish',()=>{assert.equal(E.title224(['Machamp Machamp','1st Edition Shadowless','First Edition','Shadowless']),'Machamp · 1st Edition Shadowless');assert.equal(E.title224(['Bowman Chrome Prospect Autograph Variation','Bowman Chrome']),'Bowman Chrome Prospect Autograph Variation');assert.equal(E.title224(['Mewtwo V','Mewtwo VMAX','Holo','Reverse Holo']),'Mewtwo V · Mewtwo VMAX · Holo · Reverse Holo');assert.equal(E.title224(['Base Set','Base Set 2']),'Base Set · Base Set 2');});
test('224 unrelated catalogue navigation cannot manufacture a named parallel',()=>{const x=f('shaq');for(const r of x.references)r.page_text+='\nOther products: Gold Red Blue Refractor';assert.equal(run(x).result.market_ready,true);});

test('224 candidate ranking recognizes labelled alphabetic codes before any web recovery',()=>{const x=f('hill'),rank=L.metadata215(x.references,x.l).find(r=>r.id==='lens-1');assert.equal(rank.metadataStrong,true);assert.ok(L.candidateFacts209('Anthony Hill Jr. #BCA-AHJ').labelled.includes('BCA-AHJ'));});
