/* Recorded responses from the three NEW build-221 exports. Modified replies below
   are synthetic robustness cases, never evidence of fresh model accuracy. */
const {test}=require('node:test'),assert=require('node:assert/strict');
const E=require('../src/main/assets/catalogue-engine'),L=require('../src/main/assets/lens-policy');
function fixture(name){const f=structuredClone(require('./fixtures/lens-222-'+name+'.json'));f.l=E.ingestVision(new E.Ledger(f.vision),f.vision);f.references.forEach(r=>r.image_data='recorded_download');return f;}
function run(f){for(const b of f.batches)L.reconcileOriginal208(f.l,b.reply.original_readings,f.crops);const checked=L.resolveComparisons217(f.l,f.batches,f.references),result=L.present206(E.reduce(f.l,checked.accepted),checked.accepted,f.l);return {checked,result};}
const comparisons=f=>f.batches.flatMap(b=>b.reply.comparisons);
const border=(text='absent')=>({field:'shadow',text,right_border:text,bottom_border:text,visual_reason:'Synthetic clear outer right and bottom illustration borders.',certainty:'clear',evidence_found:true,image_index:1});
test('222 recorded Topps closes Hobby, keeps the actual three-autograph and weak references rejected',()=>{const f=fixture('topps'),{checked,result:r}=run(f);assert.equal(r.market_ready,true);assert.match(r.title,/2025-26.*Topps Chrome Update Series.*Hobby Box/);assert.doesNotMatch(r.title,/Wembanyama|Flagg/);assert.deepEqual(checked.accepted.map(e=>e.visual_reference_id),['lens-19','lens-10']);assert.equal(r.next_photo_request,null);assert.equal(checked.accepted[0].normalization.original.subject,'');});
test('222 recorded Zagor closes the visible publication without a fabricated year or edition',()=>{const f=fixture('zagor'),{checked,result:r}=run(f);assert.equal(r.market_ready,true);assert.match(r.title,/Zagor.*CEPIM.*verde/i);assert.doesNotMatch(r.title,/1977|1st|prima edizione/i);assert.equal(r.subject.toLowerCase(),'zagor');assert.equal(r.publisher,'CEPIM');assert.equal(f.l.pick('model_code'),null);assert.deepEqual(checked.accepted.map(e=>e.visual_reference_id),['lens-6']);assert.ok(checked.rejected.some(e=>e.id==='lens-1'));});
test('222 publication name survives when every reference is unavailable',()=>{const f=fixture('zagor');f.batches=[];const r=run(f).result;assert.match(r.title,/Zagor/);assert.equal(r.market_ready,false);assert.equal(r.work_title,'Zagor');});
test('222 publisher may be absent in the listing title but must occur in paired image evidence',()=>{const f=fixture('zagor');const ref=f.references.find(r=>r.id==='lens-6');ref.title='Fumetto Zagor lo spirito con la scure';ref.snippet='';ref.page_text='';assert.equal(run(f).result.market_ready,true);const c=comparisons(f).find(c=>c.reference_id==='lens-6');c.features=c.features.map(v=>({...v,reference:v.reference.replace(/edizioni CEPIM/g,'different publisher')}));assert.equal(run(f).result.market_ready,false);});
test('222 publisher aliases retain verbatim text and origin',()=>{const f=fixture('zagor');f.l.add('publisher','CEPIM',{source:'focused_vision',certainty:'clear',image_index:1});f.l.add('publisher','edizioni CEPIM',{source:'vision',certainty:'clear',image_index:1});assert.ok(f.l.pick('publisher'));assert.equal(f.l.atoms.at(-1).original_text,'edizioni CEPIM');assert.equal(f.l.atoms.at(-1).normalized_value,'cepim');assert.equal(f.l.atoms.at(-1).source,'vision');});
test('222 real model-code contradiction remains a rejection for books',()=>{const f=fixture('zagor');f.l.add('model_code','OTHER-432',{source:'vision',certainty:'clear',image_index:1});assert.equal(run(f).result.market_ready,false);});
test('222 generic rules survive entirely different work and publisher names',()=>{let f=fixture('zagor');const raw=JSON.stringify({...f,l:undefined}).replace(/Zagor/gi,'Orion').replace(/CEPIM/g,'NOVA');f=JSON.parse(raw);f.l=E.ingestVision(new E.Ledger(f.vision),f.vision);const r=run(f).result;assert.equal(r.market_ready,true);assert.match(r.title,/Orion.*NOVA/i);});
test('222 configuration disagreement overrides a falsely positive match flag',()=>{const f=fixture('topps');for(const c of comparisons(f)){if(!['lens-19','lens-10'].includes(c.reference_id))continue;c.features.find(x=>x.field==='configuration').reference='3 autographs in every box';}const {checked,result:r}=run(f);assert.equal(r.market_ready,false);assert.ok(checked.rejected.some(r=>r.reasons.includes('different_configuration')));});
test('222 product, season and publisher contradictions cannot borrow a matching package',()=>{for(const field of ['family','year','brand']){const f=fixture('topps');for(const c of comparisons(f))c.identity[field]=({family:'Topps Chrome Black',year:'2024-25',brand:'Other Brand'})[field];assert.equal(run(f).result.market_ready,false,field);}});
test('222 missing original year is missing evidence, not a year conflict',()=>{const f=fixture('topps');for(const c of comparisons(f))c.original_reading.year='';const {checked,result:r}=run(f);assert.equal(r.market_ready,true);assert.ok(!checked.rejected.some(r=>r.reasons.includes('different_original_year')));});
test('222 recorded Machamp retains Base Set core but requires original shadow verification',()=>{const f=fixture('machamp'),{checked,result:r}=run(f);assert.equal(r.core_identity.status,'confirmed');assert.equal(r.family,'Base Set');assert.equal(r.market_ready,false);assert.deepEqual(r.variant_resolution.pending,['shadow']);assert.equal(r.printing_check.shadow,'unclear');assert.ok(checked.accepted.some(e=>e.visual_reference_id==='lens-43'&&e.claimed_printing==='1st Edition Shadowless'));assert.doesNotMatch(r.title,/Shadowless/);assert.ok(!checked.rejected.some(r=>r.reasons.some(v=>/year/.test(v))));assert.equal(r.printed_year,'1999');assert.equal(r.card_identity.subset,undefined);});
test('222 synthetic focused border verification closes once; no duplicate edition or printing subset',()=>{const f=fixture('machamp'),{checked,result:r}=run(f),req=E.recoveryRequests(f.l,r).map(q=>({...q,reason:'shadow_border_verification'}));E.applyDetails(f.l,[border()],req);const out=L.present206(E.reduce(f.l,checked.accepted),checked.accepted,f.l);assert.equal(out.market_ready,true);assert.equal((out.title.match(/1st Edition/g)||[]).length,1);assert.equal((out.title.match(/Shadowless/g)||[]).length,1);assert.equal(out.card_identity.subset,undefined);assert.deepEqual(E.recoveryRequests(f.l,out),[]);});
test('222 prior sufficient physical shadow evidence is reused without another recovery',()=>{const f=fixture('machamp');f.l.add('shadow','absent',{source:'focused_vision',certainty:'clear',image_index:1,raw:'Both outer illustration borders visibly have no printed shadow'});const {result:r}=run(f);assert.equal(r.market_ready,true);assert.deepEqual(E.recoveryRequests(f.l,r),[]);});
test('222 missing or disagreeing border detail cannot promote the online Shadowless claim',()=>{for(const detail of [{...border(),right_border:undefined},{...border(),bottom_border:'present'},{...border(),certainty:'uncertain',evidence_found:false}]){const f=fixture('machamp'),{checked,result:r}=run(f),req=E.recoveryRequests(f.l,r).map(q=>({...q,reason:'shadow_border_verification'}));E.applyDetails(f.l,[detail],req);assert.equal(E.reduce(f.l,checked.accepted).market_ready,false);}});
test('222 explicit incompatible single printing years remain rejected',()=>{const f=fixture('machamp');for(const c of comparisons(f))c.original_reading.year='2001';assert.equal(run(f).result.market_ready,false);assert.ok(run(f).checked.rejected.some(r=>r.reasons.includes('different_original_year')));});
test('222 missing photograph number is not relabelled as an incompatible number',()=>{const f=fixture('machamp');for(const c of comparisons(f))c.original_reading.number='';const {checked}=run(f);assert.ok(!checked.rejected.some(r=>r.reasons.includes('different_original_number')));assert.ok(checked.accepted.length);});
test('222 Base alias scope is context-bound and keeps non-Base sets independent',()=>{const f=fixture('machamp');for(const family of ['Base Set','Base Pokémon Card','Pokémon Base Set','Set Base'])assert.equal(E.printingScope(f.l,{family,year:'1999'}).shadow,true);for(const family of ['Base Set 2','Scarlet Violet Base Set','Jungle'])assert.equal(E.printingScope(f.l,{family,year:'1999'}).shadow,false);assert.equal(E.canonicalSet222('Base Pokémon Card','sports'),'Base Pokémon Card');});
