/* Recorded build-222 replies; synthetic additions are labelled and do not prove live accuracy. */
const {test}=require('node:test'),assert=require('node:assert/strict');
const E=require('../src/main/assets/catalogue-engine'),L=require('../src/main/assets/lens-policy'),S=require('../src/main/assets/slab-identity');
function fixture(name){const f=structuredClone(require('./fixtures/lens-223-'+name+'.json'));f.l=E.ingestVision(new E.Ledger(f.vision),f.vision);f.references.forEach(r=>r.image_data='replayed_download');return f;}
function run(f){for(const b of f.batches)L.reconcileOriginal208(f.l,b.reply.original_readings,f.crops);const checked=L.resolveComparisons217(f.l,f.batches,f.references);return {checked,result:L.present206(E.reduce(f.l,checked.accepted),checked.accepted,f.l)};}
const spatial=text=>({field:'shadow',text,certainty:'clear',evidence_found:true,image_index:1,right_border:text,bottom_border:text,visual_reason:'Synthetic spatial evidence',illustration_bounds:{x:.1,y:.13,width:.8,height:.42},right_transition:text==='present'?'frame_shadow_background':'frame_background',bottom_transition:text==='present'?'frame_shadow_background':'frame_background',right_description:'Synthetic right transition',bottom_description:'Synthetic bottom transition'});
test('223 recorded Goku closes P7 after normalizing adjacent name text, retaining manufacturer/product/series',()=>{const f=fixture('goku'),{result:r,checked}=run(f);assert.equal(r.market_ready,true);assert.match(r.title,/Goku.*P7.*Lamincards Dragon Ball Z.*Serie Platino.*Edibas.*ITA/);assert.doesNotMatch(r.title,/1989|2007/);assert.equal(checked.accepted[0].visual_reference_id,'lens-1');assert.ok(checked.rejected.some(r=>r.id==='lens-2'&&r.reasons.includes('unverified_image')));assert.ok(checked.rejected.some(r=>r.id==='lens-3'&&r.reasons.includes('different_number')));assert.ok(f.l.atoms.some(a=>/Supersayan/.test(a.original_text)));});
test('223 adjacent-text normalization applies to unrelated names; actual conflicting subject stays unresolved',()=>{const base={domain:'tcg',kind:'card',observations:[{field:'subject',text:'Orion',certainty:'clear',image_index:1},{field:'text',text:'Ascended',certainty:'clear',image_index:1}]};const l=E.ingestVision(new E.Ledger(base),base);l.add('subject','Orion™ Ascended',{source:'focused_vision',certainty:'clear',image_index:1});assert.equal(l.pick('subject').value,'Orion');l.add('subject','Other Hero',{source:'focused_vision',certainty:'clear',image_index:1});assert.equal(l.pick('subject'),null);assert.equal(E.subjectMatch('Mewtwo V','Mewtwo VMAX'),false);});
test('223 missing Goku reference number cannot borrow the original number',()=>{const f=fixture('goku');for(const b of f.batches)for(const c of b.reply.comparisons)c.reference_reading.number='';assert.equal(run(f).result.market_ready,false);});
test('223 recorded Vileplume keeps core and requests only stamp, without treating a symbol description as code/subset',()=>{const f=fixture('vileplume'),{result:r}=run(f);assert.equal(r.core_identity.status,'confirmed');assert.equal(r.market_ready,false);assert.deepEqual(r.variant_resolution.pending,['stamp']);assert.doesNotMatch(r.title,/Jungle symbol|No Symbol/i);assert.equal(f.l.pick('set_code'),null);assert.ok(f.l.pick('set_symbol'));assert.deepEqual(E.recoveryRequests(f.l,r).map(r=>r.field),['stamp']);});
test('223 synthetic stamp presence or absence closes Vileplume without inventing edition',()=>{for(const value of ['present','absent']){const f=fixture('vileplume'),{checked,result}=run(f);E.applyDetails(f.l,[{field:'stamp',text:value,certainty:'clear',evidence_found:true,image_index:1}],E.recoveryRequests(f.l,result));const r=E.reduce(f.l,checked.accepted);assert.equal(r.market_ready,true);assert.match(r.title,value==='present'?/1st Edition/:/Unlimited/);}});
test('223 recorded incorrect Machamp response cannot satisfy the new spatial verification contract',()=>{const f=fixture('machamp'),{checked,result}=run(f);const req=E.recoveryRequests(f.l,result).map(r=>({...r,reason:'shadow_border_verification',spatial_verification:true}));E.applyDetails(f.l,f.details.flat(),req);assert.equal(E.reduce(f.l,checked.accepted).market_ready,false);assert.ok(f.l.events.some(e=>e.reason==='unverified_spatial_transition'));});
test('223 synthetic spatial evidence accepts either physical printing, rejects inconsistent transition',()=>{for(const text of ['present','absent']){const f=fixture('machamp'),{checked,result}=run(f),req=E.recoveryRequests(f.l,result).map(r=>({...r,reason:'shadow_border_verification',spatial_verification:true}));E.applyDetails(f.l,[spatial(text)],req);assert.equal(E.reduce(f.l,checked.accepted).market_ready,true);}const f=fixture('machamp'),{checked,result}=run(f);E.applyDetails(f.l,[{...spatial('present'),bottom_transition:'frame_background'}],E.recoveryRequests(f.l,result).map(r=>({...r,reason:'shadow_border_verification',spatial_verification:true})));assert.equal(E.reduce(f.l,checked.accepted).market_ready,false);});
test('223 recorded Mewtwo retains slab set code despite uncertain card-footer reading; guessed grader omitted',()=>{const f=fixture('mewtwo'),facts=S.labelFacts(f.vision),r=S.close(f.vision,facts);assert.equal(r.market_ready,true);assert.match(r.title,/CS5aC.*135\/127.*Mewtwo V.*CHN/);assert.doesNotMatch(r.title,/ARS/);assert.equal(facts.reported_grader,'ARS');assert.equal(facts.grader_verified,false);assert.equal(r.grading.subgrades.length,4);assert.equal(facts.set_code_origin,'photo_slab_label');assert.equal(r.core_identity.fields.find(f=>f.field==='language').origin,'original_photo');});
test('223 explicit grader mark supports certificate routing while an uncertain logo does not',()=>{const f=fixture('mewtwo');Object.assign(f.vision.slab_reading,{grader:'BGS',grader_mark:'BGS',grader_certainty:'clear'});assert.equal(S.certificatePlan(S.labelFacts(f.vision)).state,'ready');f.vision.slab_reading.grader_certainty='uncertain';assert.notEqual(S.certificatePlan(S.labelFacts(f.vision)).state,'ready');});
