const {test}=require('node:test'),assert=require('node:assert/strict'),E=require('../src/main/assets/catalogue-engine'),L=require('../src/main/assets/lens-policy');
function replay(name){const f=structuredClone(require('./fixtures/lens-213-'+name+'.json')),l=new E.Ledger(f.vision);E.ingestVision(l,f.vision);for(const r of f.references)r.image_data='downloaded';return {...f,l};}
test('213 front selection follows observed side when uploads are reversed',()=>{const f=replay('boniface'),p=L.frontPlan213(f.vision,2);assert.equal(p.image_index,1);assert.ok(p.region);for(const group of ['observations','features','object_regions'])for(const o of f.vision[group])o.image_index=3-o.image_index;assert.equal(L.frontPlan213(f.vision,2).image_index,2);});
test('213 serial accepts literal one of one and preserves unknown specimen',()=>{assert.deepEqual(E.serial('ONE OF ONE'),{value:'1/1',specimen:1,print_run:1});assert.deepEqual(E.serial('/5'),{value:'/5',specimen:null,print_run:5});assert.equal(E.serial('6/5'),null);assert.equal(E.serial('one of the best'),null);});
test('213 recorded Mewtwo keeps illustration support without transferring foreign number or language',()=>{const f=replay('mewtwo'),b=f.batches[0];L.reconcileOriginal208(f.l,b.reply.original_readings,f.crops);const out=L.visualEntries206(b.reply,f.references,f.l);assert.equal(out.accepted.length,0);assert.ok(out.support.length);assert.ok(out.support.every(s=>s.identity_proof===false));assert.equal(f.l.pick('collector_number').value,'135/127');assert.equal(E.reduce(f.l,out.accepted).market_ready,false);});
test('213 recorded Luffy retains physical stamp support despite an unsupported subset title',()=>{const f=replay('luffy'),b=f.batches[1],out=L.visualEntries206(b.reply,f.references,f.l);const s=out.support.find(s=>s.reference_id==='lens-6');assert.ok(s.features.some(f=>f.original.includes('4th Anniversary')&&f.reference.includes('4th Anniversary')));assert.ok(out.accepted.some(e=>e.visual_reference_id==='lens-6'));});
test('213 two recorded Doncic references with same variant do not cancel their evidence',()=>{const f=replay('doncic'),b=f.batches[0],out=L.visualEntries206(b.reply,f.references,f.l),r=E.reduce(f.l,out.accepted);assert.equal(out.accepted.length,2);assert.equal(r.core_identity.status,'confirmed');assert.equal(r.market_ready,true);assert.equal(r.physical_card_number,null);assert.equal(r.source_confirmed_catalog_number,'280');});
test('213 Boniface wrong references never override observed set number',()=>{const f=replay('boniface');for(const b of f.batches){const out=L.visualEntries206(b.reply,f.references,f.l);assert.equal(out.accepted.length,0);}assert.equal(f.l.pick('collector_number').value,'21');});
test('213 Charizard recorded complete comparison still closes',()=>{const f=replay('charizard');let entries=[];for(const b of f.batches){L.reconcileOriginal208(f.l,b.reply.original_readings,f.crops);entries.push(...L.visualEntries206(b.reply,f.references,f.l).accepted);}assert.equal(E.reduce(f.l,entries).market_ready,true);});
