const {test}=require('node:test'),assert=require('node:assert/strict'),E=require('../src/main/assets/catalogue-engine'),L=require('../src/main/assets/lens-policy');
function replay(name){const x=structuredClone(require('./fixtures/lens-230-'+name+'.json')),l=E.ingestVision(new E.Ledger(x.vision),x.vision);x.references.forEach(r=>r.image_data='recorded');for(const b of x.batches)L.reconcileOriginal208(l,b.reply.original_readings,x.crops);const resolved=L.resolveComparisons217(l,x.batches,x.references);return {x,l,resolved,r:L.present206(E.reduce(l,resolved.accepted),resolved.accepted,l)};}
test('230 live229 Hill model_code is a physical card identifier and closes',()=>{const {l,r}=replay('hill');assert.equal(l.pick('collector_number').value,'BCA-AHJ');assert.equal(r.market_ready,true);assert.match(r.variant,/superfractor/i);assert.match(r.title,/Auto/);assert.equal(l.active('text').filter(a=>/SUPERFRACTOR/.test(a.value)).length,1);assert.ok(l.active('text').some(a=>a.value==='AUTOGRAPH VARIATION'));});
test('230 conflicting focused reread cannot replace agreed original number',()=>{const {l,x}=replay('hill');const q=x.details.requested;E.applyDetails(l,x.details.updates,q);assert.equal(l.pick('collector_number').value,'BCA-AHJ');assert.ok(l.events.some(e=>e.stage==='conflicting_detail'));});
test('230 observed variant survives unresolved catalogue without claiming exact identity',()=>{const {l}=replay('hill'),r=L.present206(E.reduce(l,[]),[],l);assert.equal(r.market_ready,false);assert.match(r.observed_variant.value,/superfractor/i);});
test('230 live229 Doncic closes and printing is not a subset',()=>{const {r}=replay('doncic');assert.equal(r.market_ready,true);assert.equal(r.physical_card_number,'280');assert.equal(r.card_identity.subset,null);assert.match(r.variant,/green/i);});
test('230 live229 panel preserves separate names and does not hunt absent number',()=>{const {l,r,x}=replay('panel');assert.equal(x.lens_state,'quota_exhausted');assert.match(E.keyValues(l).subject,/ & /);assert.equal(E.recoveryRequests(l,r).some(q=>q.field==='collector_number'),false);assert.equal(r.market_ready,false);assert.match(E.query(l),/panel image/);});
test('230 real incompatible Hill reference is still rejected',()=>{const {resolved}=replay('hill');assert.ok(resolved.rejected.some(r=>r.id==='lens-20'));});
test('230 panel unknown year is optional when actual recorded text/art/layout agree',()=>{const x=structuredClone(require('./fixtures/lens-221-panel.json')),l=E.ingestVision(new E.Ledger(x.vision),x.vision);x.references.forEach(r=>{r.image_data='recorded';r.title=r.title.replace(/1958/g,'');r.page_text='';});for(const b of x.batches){L.reconcileOriginal208(l,b.reply.original_readings,x.crops);for(const c of b.reply.comparisons){c.identity.year='';c.identity.proof.year='';}}const c=L.resolveComparisons217(l,x.batches,x.references),r=E.reduce(l,c.accepted);assert.equal(r.market_ready,true);assert.equal(r.source_confirmed_year,null);});
test('230 panel fallback excludes unrelated modern checklists',()=>{const {l}=replay('panel'),C=require('../src/main/assets/catalogue-sources');assert.equal(C.relevantSource230({title:'2019 Topps Chrome baseball checklist',url:'https://example.com/checklist.pdf'},l),false);assert.equal(C.relevantSource230({title:'Manoel Francisco Santos vintage panel',url:'https://example.com/card'},l),true);});
