const {test}=require('node:test'),assert=require('node:assert/strict'),E=require('../src/main/assets/catalogue-engine'),L=require('../src/main/assets/lens-policy'),S=require('../src/main/assets/slab-identity'),I=require('../src/main/assets/image-evidence');
function replay(name){const f=structuredClone(require('./fixtures/lens-212-'+name+'.json')),l=new E.Ledger(f.vision);E.ingestVision(l,f.vision);for(const r of f.references)r.image_data='downloaded';return {...f,l};}
test('212 recorded BGS long grader and Expedition label close without losing label number',()=>{const f=replay('bgs'),facts=S.labelFacts(f.vision);assert.equal(facts.grader,'BGS');assert.equal(facts.family,'Expedition');assert.equal(facts.card_number,'8');assert.equal(S.close(f.vision,facts,{state:'unavailable'}).market_ready,true);});
test('212 recorded Italian description confirms Green variant from English source',()=>{const f=replay('doncic'),b=f.batches[0],out=L.visualEntries206(b.reply,f.references,f.l),r=E.reduce(f.l,out.accepted);assert.equal(r.market_ready,true,JSON.stringify(r));assert.equal(r.physical_card_number,null);assert.equal(r.source_confirmed_catalog_number,'280');});
test('212 equivalent promotional family does not reopen confirmed code identity',()=>{const f=replay('luffy'),r=E.reduce(f.l,f.entries);assert.equal(r.core_identity.status,'confirmed');assert.equal(r.market_ready,false,'two official artworks remain to compare');});
test('212 sports copyright and season use compatible roles without merging unrelated years',()=>{assert.equal(L.yearReading212('2025','2025-26'),true);assert.equal(L.yearReading212('2026','2025-26'),true);assert.equal(L.yearReading212('2024','2025-26'),false);});
test('212 team or affiliation cannot overwrite a subject',()=>{const f=replay('doncic');for(const b of f.batches)L.reconcileOriginal208(f.l,b.reply.original_readings,f.crops);assert.equal(f.l.pick('subject').value,'LUKA DONCIC');});
function objectFixture(){const l=new E.Ledger({domain:'generic',kind:'object'});l.add('model_code','RC-1234',{source:'vision',certainty:'clear',image_index:2});const ref={id:'r',image_data:'bytes',url:'https://example.com/remote',title:'Acme RC-1234 Remote',snippet:''};const c={reference_id:'r',match:true,ambiguous:false,title_matches_image:true,conflicts:[],original_reading:{},reference_reading:{},features:[{field:'shape',original:'oval remote',reference:'oval remote',agrees:true,certainty:'clear'},{field:'identifier',original:'RC-1234',reference:'RC-1234',agrees:true,certainty:'clear'}],identity:{subject:'RC-1234',family:'Acme',number:'RC-1234',year:'',subset:'',brand:'Acme'}};return {l,ref,c};}
test('212 non-card object closes with model evidence and corresponding image details',()=>{const f=objectFixture(),out=L.visualEntries206({comparisons:[f.c]},[f.ref],f.l);assert.equal(out.accepted.length,1,JSON.stringify(out.rejected));assert.equal(E.reduce(f.l,out.accepted).market_ready,true);});
test('212 similar enclosure or contradictory code does not identify an object',()=>{for(const mode of ['shape','code','view']){const f=objectFixture();if(mode==='shape')f.c.features=f.c.features.slice(0,1);if(mode==='code')f.ref.title='Acme RC-9999 Remote';if(mode==='view'){f.c.original_view='back';f.c.reference_view='front';}assert.equal(L.visualEntries206({comparisons:[f.c]},[f.ref],f.l).accepted.length,0);}});
test('212 local appearance measures green without declaring silver or foil',()=>{const p={width:100,height:100,data:new Uint8ClampedArray(40000)},q=[{x:0,y:0},{x:1,y:0},{x:1,y:1},{x:0,y:1}];for(let i=0;i<p.data.length;i+=4){p.data[i]=30;p.data[i+1]=170;p.data[i+2]=50;p.data[i+3]=255;}const a=I.surface212(p,q);assert.equal(a.frame_color,'green');assert.equal(a.foil,'undetermined');assert.equal(I.compareSurface212(a,a).frame_color_agrees,true);assert.equal(I.surface212(p,null).state,'unclear');p.data.fill(255);assert.equal(I.surface212(p,q).state,'unclear');});
