/* Frozen 203 diagnostics + deterministic IO mocks. No new photo recognition or paid calls. */
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),zlib=require('zlib'),path=require('path'),vm=require('vm');
const E=require('../src/main/assets/catalogue-engine'),C=require('../src/main/assets/catalogue-sources');
const D=JSON.parse(zlib.gunzipSync(fs.readFileSync(path.join(__dirname,'fixtures/diagnostics-203-pokemon.json.gz'))));
const runtime=fs.readFileSync(path.join(__dirname,'../src/main/assets/catalogue-runtime.js'),'utf8');
function replay(i){const d=D[i],l=E.ingestVision(new E.Ledger(d.vision),d.vision);E.ingestOcr(l,d.photoOcr);E.applyIdentityBands202(l,d.bands);const entries=[...d.candidates,...C.records(d.pages,l),...d.phases.flatMap(p=>C.pokemonLeadEntries204(p.result,d.pages,l))];return {d,l,entries};}
function specimen(extra={}){const l=new E.Ledger({domain:'pokemon',kind:'card'});for(const [field,value] of Object.entries({subject:'Example V',collector_number:'007/099',copyright:'©2024 Pokémon',language:'it',finish:'holo',...extra}))l.add(field,value,{certainty:'clear',image_index:1});return l;}
function entry(extra={}){return {subject:'Example V',number:'7/099',family:'Example Set',year:'2024',language:'it',variants:[{name:'Holo',finish:'holo'}],grounded:true,source:{url:'https://api.tcgdex.net/v2/it/cards/example-7'},...extra};}
function proof(l,e){l.add('catalogue_core',E.coreKey(e),{certainty:'clear',image_index:1,source:'catalogue_image_comparison',reference_source:e.source.url});}
function sandbox(extra={}){const s={E193:E,C193:C,URLSearchParams,Date,JSON,Math,Object,Map,Set,string193:{type:'string'},strings193:{type:'array'},object193:properties=>({type:'object',properties}),enum193:values=>({type:'string',enum:values}),schemaFormat:()=>({}),entrySchema193:{},estimate164:()=>.003,addUsage(){},guard164(){},status(){},saveEvidence192(){},diagnosticPhases:[],...extra};vm.createContext(s);return s;}
test('all four clear photo keys bind every candidate, including after visual comparison',()=>{
 const l=specimen(),good=entry();assert.equal(E.reduce(l,[good]).market_ready,true);
 for(const change of [{subject:'Example'},{number:'7/100'},{year:'2023'},{language:'en'}]){const bad=entry(change);proof(l,bad);const r=E.reduce(l,[bad]);assert.equal(r.market_ready,false,JSON.stringify(change));assert.deepEqual([r.identity_keys.subject.value,r.identity_keys.number.value,r.identity_keys.date.value,r.language],['Example V','007/099','2024','it']);assert.ok(l.candidates[0].reasons.length);}
});
test('clear keys outrank secondary catalogue HP, illustrator, attacks and product hints',()=>{
 const l=specimen({illustrator:'Artist A',hp:'100',attack:'Attack A',product:'Unreliable set hint'}),e=entry({illustrator:'Artist B',hp:200,attacks:['Attack B'],attacks_language:'it'}),r=E.reduce(l,[e]);assert.equal(r.market_ready,true);assert.equal(r.family,'Example Set');assert.deepEqual(l.candidates[0].nonblocking_differences.sort(),['different_attacks','different_hp','different_illustrator','different_printed_product']);assert.equal(r.core_identity.fields.find(f=>f.field==='year').origin,'photo');assert.equal(r.core_identity.fields.find(f=>f.field==='family').origin,'catalogue');
});
test('clear collector fraction takes precedence over the species number in every query',()=>{const l=specimen();l.add('pokedex_number','129',{certainty:'clear',image_index:1});assert.deepEqual(E.pokemonNumbers203(l),['007/099']);assert.match(E.query(l,'reference',entry({subject:'Wrong Name',number:'8',year:'2020'})),/"007\/099" 2024/);assert.doesNotMatch(E.query(l),/129/);assert.doesNotMatch(E.query(l,'reference',entry({subject:'Wrong Name'})),/Wrong Name/);});
test('year and language provenance cannot be replaced by reference metadata',()=>{const l=specimen(),r=E.reduce(l,[entry({year:'2023',printing_year:'2024'})]);assert.equal(r.market_ready,true);assert.equal(r.printed_year,'2024');assert.equal(r.source_confirmed_year,'2024');assert.equal(r.catalogue_release_year,'2023');assert.equal(r.language_origin,'original_photo');});
test('203 Mewtwo reuses the exact PriceCharting card and attributed large image; suffix and fraction survive',()=>{
 const {d,l}=replay(0),entries=C.records(d.pages,l),e=entries.find(e=>e.image_url);assert.ok(e);assert.equal(e.family,'CS5aC');assert.match(e.image_url,/1600\.jpg$/);assert.equal(E.reduce(l,entries).market_ready,false);assert.deepEqual(E.pokemonAliases204(l),['Mewtwo V']);assert.match(E.query(l),/Mewtwo V/);
 proof(l,e);const r=E.reduce(l,entries);assert.equal(r.market_ready,true);assert.equal(r.card_identity.subject,'超梦V');assert.equal(r.physical_card_number,'135/127');assert.equal(r.printed_year,'2024');assert.equal(r.source_confirmed_year,null);assert.equal(r.language,'zh');assert.equal(r.variant,'Holo');
});
test('203 Mewtwo production comparison consumes its downloaded page without another search',async()=>{
 const {d,l}=replay(0),entries=C.records(d.pages,l),calls=[],downloads=[];
 const s=sandbox({lastVisionReading:l.base,directCall165:async(action,payload)=>{assert.equal(action,'image');downloads.push(payload.url);return {status:200,image_data:'offline-reference'};},visualPhoto164:async()=>({data:'offline-original',meta:{imageIndex:1}}),originalOpenai26:async body=>{calls.push(body);return {comparisons:[{reference_id:'core0',reference_subject:'Mewtwo V',reference_number:'135',match:true,ambiguous:false,conflicts:[],features:[{field:'artwork',original:'pose',reference:'pose',certainty:'clear',agrees:true},{field:'text',original:'same printing',reference:'same printing',certainty:'clear',agrees:true}]}]};},parseResponseJSON:x=>x});
 vm.runInContext(runtime.slice(runtime.indexOf('async function compareCore193('),runtime.indexOf('async function compareVariants193('))+'\nthis.compare=compareCore193;',s);await s.compare(l,entries,{budget:{spent:()=>.01833,maxUsd:.03}},d.pages);
 assert.equal(calls.length,1);assert.equal(calls[0].tools,undefined);assert.equal(downloads.length,1);assert.match(downloads[0],/1600\.jpg$/);assert.equal(E.reduce(l,entries).market_ready,true);
});
test('203 Charizard No.006 reaches structured lookup and web; an unrelated catalogue cannot demand a number reread',()=>{
 const {l,entries}=replay(1),r=E.reduce(l,entries);assert.deepEqual(C.requestPlan(l)[0].numbers,['006']);assert.match(E.query(l,'reference'),/リザードン "006"/);assert.equal(E.number(r.pokedex_number),'006');assert.equal(r.physical_card_number,null);assert.equal(r.market_ready,false);assert.deepEqual(E.recoveryRequests(l,r).map(q=>q.field),['copyright']);
});
test('203 Dragonite cannot promote uncertain number/year or an English reference into Italian exact identity',()=>{
 const {l,entries}=replay(2),r=E.reduce(l,entries);assert.equal(r.market_ready,false);assert.equal(r.physical_card_number,null);assert.equal(r.printed_year,null);assert.equal(r.source_confirmed_year,null);assert.equal(r.language,'it');assert.deepEqual(E.recoveryRequests(l,r).map(q=>q.field),['collector_number','copyright']);assert.ok(l.candidates.some(e=>e.reasons.includes('different_printing_language')));
});
test('203 Glurak retains a grounded discovery lead and all clear photo keys without declaring it verified',()=>{
 const {l,entries}=replay(4),g=E.candidateGroups(l,entries).find(g=>g.entry.source_tier==='discovery_lead');assert.ok(g);assert.equal(g.entry.number,'9/12');assert.equal(g.entry.requires_image_confirmation,true);assert.equal(E.sourceTrusted(g.entry.source.url,'pokemon'),false);assert.equal(E.reduce(l,entries).market_ready,false);assert.equal(E.recoveryRequests(l,E.reduce(l,entries)).some(q=>q.field==='collector_number'),false);
 const invented={entries:[{...g.entry,source_url:g.entry.source.url,entry_quote:'Invented passage'}]};assert.deepEqual(C.pokemonLeadEntries204(invented,D[4].pages,l),[]);
});
test('203 Vileplume and Magikarp keep their recorded correct closures and physical rarity symbols',()=>{
 for(const i of [3,5]){const {d,l,entries}=replay(i);for(const p of d.phases.filter(p=>p.stage==='flipcheck_evidence_detail'))E.applyDetails(l,p.result.details,E.recoveryRequests(l,E.reduce(l,entries)));for(const a of d.observations.filter(a=>a.source==='local_frame_measurement'))l.add(a.field,a.value,{...a,id:undefined});const r=E.reduce(l,entries);assert.equal(r.market_ready,true,d.label);assert.equal(r.printed_year,'1999');assert.equal(r.language,'en');assert.equal(r.card_identity.rarity_symbol,'present');assert.match(r.variant,/1st Edition/);}
});
test('band presence values accept literal symbols and preserve uncertain readings',()=>{
 for(const [field,value] of [['rarity_symbol','star'],['rarity_symbol','diamond'],['rarity_symbol','stella nera'],['stamp','First Edition']]){const l=specimen();E.applyIdentityBands202(l,{features:[{field,value,certainty:'clear',image_index:1,region:{image_index:1,x:.1,y:.8,width:.1,height:.1},description:value}]});assert.equal(l.pick(field).value,'present');assert.equal(l.pick(field).raw,value);}
 const l=specimen();E.applyIdentityBands202(l,{features:[{field:'rarity_symbol',value:'star',certainty:'uncertain',image_index:1,region:{image_index:1,x:.1,y:.8,width:.1,height:.1}}]});assert.equal(l.pick('rarity_symbol'),null);
});
test('a generic reflective observation does not conflict with a clear holo band; opposite finishes still conflict',()=>{const l=specimen();l.add('finish','reflective',{certainty:'clear',image_index:1});assert.equal(l.pick('finish').value,'holo');l.add('finish','normal',{certainty:'clear',image_index:1});assert.equal(l.pick('finish'),null);});
test('structured lookup reads later pages instead of silently losing the exact number',async()=>{
 const l=specimen(),requests=[];const s=sandbox({directCall165:async(action,p)=>{requests.push(p.url);if(p.url.includes('/cards?'))return {status:200,body:p.url.includes('pagination%3Apage=2')?[{id:'test-7',localId:'7',name:'Example V'}]:Array.from({length:100},(_,i)=>({id:'other-'+i,localId:String(i+100),name:'Example V'}))};if(p.url.includes('/cards/'))return {status:200,body:{id:'test-7',localId:'7',name:'Example V',set:{id:'test',name:'Example Set',cardCount:{official:'099'}},variants:{holo:true}}};return {status:200,body:{releaseDate:'2024-01-01'}};}});
 vm.runInContext(runtime.slice(runtime.indexOf('async function catalogueLookup193('),runtime.indexOf('const variantSchema193='))+'\nthis.lookup=catalogueLookup193;',s);const ctx={},r=await s.lookup(l,ctx);assert.equal(r.entries.length,1);assert.equal(E.reduce(l,r.entries).market_ready,true);assert.ok(requests.some(q=>q.includes('pagination%3Apage=2')));assert.equal(ctx.catalogueCoverage.truncated,false);assert.equal(requests.some(q=>q.includes('/cards/other-')),false);
});

test('panel coordinates map deterministically onto the original photo; malformed panels cannot produce evidence',()=>{const plans=E.pokemonPanels202({object_regions:[{image_index:1,x:.1,y:.2,width:.8,height:.6}]}),packet={observations:[{field:'copyright',text:'©2024',certainty:'clear',image_index:1,panel_role:'lower',region:{image_index:1,x:.25,y:.5,width:.5,height:.25}}]},mapped=E.mapPokemonBands204(packet,plans),r=mapped.observations[0].region;assert.ok(Math.abs(r.x-.3)<1e-10);assert.ok(Math.abs(r.y-.71)<1e-10);assert.ok(Math.abs(r.width-.4)<1e-10);assert.ok(Math.abs(r.height-.045)<1e-10);assert.equal(packet.observations[0].region.y,.5);const invalid=E.mapPokemonBands204({observations:[{...packet.observations[0],panel_role:'invalid'}]},plans);assert.equal(invalid.observations[0].region,null);});

test('a provisional discovery source cannot certify its own lead with its own image',()=>{const {l,entries}=replay(4),lead=entries.find(e=>e.source_tier==='discovery_lead');assert.ok(lead);proof(l,lead);assert.equal(E.reduce(l,[lead]).market_ready,false);assert.equal(E.reduce(l,[lead]).core_identity.status,'partial');const verified={...lead,source_tier:'secondary_product',source:{url:'https://www.psacard.com/cert/example/psa'},variants:[{name:'Holo',finish:'holo'}]};proof(l,verified);assert.equal(E.reduce(l,[lead,verified]).market_ready,true);});
