const {test}=require('node:test'),assert=require('node:assert/strict'),P=require('../src/main/assets/price-summary'),X=require('../src/main/assets/ximilar-policy'),E=require('../src/main/assets/catalogue-engine');
const snorlax={name:'Snorlax',set:'Jungle',card_number:'11',out_of:'64',year:1999,price_stats:[{stats_type:'graded',interval:'overall',value:{median:249.99,mean:2295.35,max:139999.99}},{stats_type:'overall',interval:'overall',value:{median:191}},{stats_type:'ungraded',interval:'overall',value:{q1:39.99,q3:79.99,median:59.99,volume:25,latest_date:'2026-08-15'}}]};
function entries(m=snorlax){return X.normalize({records:[{_status:{code:200},_objects:[{name:'Card',_identification:{best_match:m}}]}]},'pokemon').entries;}
const identity={kind:'card',market_ready:true,core_identity:{status:'confirmed'},card_identity:{subject:'Snorlax',set:'Jungle',number:'11/64',date:'1999'}};
test('235 actual supplied Snorlax stats use raw median and never graded outliers',()=>{const m=P.model(identity,{},entries());assert.equal(m.stat.median,59.99);assert.equal(m.stat.q1,39.99);assert.equal(m.stat.q3,79.99);assert.equal(m.stat.currency,null);const html=P.html(m);assert.match(html,/59,99/);assert.match(html,/Valuta non indicata/);assert.doesNotMatch(html,/249,99|139999|2.295|€|\$/);assert.ok(m.rows.every(r=>r.value===null));});
test('235 slab PSA 8 never inherits raw or undifferentiated graded median',()=>{const m=P.model({...identity,grading:{company:'PSA',grade:'8'}},{},entries());assert.equal(m.label,'PSA · Voto 8');assert.equal(m.stat,null);assert.equal(m.state,'grade_data_missing');assert.doesNotMatch(P.html(m),/59,99|249,99/);});
test('235 unknown slab cannot silently become raw',()=>{assert.equal(P.model(identity,{slab_reading:{present:true}},entries()).stat,null);});
test('235 prices do not cross subject, set, number or year',()=>{for(const change of [{subject:'Politoed'},{set:'Base Set'},{number:'27/64'},{date:'2003'}])assert.equal(P.model({...identity,card_identity:{...identity.card_identity,...change}},{},entries()).stat,null);});
test('235 pending core hides price and pending printing qualifies it',()=>{assert.equal(P.model({...identity,core_identity:{status:'partial'}},{},entries()).stat,null);assert.equal(P.model({...identity,market_ready:false},{},entries()).state,'printing_pending');});
test('235 explicit source currency is preserved without UI currency conversion',()=>{const m=P.model(identity,{},entries({...snorlax,currency:'USD'}));assert.equal(m.stat.currency,'USD');assert.doesNotMatch(P.html(m),/€|Valuta non indicata/);});
test('235 malformed, missing, duplicate and alternative prices cannot become primary quote',()=>{for(const stats of [[],[{stats_type:'overall',interval:'overall',value:{median:12}}],[{stats_type:'ungraded',interval:'overall',value:{median:null}}],[{stats_type:'ungraded',interval:'overall',value:{median:'59.99'}}]])assert.equal(P.model(identity,{},entries({...snorlax,price_stats:stats})).stat,null);assert.equal(P.model(identity,{},entries().map(e=>({...e,provider_rank:1}))).stat,null);});
test('235 price text is escaped and provider cannot inject HTML',()=>{const m=P.model({...identity,grading:{company:'<img onerror=alert(1)>',grade:'8'}},{},entries());assert.doesNotMatch(P.html(m),/<img/);});
test('235 sports provider subset preserved and no invented variant blocks concordant physical number',()=>{const v={domain:'sports',kind:'card',observations:[['subject','Kobe Bryant'],['product','SP Authentic'],['subset','First Class'],['collector_number','FC7']].map(([field,text])=>({field,text,certainty:'clear',image_index:1}))},l=E.ingestVision(new E.Ledger(v),v),e={subject:'Kobe Bryant',family:'SP Authentic',number:'FC7',year:'2000',subset:'First Class',subset_known:true,grounded:true,provider_rank:0,source_tier:'recognition_api',source:{provider:'ximilar',url:'https://api.ximilar.com/collectibles/v2/sport_id'},variants:[]};const r=E.reduce(l,[e]);assert.equal(r.market_ready,true);assert.equal(r.card_identity.subset,'First Class');l.add('serial','2/5',{source:'vision',certainty:'clear',image_index:1});assert.equal(E.reduce(l,[e]).market_ready,false);});
