package com.flipcheck.nativebeta;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

/** The only v1.32 writer of public identity state. Invoked exactly once per run. */
final class FinalStateReducerV2 {
    static final String VERSION="UniversalIdentityEngineV2.FinalStateReducer/1";
    private FinalStateReducerV2() {}

    static FinalIdentityState reduce(Models.Identification id,ImmutableEvidenceLedgerV2 ledger,
                                     DomainProfileRouterV2.Profile profile,List<IdentityCandidateV2> ranked,
                                     List<ConflictResolverV2.Conflict> conflicts,String technicalFailure){
        id.finalStateReducerVersion=VERSION;id.v2Profile=DomainProfileRouterV2.categoryKey(profile);
        id.categoryKey=id.v2Profile;id.category=humanCategory(profile);id.categoryStatus="CONFIRMED";id.categoryConfidence=Math.max(75,id.categoryConfidence);
        IdentityCandidateV2 winner=winner(ranked);hydrateFromLedgerAndCandidate(id,ledger,profile,winner);
        boolean hardConflict=affectsCore(conflicts);boolean technical=!safe(technicalFailure).isEmpty();
        boolean core=coreComplete(id,ledger,profile,winner)&&!hardConflict&&!technical;
        boolean exactPhysical=exactPhysical(id,ledger,profile);boolean catalog=winner!=null&&winner.retrieved&&!winner.rejected&&winner.disproofPassed&&winner.webSourceQuality>=65;

        id.familyStatus=family(id).isEmpty()?"UNRESOLVED":catalog?"CATALOG_MATCHED":"CONFIRMED";
        id.coreIdentityStatus=technical?"UNRESOLVED":core?"CONFIRMED":partialCore(id,profile)?"PROBABLE":"UNRESOLVED";
        id.exactIdentityStatus=profile==DomainProfileRouterV2.Profile.TCG_CARD||profile==DomainProfileRouterV2.Profile.SPORTS_CARD
                ?catalog?"CATALOG_MATCHED":exactPhysical?"PHYSICALLY_VERIFIED":"TO_VERIFY"
                :profile==DomainProfileRouterV2.Profile.SEALED_TRADING_CARD_PRODUCT
                ?empty(id.sealedFormat)?"FORMAT_PENDING":catalog?"CATALOG_MATCHED":"PHYSICALLY_VERIFIED"
                :DomainProfileRouterV2.electronics(profile)
                ?empty(id.model)?"MODEL_TO_VERIFY":catalog?"CATALOG_MATCHED":"PHYSICALLY_VERIFIED"
                :catalog?"CATALOG_MATCHED":core?"PHYSICALLY_VERIFIED":"TO_VERIFY";
        id.identifierStatus=identifierStatus(id,ledger,profile,catalog);id.collectorNumberStatus=id.identifierStatus;id.cardNumberVerificationStatus=id.identifierStatus;id.collectorNumberVerificationStatus=id.identifierStatus;
        id.exactCatalogStatus=catalog?"CATALOG_MATCHED":"NOT_AVAILABLE";id.catalogVerified=catalog;id.disproofStatus=catalog?"PASSED":winner==null?"NOT_EXECUTED":"UNRESOLVED";
        id.webContributionScore=winner==null?0:winner.webSourceQuality;id.catalogCompatibilityStatus=catalog?"MATCHED":winner==null?"NOT_EVALUATED":"UNRESOLVED";id.catalogMatchedFields=winner==null?"":joinList(winner.matchedEvidence);
        id.exactEditionStatus=profile==DomainProfileRouterV2.Profile.TCG_CARD?((ledger.hasObserved("edition")||ledger.hasObserved("firstEditionMark"))?"CONFIRMED":"TO_VERIFY"):"NOT_APPLICABLE";
        id.finishStatus=(profile==DomainProfileRouterV2.Profile.TCG_CARD||profile==DomainProfileRouterV2.Profile.SPORTS_CARD)?(ledger.hasObserved("finish")?"CONFIRMED":"TO_VERIFY"):"NOT_APPLICABLE";
        id.variantStatus=variantStatus(id,profile);id.formatStatus=profile==DomainProfileRouterV2.Profile.SEALED_TRADING_CARD_PRODUCT?(empty(id.sealedFormat)?"FORMAT_PENDING":"CONFIRMED"):"NOT_APPLICABLE";
        id.commercialFormatStatus=profile==DomainProfileRouterV2.Profile.SEALED_TRADING_CARD_PRODUCT?(empty(id.sealedFormat)?"TO_VERIFY":"CONFIRMED"):"NOT_APPLICABLE";
        id.skuStatus=profile==DomainProfileRouterV2.Profile.SEALED_TRADING_CARD_PRODUCT?(empty(id.sourceConfirmedProductCode)?"TO_VERIFY":"CONFIRMED"):"NOT_APPLICABLE";
        id.exactModelStatus=DomainProfileRouterV2.electronics(profile)?(empty(id.model)?"TO_VERIFY":"CONFIRMED"):"NOT_APPLICABLE";
        id.copyIdentifierStatus=empty(id.physicalSerial)?"NOT_OBSERVED":"PHYSICALLY_VERIFIED";
        id.identityConfirmed=core;id.closureResult=core;id.closureAttempt=true;id.closureLevel=catalog?"CATALOG_IDENTITY":exactPhysical?"EXACT_PHYSICAL_IDENTITY":core?"CORE_IDENTITY":"CATEGORY";id.closureStage="final_state_reducer_v2";
        if(technical){id.identityStatus="TECHNICAL_FAILURE";id.overallStatus="TECHNICAL_FAILURE";id.decision="TECHNICAL_FAILURE";id.pipelineFailureDomain=technicalFailure;}
        else if(hardConflict){id.identityStatus="CONFLICTED";id.overallStatus="CONFLICTED";id.decision="CONFLICTED";}
        else if(core){boolean pending=attributePending(id,profile);id.identityStatus=pending?"CONFIRMED_WITH_ATTRIBUTE_PENDING":"CONFIRMED";id.overallStatus=id.identityStatus;id.decision=id.identityStatus;}
        else if(photoRequestApplicable(id,profile)){id.identityStatus="NEEDS_SPECIFIC_PHOTO";id.overallStatus="NEEDS_SPECIFIC_PHOTO";id.decision=id.identityStatus;}
        else {id.identityStatus="UNRESOLVED";id.overallStatus="UNRESOLVED";id.decision=id.identityStatus;}
        id.hierarchicalStatus=id.overallStatus;id.blockingReason=hardConflict?"documented_core_conflict":"";
        id.marketStatus=marketStatus(id,profile);id.marketReady=core&&!marketIdentityPending(id,profile);id.priceAvailable=false;id.marketDecisionStatus=id.marketStatus;id.priceSummary="Prezzo non calcolato: risoluzione identità separata dai comparabili";id.comparablesSummary="Comparabili non richiesti durante l’identificazione";
        id.title=title(id,profile);id.confirmedBrand=id.brand;id.confirmedFamily=family(id);id.confirmedModel=id.model;id.mainIdentityConfidence=confidence(ledger,winner,core);id.coreIdentityConfidence=id.mainIdentityConfidence;id.exactIdentityConfidence=exactPhysical||catalog?Math.min(99,id.mainIdentityConfidence):Math.min(75,id.mainIdentityConfidence);id.modelConfidence=id.exactIdentityConfidence;
        id.identifierConfidence=observedConfidence(ledger,profile==DomainProfileRouterV2.Profile.TCG_CARD?"collectorNumber":"physicalCardNumber");id.familyConfidence=observedConfidence(ledger,profile==DomainProfileRouterV2.Profile.TCG_CARD?"setName":"productLine");id.variantConfidence=Math.max(observedConfidence(ledger,"edition"),observedConfidence(ledger,"finish"));
        id.verificationSummary=summary(id,profile,catalog,exactPhysical);id.finalDecisionReason="reducer="+VERSION+"; profile="+id.v2Profile+"; core="+id.coreIdentityStatus+"; exact="+id.exactIdentityStatus+"; catalog="+id.exactCatalogStatus+"; conflicts="+(conflicts==null?0:conflicts.size());
        applyPhotoRequest(id,profile,core);serializeTrace(id,ledger,ranked,conflicts);enforceBlockingInvariants(id,ledger,profile,conflicts);
        id.finalState=new FinalIdentityState(id,id.title,id.identityConfirmed&&!"CONFLICTED".equals(id.identityStatus));return id.finalState;
    }

    private static void hydrateFromLedgerAndCandidate(Models.Identification id,ImmutableEvidenceLedgerV2 l,DomainProfileRouterV2.Profile p,IdentityCandidateV2 c){
        id.game=observed(l,"game");id.observedBrand=observed(l,"manufacturer","brand");if(p==DomainProfileRouterV2.Profile.TCG_CARD&&empty(id.observedBrand))id.observedBrand=id.game;id.inferredBrand=inferred(l,"manufacturer","brand","game");id.catalogBrand=c==null?"":first(c.value("manufacturer"),c.value("brand"));id.brand=first(id.observedBrand,id.catalogBrand,id.inferredBrand);id.brandStatus=!id.observedBrand.isEmpty()?"CONFIRMED":!id.catalogBrand.isEmpty()?"STRONGLY_SUPPORTED":!id.inferredBrand.isEmpty()?"HYPOTHESIS":"UNRESOLVED";
        String familyField=p==DomainProfileRouterV2.Profile.TCG_CARD?"setName":"productLine";id.family=observed(l,familyField);if(empty(id.family)&&c!=null)id.family=first(c.value(familyField),c.value("productLine"));if(empty(id.family))id.family=inferred(l,familyField);
        String subjectField=p==DomainProfileRouterV2.Profile.TCG_CARD?"cardName":p==DomainProfileRouterV2.Profile.SPORTS_CARD?"athlete":"model";String subject=observed(l,subjectField);if(empty(subject)&&c!=null)subject=c.value(subjectField);if(empty(subject))subject=inferred(l,subjectField);id.model=subject;
        id.physicalReleaseYear=observed(l,"productReleaseYear");id.statisticsSeason=value(l,"statisticsSeason");String year=id.physicalReleaseYear;if(c!=null&&empty(year))year=c.value("productReleaseYear");id.sourceConfirmedReleaseYear=c==null?"":c.value("productReleaseYear");
        String physicalField=p==DomainProfileRouterV2.Profile.TCG_CARD?"collectorNumber":"physicalCardNumber";String physicalNumber=observed(l,physicalField);id.physicalCardNumber=physicalNumber;if(p==DomainProfileRouterV2.Profile.TCG_CARD)id.physicalCollectorNumber=physicalNumber;id.cardNumberCandidate=physicalNumber;id.collectorNumberCandidate=p==DomainProfileRouterV2.Profile.TCG_CARD?physicalNumber:"";id.physicalCardNumberOrigin=observedSource(l,physicalField);id.cardNumberVerified=!physicalNumber.isEmpty();id.collectorNumberVerified=p==DomainProfileRouterV2.Profile.TCG_CARD&&!physicalNumber.isEmpty();
        String catalogNumber=c==null?"":c.value("catalogCardNumber");id.sourceConfirmedCatalogNumber=catalogNumber;id.sourceConfirmedCatalogNumberOrigin=empty(catalogNumber)?"":"WEB_CATALOG";id.numberAgreement=!empty(physicalNumber)&&!empty(catalogNumber)&&TypedFieldNormalizerV2.equivalent(p==DomainProfileRouterV2.Profile.TCG_CARD?"collectorNumber":"physicalCardNumber",physicalNumber,catalogNumber);id.combinedVerification=id.numberAgreement?"PHOTO_PLUS_CATALOG":!empty(physicalNumber)?"PHOTO_ONLY":!empty(catalogNumber)?"CATALOG_ONLY":"NONE";
        id.edition=observed(l,"edition");String editionMark=observed(l,"firstEditionMark");if(empty(id.edition)&&"PRESENT".equals(editionMark))id.edition="FIRST_EDITION";if(empty(id.edition)&&c!=null)id.edition=c.value("edition");id.firstEditionMark="FIRST_EDITION".equals(id.edition)||"PRESENT".equals(editionMark)?"PRESENT":editionMark;id.firstEditionSource="PRESENT".equals(id.firstEditionMark)&&!editionMark.isEmpty()?"PHOTO_FRONT":"";
        id.finish=observed(l,"finish");if(empty(id.finish)&&c!=null)id.finish=c.value("finish");id.language=first(observed(l,"language"),c==null?"":c.value("language"));id.hpOrPv=observed(l,"hp");id.attackNames=values(l,"attacks");id.copyrightYear=observed(l,"copyrightYear");id.productType=first(observed(l,"productType"),c==null?"":c.value("productType"));id.productConfiguration=first(observed(l,"configuration"),c==null?"":c.value("configuration"));id.sealedFormat=first(observed(l,"commercialFormat"),c==null?"":c.value("commercialFormat"));id.physicalSerial=observed(l,"physicalSerial");id.physicalSerialOrigin=observedSource(l,"physicalSerial");id.graphicNumber=observed(l,"graphicNumber");
        id.sourceConfirmedProductLine=c==null?"":first(c.value("productLine"),c.value("setName"));id.sourceConfirmedFormat=c==null?"":c.value("commercialFormat");id.sourceConfirmedProductCode=c==null?"":first(c.value("productCode"),c.value("sku"),c.value("barcode"));id.sourceCatalogTitle=c==null?"":c.display();id.searchQuery=id.webQueries.isEmpty()?"":id.webQueries.get(id.webQueries.size()-1);id.title=join(year,id.brand,id.family,subject,physicalNumber.isEmpty()?"":"#"+physicalNumber);
    }

    private static void enforceBlockingInvariants(Models.Identification id,ImmutableEvidenceLedgerV2 l,DomainProfileRouterV2.Profile p,List<ConflictResolverV2.Conflict> conflicts){List<String>errors=id.consistencyInvariantErrors;errors.clear();
        if(id.closureResult&&"UNRESOLVED".equals(id.coreIdentityStatus))errors.add("FAIL:closure_core_state_conflict");
        if("CONFLICTED".equals(id.identityStatus)&&(conflicts==null||conflicts.isEmpty()))errors.add("FAIL:conflict_without_two_evidenced_values");
        if("CONFIRMED".equals(id.exactEditionStatus)&&empty(id.edition))errors.add("FAIL:edition_confirmed_but_missing");
        if(p==DomainProfileRouterV2.Profile.SEALED_TRADING_CARD_PRODUCT&&safe(id.missingDiscriminativeFields).contains("card"))errors.add("FAIL:sealed_product_requires_card_number");
        if("PHOTO_PLUS_CATALOG".equals(id.combinedVerification)&&(!l.hasObserved(p==DomainProfileRouterV2.Profile.TCG_CARD?"collectorNumber":"physicalCardNumber")||empty(id.sourceConfirmedCatalogNumber)))errors.add("FAIL:false_photo_plus_catalog");
        if(!id.observedBrand.isEmpty()&&!l.hasObserved("manufacturer")&&!l.hasObserved("brand")&&!l.hasObserved("game"))errors.add("FAIL:observed_brand_without_region");
        if(!id.nextPhotoRequest.isEmpty()&&empty(id.requestedPhotoReason))errors.add("FAIL:photo_request_without_reason");
        if("CONFIRMED".equals(id.categoryStatus)&&id.categoryConfidence==0)errors.add("FAIL:confirmed_category_zero_confidence");
        if(!errors.isEmpty()){id.consistencyInvariants="REPAIRED";id.fieldTransitions.add("FinalStateReducerV2 safe fallback applied: "+errors);if(errors.contains("FAIL:photo_request_without_reason")){id.nextPhotoRequest="";id.requestedPhotoReason="";}if(errors.contains("FAIL:conflict_without_two_evidenced_values")){id.identityStatus=id.identityConfirmed?"CONFIRMED_WITH_ATTRIBUTE_PENDING":"UNRESOLVED";id.overallStatus=id.identityStatus;}if(errors.contains("FAIL:false_photo_plus_catalog"))id.combinedVerification=l.hasObserved(p==DomainProfileRouterV2.Profile.TCG_CARD?"collectorNumber":"physicalCardNumber")?"PHOTO_ONLY":"CATALOG_ONLY";}
        else id.consistencyInvariants="PASS";id.postWebInvariants=id.consistencyInvariants;id.preWebInvariants="PASS";}

    private static IdentityCandidateV2 winner(List<IdentityCandidateV2> ranked){if(ranked==null)return null;for(IdentityCandidateV2 c:ranked)if(!c.rejected&&c.retrieved&&c.disproofPassed&&c.totalScore>=48)return c;return null;}
    private static boolean coreComplete(Models.Identification id,ImmutableEvidenceLedgerV2 l,DomainProfileRouterV2.Profile p,IdentityCandidateV2 c){if(p==DomainProfileRouterV2.Profile.TCG_CARD)return !empty(id.model)&&!empty(id.family)&&!empty(id.physicalCollectorNumber);if(p==DomainProfileRouterV2.Profile.SPORTS_CARD)return !empty(id.model)&&!empty(id.family)&&!empty(id.physicalCardNumber)&&!empty(first(id.physicalReleaseYear,id.sourceConfirmedReleaseYear));if(p==DomainProfileRouterV2.Profile.SEALED_TRADING_CARD_PRODUCT)return !empty(id.brand)&&!empty(id.family)&&!empty(first(id.physicalReleaseYear,id.sourceConfirmedReleaseYear));if(p==DomainProfileRouterV2.Profile.TELEVISION_REMOTE_CONTROL)return !empty(id.brand)&&observedDesign(l)&&(c!=null||!empty(id.observedBrand));if(DomainProfileRouterV2.electronics(p))return !empty(id.brand)&&(!empty(id.model)||!empty(value(l,"barcode")));return c!=null||observedDesign(l);}
    private static boolean exactPhysical(Models.Identification id,ImmutableEvidenceLedgerV2 l,DomainProfileRouterV2.Profile p){if(p==DomainProfileRouterV2.Profile.TCG_CARD)return l.hasObserved("cardName")&&l.hasObserved("collectorNumber")&&(l.hasObserved("setName")||l.hasObserved("productLine"));if(p==DomainProfileRouterV2.Profile.SPORTS_CARD)return l.hasObserved("athlete")&&l.hasObserved("physicalCardNumber")&&l.hasObserved("productLine");return l.hasObserved("model")||l.hasObserved("barcode");}
    private static boolean partialCore(Models.Identification id,DomainProfileRouterV2.Profile p){return !empty(id.brand)||!empty(id.family)||!empty(id.model);}
    private static boolean attributePending(Models.Identification id,DomainProfileRouterV2.Profile p){if(p==DomainProfileRouterV2.Profile.SEALED_TRADING_CARD_PRODUCT)return empty(id.sealedFormat)||empty(id.sourceConfirmedProductCode);if(DomainProfileRouterV2.electronics(p))return empty(id.model);return "TO_VERIFY".equals(id.variantStatus)||"TO_VERIFY".equals(id.finishStatus)||"TO_VERIFY".equals(id.exactEditionStatus);}
    private static boolean marketIdentityPending(Models.Identification id,DomainProfileRouterV2.Profile p){return p==DomainProfileRouterV2.Profile.SEALED_TRADING_CARD_PRODUCT&&(empty(id.sealedFormat)||empty(id.sourceConfirmedProductCode))||DomainProfileRouterV2.electronics(p)&&empty(id.model);}
    private static String marketStatus(Models.Identification id,DomainProfileRouterV2.Profile p){return marketIdentityPending(id,p)?"IDENTITY_OR_SKU_PENDING":"NOT_RUN";}
    private static String identifierStatus(Models.Identification id,ImmutableEvidenceLedgerV2 l,DomainProfileRouterV2.Profile p,boolean catalog){String f=p==DomainProfileRouterV2.Profile.TCG_CARD?"collectorNumber":"physicalCardNumber";if(l.hasObserved(f))return catalog&&id.numberAgreement?"PHOTO_PLUS_CATALOG":"PHYSICALLY_VERIFIED";return catalog?"CATALOG_MATCHED":"NOT_OBSERVED";}
    private static String variantStatus(Models.Identification id,DomainProfileRouterV2.Profile p){if(p==DomainProfileRouterV2.Profile.SEALED_TRADING_CARD_PRODUCT)return empty(id.sealedFormat)?"TO_VERIFY":"CONFIRMED";if(p==DomainProfileRouterV2.Profile.TCG_CARD||p==DomainProfileRouterV2.Profile.SPORTS_CARD)return empty(id.edition)&&empty(id.finish)?"TO_VERIFY":"CONFIRMED";return empty(id.model)?"TO_VERIFY":"CONFIRMED";}
    private static boolean photoRequestApplicable(Models.Identification id,DomainProfileRouterV2.Profile p){return DomainProfileRouterV2.electronics(p)||!empty(id.missingDiscriminativeFields);}
    private static void applyPhotoRequest(Models.Identification id,DomainProfileRouterV2.Profile p,boolean core){id.nextPhotoRequest="";id.nextPhotoReason="";id.requestedPhotoReason="";if(p==DomainProfileRouterV2.Profile.TELEVISION_REMOTE_CONTROL&&empty(id.model)){id.requestedPhotoMissingField="exactModel";id.requestedPhotoSide="back";id.requestedPhotoRegion="entire_rear_label";id.requestedPhotoExpectedEvidence="model_or_part_code";id.requestedPhotoReason="rear_label_or_model_code";id.nextPhotoReason=id.requestedPhotoReason;id.nextPhotoRequest="Fotografa il retro includendo l’intera etichetta e qualsiasi codice modello o sigla del telecomando.";}else if(!core&&!empty(id.missingDiscriminativeFields)){id.requestedPhotoMissingField=id.missingDiscriminativeFields;id.requestedPhotoSide="identity_bearing_side";id.requestedPhotoRegion="missing_discriminator";id.requestedPhotoExpectedEvidence=id.missingDiscriminativeFields;id.requestedPhotoReason="required_core_discriminator_not_visible";id.nextPhotoReason=id.requestedPhotoReason;id.nextPhotoRequest="Fotografa da vicino la zona che contiene "+id.missingDiscriminativeFields+" mantenendo visibile l’oggetto intero.";}}
    private static boolean affectsCore(List<ConflictResolverV2.Conflict> conflicts){if(conflicts==null)return false;for(ConflictResolverV2.Conflict c:conflicts)if("CORE_IDENTITY".equals(c.affectedIdentityLevel)&&"CRITICAL".equals(c.severity))return true;return false;}
    private static void serializeTrace(Models.Identification id,ImmutableEvidenceLedgerV2 l,List<IdentityCandidateV2>ranked,List<ConflictResolverV2.Conflict>conflicts){StringBuilder o=new StringBuilder(),i=new StringBuilder(),r=new StringBuilder();id.evidenceAtomsV2.clear();id.evidenceAtomsV2.addAll(l.all());for(EvidenceAtom a:l.all()){String x=a.id+":"+a.field+"="+a.normalizedValue+"@"+a.source+(a.boundingBox.isEmpty()?"":"["+a.boundingBox+"]");if(a.epistemicLevel==EvidenceAtom.EpistemicLevel.OBSERVED)append(o,x);else if(a.epistemicLevel==EvidenceAtom.EpistemicLevel.INFERRED)append(i,x);else append(r,x);}id.v2ObservedFacts=o.toString();id.v2InferredFacts=i.toString();id.v2RetrievedFacts=r.toString();StringBuilder cs=new StringBuilder();if(ranked!=null)for(IdentityCandidateV2 c:ranked)append(cs,c.candidateId+"="+c.display()+" score="+c.totalScore+" rejected="+c.rejected+" conflicts="+c.trueConflicts);id.v2CandidateTrace=cs.toString();StringBuilder cf=new StringBuilder();if(conflicts!=null)for(ConflictResolverV2.Conflict c:conflicts)append(cf,c.field+":"+c.valueA+c.evidenceIdsA+" vs "+c.valueB+c.evidenceIdsB);id.v2TrueConflicts=cf.toString();id.numberConflicts=cf.toString();}
    private static int confidence(ImmutableEvidenceLedgerV2 ledger,IdentityCandidateV2 c,boolean core){int physical=0;for(EvidenceAtom a:ledger.all())if(a.epistemicLevel==EvidenceAtom.EpistemicLevel.OBSERVED&&a.localized())physical=Math.max(physical,a.confidence);int score=c==null?0:c.totalScore;return core?Math.max(82,Math.min(99,(physical*2+score)/3)):Math.min(79,Math.max(physical,score));}
    private static String summary(Models.Identification id,DomainProfileRouterV2.Profile p,boolean catalog,boolean physical){return "Identità ridotta una sola volta da prove "+(physical?"fotografiche localizzate":"disponibili")+(catalog?" e fonte catalografica con disproof superato":"")+"; gli attributi secondari restano separati.";}
    private static String title(Models.Identification id,DomainProfileRouterV2.Profile p){String year=first(id.physicalReleaseYear,id.sourceConfirmedReleaseYear);if(p==DomainProfileRouterV2.Profile.TELEVISION_REMOTE_CONTROL)return join("Telecomando",id.brand,"per TV",empty(id.model)?"":id.model);if(p==DomainProfileRouterV2.Profile.SEALED_TRADING_CARD_PRODUCT)return join(year,id.brand,id.family);String number=first(id.physicalCollectorNumber,id.physicalCardNumber,id.sourceConfirmedCatalogNumber);return join(year,id.brand,id.family,id.model,empty(number)?"":"#"+number);}
    private static String family(Models.Identification id){return first(id.family,id.sourceConfirmedProductLine);}
    private static boolean observedDesign(ImmutableEvidenceLedgerV2 l){return l.hasObserved("controlLayout")||l.hasObserved("shortcutButtons")||l.hasObserved("printedLabel")||l.hasObserved("layoutSignature")||l.hasObserved("numericKeypad")||l.hasObserved("navigationLayout");}
    private static String value(ImmutableEvidenceLedgerV2 l,String...f){EvidenceAtom a=l.strongest(f[0],EvidenceAtom.EpistemicLevel.OBSERVED,EvidenceAtom.EpistemicLevel.RETRIEVED,EvidenceAtom.EpistemicLevel.INFERRED);if(a!=null)return a.normalizedValue;for(int x=1;x<f.length;x++){a=l.strongest(f[x],EvidenceAtom.EpistemicLevel.OBSERVED,EvidenceAtom.EpistemicLevel.RETRIEVED,EvidenceAtom.EpistemicLevel.INFERRED);if(a!=null)return a.normalizedValue;}return "";}
    private static String observed(ImmutableEvidenceLedgerV2 l,String...f){for(String x:f){EvidenceAtom a=l.strongest(x,EvidenceAtom.EpistemicLevel.OBSERVED);if(a!=null&&a.localized())return a.normalizedValue;}return "";}
    private static String inferred(ImmutableEvidenceLedgerV2 l,String...f){for(String x:f){EvidenceAtom a=l.strongest(x,EvidenceAtom.EpistemicLevel.INFERRED);if(a!=null)return a.normalizedValue;}return "";}
    private static String observedSource(ImmutableEvidenceLedgerV2 l,String f){EvidenceAtom a=l.strongest(f,EvidenceAtom.EpistemicLevel.OBSERVED);return a!=null&&a.localized()?a.source:"";}
    private static int observedConfidence(ImmutableEvidenceLedgerV2 l,String f){EvidenceAtom a=l.strongest(f,EvidenceAtom.EpistemicLevel.OBSERVED);return a!=null&&a.localized()?a.confidence:0;}
    private static String retrieved(ImmutableEvidenceLedgerV2 l,String...f){for(String x:f){EvidenceAtom a=l.strongest(x,EvidenceAtom.EpistemicLevel.RETRIEVED);if(a!=null)return a.normalizedValue;}return "";}
    private static String values(ImmutableEvidenceLedgerV2 l,String f){StringBuilder b=new StringBuilder();for(EvidenceAtom a:l.current(f))append(b,a.normalizedValue);return b.toString();}
    private static String humanCategory(DomainProfileRouterV2.Profile p){switch(p){case TCG_CARD:return "Carta TCG";case SPORTS_CARD:return "Carta sportiva";case SEALED_TRADING_CARD_PRODUCT:return "Prodotto sigillato";case TELEVISION_REMOTE_CONTROL:return "Telecomando per televisore";case SMARTPHONE:return "Smartphone";case APPLIANCE:return "Elettrodomestico";case CONSUMER_ELECTRONICS:return "Elettronica di consumo";case BARCODE_PRODUCT:return "Prodotto con barcode";case GENERIC_COLLECTIBLE:return "Collezionabile";default:return "Oggetto";}}
    private static void append(StringBuilder b,String value){if(empty(value))return;if(b.length()>0)b.append(" | ");b.append(value);}
    private static String join(String...values){StringBuilder b=new StringBuilder();for(String v:values)append(b,safe(v));return b.toString();}
    private static String joinList(List<String> values){StringBuilder b=new StringBuilder();if(values!=null)for(String v:values)append(b,safe(v));return b.toString();}
    private static String first(String...values){for(String v:values)if(!empty(v))return safe(v);return "";}
    private static boolean empty(String v){return safe(v).isEmpty();}private static String safe(String v){return v==null?"":v.trim();}
}
