package com.flipcheck.nativebeta;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

/** The only v1.33 writer of public identity state. Invoked exactly once per run. */
final class FinalStateReducerV2 {
    static final String VERSION="UniversalIdentityEngineV2.FinalStateReducer/3";
    private FinalStateReducerV2() {}

    static FinalIdentityState reduce(Models.Identification id,ImmutableEvidenceLedgerV2 ledger,
                                     DomainProfileRouterV2.Profile profile,List<IdentityCandidateV2> ranked,
                                     List<ConflictResolverV2.Conflict> conflicts,String technicalFailure){
        id.finalStateReducerVersion=VERSION;id.v2Profile=DomainProfileRouterV2.categoryKey(profile);ensureStructuredViews(id,ledger);
        id.categoryKey=id.v2Profile;id.category=humanCategory(profile);
        IdentityCandidateV2 winner=winner(ranked);CandidateRetrieverV2.commitWinner(winner,ledger);hydrateFromLedgerAndCandidate(id,ledger,profile,winner);classifyWinnerSource(id,winner,ranked);
        boolean photographicInput=id.uploadedImageCount>0&&!ledger.byLevel(EvidenceAtom.EpistemicLevel.OBSERVED).isEmpty();id.categoryStatus=photographicInput?"CONFIRMED":"UNRESOLVED";id.categoryConfidence=photographicInput?categoryConfidence(ledger):0;
        boolean hardConflict=affectsCore(conflicts);boolean technical=!safe(technicalFailure).isEmpty();
        boolean exactPhysical=exactPhysical(id,ledger,profile);boolean catalog=winner!=null&&winner.retrieved&&!winner.rejected&&winner.disproofPassed&&winner.webSourceQuality>=60;
        boolean core=photographicInput&&coreComplete(id,ledger,profile,winner,exactPhysical,catalog)&&!hardConflict&&!technical;

        id.familyStatus=family(id).isEmpty()?"UNRESOLVED":catalog?"CATALOG_MATCHED":"CONFIRMED";
        id.coreIdentityStatus=technical?"UNRESOLVED":core?"CONFIRMED":partialCore(id,profile)?"PROBABLE":"UNRESOLVED";
        id.exactIdentityStatus=profile==DomainProfileRouterV2.Profile.TCG_CARD||profile==DomainProfileRouterV2.Profile.SPORTS_CARD
                ?catalog?"CATALOG_MATCHED":exactPhysical?"PHYSICALLY_VERIFIED":"TO_VERIFY"
                :profile==DomainProfileRouterV2.Profile.SEALED_TRADING_CARD_PRODUCT
                ?empty(id.sealedFormat)?"FORMAT_PENDING":catalog?"CATALOG_MATCHED":"PHYSICALLY_VERIFIED"
                :DomainProfileRouterV2.electronics(profile)
                ?empty(id.model)?"MODEL_TO_VERIFY":catalog?"CATALOG_MATCHED":"PHYSICALLY_VERIFIED"
                :catalog?"CATALOG_MATCHED":core?"PHYSICALLY_VERIFIED":"TO_VERIFY";
        id.identifierStatus=identifierStatus(id,ledger,profile,catalog);id.collectorNumberStatus=id.identifierStatus;id.cardNumberVerificationStatus=id.identifierStatus;id.collectorNumberVerificationStatus=id.identifierStatus;
        id.exactCatalogStatus=catalog?"CATALOG_MATCHED":"NOT_AVAILABLE";id.catalogVerified=catalog;id.disproofPassed=catalog;id.disproofStatus=catalog?"PASSED":disproofSummary(ranked);
        id.webContributionScore=winner==null?0:winner.webSourceQuality;id.catalogCompatibilityStatus=catalog?"MATCHED":winner==null?"NOT_EVALUATED":"UNRESOLVED";id.catalogMatchedFields=winner==null?"":matchedFieldNames(winner);
        id.exactEditionStatus=profile==DomainProfileRouterV2.Profile.TCG_CARD?((!empty(id.edition)&&!TypedFieldNormalizerV2.ambiguous(id.edition)&&(ledger.hasObserved("edition")||"PRESENT".equals(observed(ledger,"firstEditionMark"))))?"CONFIRMED":"TO_VERIFY"):"NOT_APPLICABLE";
        id.finishStatus=(profile==DomainProfileRouterV2.Profile.TCG_CARD||profile==DomainProfileRouterV2.Profile.SPORTS_CARD)?(ledger.hasObserved("finish")?"CONFIRMED":"TO_VERIFY"):"NOT_APPLICABLE";
        id.variantStatus=variantStatus(id,profile);id.formatStatus=profile==DomainProfileRouterV2.Profile.SEALED_TRADING_CARD_PRODUCT?(empty(id.sealedFormat)?"FORMAT_PENDING":"CONFIRMED"):"NOT_APPLICABLE";
        id.commercialFormatStatus=profile==DomainProfileRouterV2.Profile.SEALED_TRADING_CARD_PRODUCT?(empty(id.sealedFormat)?"TO_VERIFY":"CONFIRMED"):"NOT_APPLICABLE";
        id.skuStatus=profile==DomainProfileRouterV2.Profile.SEALED_TRADING_CARD_PRODUCT?(empty(id.sourceConfirmedProductCode)?"TO_VERIFY":"CONFIRMED"):"NOT_APPLICABLE";
        id.exactModelStatus=DomainProfileRouterV2.electronics(profile)?(empty(id.model)?"TO_VERIFY":"CONFIRMED"):"NOT_APPLICABLE";
        id.copyIdentifierStatus=empty(id.physicalSerial)?"NOT_OBSERVED":"PHYSICALLY_VERIFIED";
        id.identityConfirmed=core;id.closureResult=core;id.closureAttempt=true;id.closureLevel=catalog?"CATALOG_IDENTITY":exactPhysical?"EXACT_PHYSICAL_IDENTITY":core?"CORE_IDENTITY":"CATEGORY";id.closureBasis=catalog?"isolated_catalog_candidate_with_disproof":exactPhysical?"complete_physical_tuple":"partial_evidence";id.closureStage="final_state_reducer_v2";
        if(technical){id.identityStatus="TECHNICAL_FAILURE";id.overallStatus="TECHNICAL_FAILURE";id.decision="TECHNICAL_FAILURE";id.pipelineFailureDomain=technicalFailure;}
        else if(hardConflict){id.identityStatus="CONFLICTED";id.overallStatus="CONFLICTED";id.decision="CONFLICTED";}
        else if(core){boolean pending=attributePending(id,profile);id.identityStatus=pending?"CONFIRMED_WITH_ATTRIBUTE_PENDING":"CONFIRMED";id.overallStatus=id.identityStatus;id.decision=id.identityStatus;}
        else if(photoRequestApplicable(id,profile)){id.identityStatus="NEEDS_SPECIFIC_PHOTO";id.overallStatus="NEEDS_SPECIFIC_PHOTO";id.decision=id.identityStatus;}
        else {id.identityStatus="UNRESOLVED";id.overallStatus="UNRESOLVED";id.decision=id.identityStatus;}
        id.hierarchicalStatus=id.overallStatus;id.blockingReason=hardConflict?"documented_core_conflict":"";
        id.marketStatus=marketStatus(id,profile);id.marketReady=core&&!marketIdentityPending(id,profile);id.priceAvailable=false;id.marketDecisionStatus=id.marketStatus;id.priceSummary="Prezzo non calcolato: risoluzione identità separata dai comparabili";id.comparablesSummary="Comparabili non richiesti durante l’identificazione";
        id.title=title(id,profile);id.confirmedBrand=id.brand;id.confirmedFamily=family(id);id.confirmedModel=id.model;id.mainIdentityConfidence=confidence(ledger,winner,core);id.coreIdentityConfidence=id.mainIdentityConfidence;id.exactIdentityConfidence=exactPhysical||catalog?Math.min(99,id.mainIdentityConfidence):Math.min(75,id.mainIdentityConfidence);id.modelConfidence=id.exactIdentityConfidence;
        id.identifierConfidence=observedConfidence(ledger,profile==DomainProfileRouterV2.Profile.TCG_CARD?"collectorNumber":"physicalCardNumber");id.familyConfidence=Math.max(observedConfidence(ledger,profile==DomainProfileRouterV2.Profile.TCG_CARD?"setName":"productLine"),catalog&&winner!=null?Math.min(99,winner.totalScore):0);id.variantConfidence=Math.max(observedConfidence(ledger,"edition"),observedConfidence(ledger,"finish"));
        id.verificationSummary=summary(id,profile,catalog,exactPhysical);id.finalDecisionReason="reducer="+VERSION+"; profile="+id.v2Profile+"; core="+id.coreIdentityStatus+"; exact="+id.exactIdentityStatus+"; catalog="+id.exactCatalogStatus+"; conflicts="+(conflicts==null?0:conflicts.size());
        applyPhotoRequest(id,profile,core);serializeTrace(id,ledger,ranked,conflicts);enforceBlockingInvariants(id,ledger,profile,conflicts);
        id.finalState=new FinalIdentityState(id,id.title,id.identityConfirmed&&!"CONFLICTED".equals(id.identityStatus));return id.finalState;
    }

    private static void hydrateFromLedgerAndCandidate(Models.Identification id,ImmutableEvidenceLedgerV2 l,DomainProfileRouterV2.Profile p,IdentityCandidateV2 c){
        id.observedSubSeries=observed(l,"subSeries");
        id.game=observed(l,"game");id.observedBrand=observed(l,"manufacturer","brand");id.inferredBrand=inferred(l,"manufacturer","brand","game");id.catalogBrand=c==null?"":first(c.value("manufacturer"),c.value("brand"));id.brand=first(id.observedBrand,id.catalogBrand);if(!empty(id.observedBrand)&&!empty(id.catalogBrand)&&SemanticRelationV3.compatible(SemanticRelationV3.relate("manufacturer",id.observedBrand,id.catalogBrand)))id.brand=id.catalogBrand;id.brandStatus=!id.observedBrand.isEmpty()?"CONFIRMED":!id.catalogBrand.isEmpty()?"STRONGLY_SUPPORTED":!id.inferredBrand.isEmpty()?"HYPOTHESIS":"UNRESOLVED";
        String familyField=p==DomainProfileRouterV2.Profile.TCG_CARD?"setName":"productLine";id.family=observed(l,familyField);if(empty(id.family)&&c!=null)id.family=first(c.value(familyField),c.value("productLine"));
        String subjectField=p==DomainProfileRouterV2.Profile.TCG_CARD?"cardName":p==DomainProfileRouterV2.Profile.SPORTS_CARD?"athlete":"model";String subject=observed(l,subjectField);if(empty(subject)&&c!=null&&(p!=DomainProfileRouterV2.Profile.TELEVISION_REMOTE_CONTROL||c.observedIdentifierMatch>=82))subject=c.value(subjectField);id.model=subject;
        id.physicalReleaseYear=observed(l,"productReleaseYear");id.statisticsSeason=value(l,"statisticsSeason");String year=id.physicalReleaseYear;if(c!=null&&empty(year))year=c.value("productReleaseYear");id.sourceConfirmedReleaseYear=c==null?"":c.value("productReleaseYear");
        String physicalField=p==DomainProfileRouterV2.Profile.TCG_CARD?"collectorNumber":"physicalCardNumber";String physicalNumber=observed(l,physicalField);id.physicalCardNumber=physicalNumber;if(p==DomainProfileRouterV2.Profile.TCG_CARD)id.physicalCollectorNumber=physicalNumber;id.cardNumberCandidate=physicalNumber;id.collectorNumberCandidate=p==DomainProfileRouterV2.Profile.TCG_CARD?physicalNumber:"";id.physicalCardNumberOrigin=observedSource(l,physicalField);id.cardNumberVerified=!physicalNumber.isEmpty();id.collectorNumberVerified=p==DomainProfileRouterV2.Profile.TCG_CARD&&!physicalNumber.isEmpty();
        String catalogNumber=c==null?"":c.value("catalogCardNumber");id.sourceConfirmedCatalogNumber=catalogNumber;id.sourceConfirmedCatalogNumberOrigin=empty(catalogNumber)?"":"WEB_CATALOG";id.numberAgreement=!empty(physicalNumber)&&!empty(catalogNumber)&&TypedFieldNormalizerV2.equivalent(p==DomainProfileRouterV2.Profile.TCG_CARD?"collectorNumber":"physicalCardNumber",physicalNumber,catalogNumber);id.combinedVerification=id.numberAgreement?"PHOTO_PLUS_CATALOG":!empty(physicalNumber)?"PHOTO_ONLY":!empty(catalogNumber)?"CATALOG_ONLY":"NONE";
        id.edition=observed(l,"edition");String editionMark=observed(l,"firstEditionMark");if(empty(id.edition)&&"PRESENT".equals(editionMark))id.edition="FIRST_EDITION";if(p!=DomainProfileRouterV2.Profile.TCG_CARD&&empty(id.edition)&&c!=null&&!TypedFieldNormalizerV2.ambiguous(c.value("edition")))id.edition=c.value("edition");id.firstEditionMark="FIRST_EDITION".equals(id.edition)||"PRESENT".equals(editionMark)?"PRESENT":editionMark;id.firstEditionSource="PRESENT".equals(id.firstEditionMark)&&!editionMark.isEmpty()?"PHOTO_FRONT":"";
        id.finish=observed(l,"finish");if(empty(id.finish)&&c!=null)id.finish=c.value("finish");id.language=first(observed(l,"language"),c==null?"":c.value("language"));id.hpOrPv=observed(l,"hp");id.attackNames=values(l,"attacks");id.copyrightYear=observed(l,"copyrightYear");id.productType=first(observed(l,"productType"),c==null?"":c.value("productType"));id.productConfiguration=first(observed(l,"configuration"),c==null?"":c.value("configuration"));id.sealedFormat=resolvedFormat(observed(l,"commercialFormat"),c);id.physicalSerial=observed(l,"physicalSerial");id.physicalSerialOrigin=observedSource(l,"physicalSerial");id.graphicNumber=observed(l,"graphicNumber");
        id.sourceConfirmedProductLine=c==null?"":first(c.value("productLine"),c.value("setName"));id.sourceConfirmedSubSeries=c==null?"":c.value("subSeries");id.sourceConfirmedFormat=c==null?"":c.value("commercialFormat");id.sourceConfirmedProductCode=c==null?"":first(c.value("productCode"),c.value("sku"),c.value("barcode"));id.sourceCatalogTitle=c==null?"":first(c.sourceTitle,c.display());id.searchQuery=id.webQueries.isEmpty()?"":id.webQueries.get(id.webQueries.size()-1);id.title=phrase(year,id.brand,id.family,subject,physicalNumber.isEmpty()?"":"#"+physicalNumber);
    }

    private static void enforceBlockingInvariants(Models.Identification id,ImmutableEvidenceLedgerV2 l,DomainProfileRouterV2.Profile p,List<ConflictResolverV2.Conflict> conflicts){List<String>errors=id.consistencyInvariantErrors;errors.clear();
        if(id.closureResult&&"UNRESOLVED".equals(id.coreIdentityStatus))errors.add("FAIL:closure_core_state_conflict");
        if("CONFLICTED".equals(id.identityStatus)&&(conflicts==null||conflicts.isEmpty()))errors.add("FAIL:conflict_without_two_evidenced_values");
        if("CONFIRMED".equals(id.exactEditionStatus)&&empty(id.edition))errors.add("FAIL:edition_confirmed_but_missing");
        if(p==DomainProfileRouterV2.Profile.SEALED_TRADING_CARD_PRODUCT&&safe(id.missingDiscriminativeFields).contains("card"))errors.add("FAIL:sealed_product_requires_card_number");
        if("PHOTO_PLUS_CATALOG".equals(id.combinedVerification)&&(!l.hasObserved(p==DomainProfileRouterV2.Profile.TCG_CARD?"collectorNumber":"physicalCardNumber")||empty(id.sourceConfirmedCatalogNumber)))errors.add("FAIL:false_photo_plus_catalog");
        if(!id.observedBrand.isEmpty()&&!l.hasObserved("manufacturer")&&!l.hasObserved("brand")&&!l.hasObserved("game"))errors.add("FAIL:observed_brand_without_region");
        if(!id.nextPhotoRequest.isEmpty()&&empty(id.requestedPhotoReason))errors.add("FAIL:photo_request_without_reason");
        if("CONFIRMED".equals(id.categoryStatus)&&id.categoryConfidence==0)errors.add("FAIL:confirmed_category_zero_confidence");
        if(id.uploadedImageCount>0&&!l.byLevel(EvidenceAtom.EpistemicLevel.OBSERVED).isEmpty()&&id.photoViews.isEmpty())errors.add("FAIL:observed_photo_evidence_without_views");
        if(!id.photoViews.isEmpty()&&!"STRUCTURED".equals(id.evidenceLedgerStatus))errors.add("FAIL:photo_views_without_structured_ledger");
        if(!id.inferredBrand.isEmpty()&&id.observedBrand.isEmpty()&&id.catalogBrand.isEmpty()&&id.title.toLowerCase(Locale.ROOT).contains(id.inferredBrand.toLowerCase(Locale.ROOT)))errors.add("FAIL:inferred_brand_in_public_title");
        if(id.catalogVerified&&SourceClassificationPolicy.count(id,"catalog")==0)errors.add("FAIL:catalog_confirmation_without_used_source");
        if(!errors.isEmpty()){id.consistencyInvariants="REPAIRED";id.fieldTransitions.add("FinalStateReducerV2 safe fallback applied: "+errors);if(errors.contains("FAIL:photo_request_without_reason")){id.nextPhotoRequest="";id.requestedPhotoReason="";}if(errors.contains("FAIL:conflict_without_two_evidenced_values")){id.identityStatus=id.identityConfirmed?"CONFIRMED_WITH_ATTRIBUTE_PENDING":"UNRESOLVED";id.overallStatus=id.identityStatus;}if(errors.contains("FAIL:false_photo_plus_catalog"))id.combinedVerification=l.hasObserved(p==DomainProfileRouterV2.Profile.TCG_CARD?"collectorNumber":"physicalCardNumber")?"PHOTO_ONLY":"CATALOG_ONLY";if(errors.contains("FAIL:observed_photo_evidence_without_views")){id.identityConfirmed=false;id.closureResult=false;id.coreIdentityStatus="UNRESOLVED";id.identityStatus="UNRESOLVED";id.overallStatus="UNRESOLVED";}if(errors.contains("FAIL:inferred_brand_in_public_title")){id.brand="";id.title=title(id,p);}if(errors.contains("FAIL:catalog_confirmation_without_used_source")){id.catalogVerified=false;id.exactCatalogStatus="NOT_AVAILABLE";id.disproofStatus="UNRESOLVED";}}
        else id.consistencyInvariants="PASS";id.postWebInvariants=id.consistencyInvariants;id.preWebInvariants="PASS";}

    private static IdentityCandidateV2 winner(List<IdentityCandidateV2> ranked){if(ranked==null)return null;for(IdentityCandidateV2 c:ranked)if(!c.rejected&&c.retrieved&&c.disproofPassed&&c.totalScore>=45)return c;return null;}
    private static boolean coreComplete(Models.Identification id,ImmutableEvidenceLedgerV2 l,DomainProfileRouterV2.Profile p,IdentityCandidateV2 c,boolean exactPhysical,boolean catalog){if(p==DomainProfileRouterV2.Profile.TCG_CARD)return !empty(id.model)&&!empty(id.family)&&!empty(id.physicalCollectorNumber)&&(exactPhysical||catalog);if(p==DomainProfileRouterV2.Profile.SPORTS_CARD)return !empty(id.model)&&!empty(id.family)&&!empty(id.physicalCardNumber)&&!empty(first(id.physicalReleaseYear,id.sourceConfirmedReleaseYear))&&(exactPhysical||catalog);if(p==DomainProfileRouterV2.Profile.SEALED_TRADING_CARD_PRODUCT)return !empty(id.brand)&&!empty(id.family)&&!empty(first(id.physicalReleaseYear,id.sourceConfirmedReleaseYear))&&(catalog||observed(l,"manufacturer","brand").length()>0&&observed(l,"productLine").length()>0);if(p==DomainProfileRouterV2.Profile.TELEVISION_REMOTE_CONTROL)return !empty(id.brand)&&observedDesign(l)&&catalog;if(DomainProfileRouterV2.electronics(p))return !empty(id.brand)&&(!empty(id.model)||!empty(value(l,"barcode")))&&(catalog||l.hasObserved("model")||l.hasObserved("barcode"));return catalog||exactPhysical;}
    private static boolean exactPhysical(Models.Identification id,ImmutableEvidenceLedgerV2 l,DomainProfileRouterV2.Profile p){if(id.photoViews.isEmpty())return false;if(p==DomainProfileRouterV2.Profile.TCG_CARD)return l.hasObserved("cardName")&&l.hasObserved("collectorNumber")&&(l.hasObserved("setName")||l.hasObserved("productLine"));if(p==DomainProfileRouterV2.Profile.SPORTS_CARD)return l.hasObserved("athlete")&&l.hasObserved("physicalCardNumber")&&l.hasObserved("productLine");return l.hasObserved("model")||l.hasObserved("barcode");}
    private static boolean partialCore(Models.Identification id,DomainProfileRouterV2.Profile p){return !empty(id.brand)||!empty(id.family)||!empty(id.model);}
    private static boolean attributePending(Models.Identification id,DomainProfileRouterV2.Profile p){if(p==DomainProfileRouterV2.Profile.SEALED_TRADING_CARD_PRODUCT)return empty(id.sealedFormat)||empty(id.sourceConfirmedProductCode);if(DomainProfileRouterV2.electronics(p))return empty(id.model);return "TO_VERIFY".equals(id.variantStatus)||"TO_VERIFY".equals(id.finishStatus)||"TO_VERIFY".equals(id.exactEditionStatus);}
    private static boolean marketIdentityPending(Models.Identification id,DomainProfileRouterV2.Profile p){return p==DomainProfileRouterV2.Profile.SEALED_TRADING_CARD_PRODUCT&&(empty(id.sealedFormat)||empty(id.sourceConfirmedProductCode))||DomainProfileRouterV2.electronics(p)&&empty(id.model);}
    private static String marketStatus(Models.Identification id,DomainProfileRouterV2.Profile p){return marketIdentityPending(id,p)?"IDENTITY_OR_SKU_PENDING":"NOT_RUN";}
    private static String identifierStatus(Models.Identification id,ImmutableEvidenceLedgerV2 l,DomainProfileRouterV2.Profile p,boolean catalog){String f=p==DomainProfileRouterV2.Profile.TCG_CARD?"collectorNumber":"physicalCardNumber";if(l.hasObserved(f))return catalog&&id.numberAgreement?"PHOTO_PLUS_CATALOG":"PHYSICALLY_VERIFIED";return catalog?"CATALOG_MATCHED":"NOT_OBSERVED";}
    private static String variantStatus(Models.Identification id,DomainProfileRouterV2.Profile p){if(p==DomainProfileRouterV2.Profile.SEALED_TRADING_CARD_PRODUCT)return empty(id.sealedFormat)?"TO_VERIFY":"CONFIRMED";if(p==DomainProfileRouterV2.Profile.TCG_CARD)return "CONFIRMED".equals(id.exactEditionStatus)&&"CONFIRMED".equals(id.finishStatus)?"CONFIRMED":"TO_VERIFY";if(p==DomainProfileRouterV2.Profile.SPORTS_CARD)return empty(id.edition)&&empty(id.finish)?"TO_VERIFY":"CONFIRMED";return empty(id.model)?"TO_VERIFY":"CONFIRMED";}
    private static boolean photoRequestApplicable(Models.Identification id,DomainProfileRouterV2.Profile p){return DomainProfileRouterV2.electronics(p)||!empty(id.missingDiscriminativeFields);}
    private static void applyPhotoRequest(Models.Identification id,DomainProfileRouterV2.Profile p,boolean core){id.nextPhotoRequest="";id.nextPhotoReason="";id.requestedPhotoReason="";if(p==DomainProfileRouterV2.Profile.TELEVISION_REMOTE_CONTROL&&empty(id.model)){id.requestedPhotoMissingField="exactModel";id.requestedPhotoSide="back";id.requestedPhotoRegion="entire_rear_label";id.requestedPhotoExpectedEvidence="model_or_part_code";id.requestedPhotoReason="rear_label_or_model_code";id.nextPhotoReason=id.requestedPhotoReason;id.nextPhotoRequest="Fotografa il retro includendo l’intera etichetta e qualsiasi codice modello o sigla del telecomando.";}else if(!core&&!empty(id.missingDiscriminativeFields)){id.requestedPhotoMissingField=id.missingDiscriminativeFields;id.requestedPhotoSide="identity_bearing_side";id.requestedPhotoRegion="missing_discriminator";id.requestedPhotoExpectedEvidence=id.missingDiscriminativeFields;id.requestedPhotoReason="required_core_discriminator_not_visible";id.nextPhotoReason=id.requestedPhotoReason;id.nextPhotoRequest="Fotografa da vicino la zona che contiene "+id.missingDiscriminativeFields+" mantenendo visibile l’oggetto intero.";}}
    private static boolean affectsCore(List<ConflictResolverV2.Conflict> conflicts){if(conflicts==null)return false;for(ConflictResolverV2.Conflict c:conflicts)if("CORE_IDENTITY".equals(c.affectedIdentityLevel)&&"CRITICAL".equals(c.severity))return true;return false;}
    private static void serializeTrace(Models.Identification id,ImmutableEvidenceLedgerV2 l,List<IdentityCandidateV2>ranked,List<ConflictResolverV2.Conflict>conflicts){
        StringBuilder o=new StringBuilder(),i=new StringBuilder(),r=new StringBuilder();id.evidenceAtomsV2.clear();id.evidenceAtomsV2.addAll(l.all());id.evidenceLedger.clear();
        for(EvidenceAtom a:l.all()){String x=a.id+":"+a.field+"="+a.normalizedValue+"@"+a.source+(a.boundingBox.isEmpty()?"":"["+a.boundingBox+"]");if(a.epistemicLevel==EvidenceAtom.EpistemicLevel.OBSERVED)append(o,x);else if(a.epistemicLevel==EvidenceAtom.EpistemicLevel.INFERRED)append(i,x);else append(r,x);String origin=a.epistemicLevel==EvidenceAtom.EpistemicLevel.OBSERVED?"photo":a.epistemicLevel==EvidenceAtom.EpistemicLevel.RETRIEVED?"web_catalog":"inferred";id.evidenceLedger.add(new Models.EvidenceFact(a.field,a.rawValue,origin,a.modality.name(),a.confidence,a.imageIndex,a.side,a.boundingBox,a.semanticScope,a.sourceUrl));}
        id.v2ObservedFacts=o.toString();id.v2InferredFacts=i.toString();id.v2RetrievedFacts=r.toString();id.evidenceLedgerStatus=id.photoViews.isEmpty()?"UNSTRUCTURED":"STRUCTURED";
        StringBuilder cs=new StringBuilder(),rejected=new StringBuilder();id.candidates.clear();id.rejectedCandidates.clear();IdentityCandidateV2 first=null,second=null;int grounded=0;
        if(ranked!=null)for(IdentityCandidateV2 c:ranked){append(cs,c.candidateId+"="+c.display()+" source_record="+c.sourceRecordId+" level="+c.identityLevel+" source_quality_percent="+c.webSourceQuality+" fields="+c.fields+" score="+c.totalScore+" status="+c.status+" disproof="+c.disproofResult+" relations="+c.fieldRelations+" conflicts="+c.trueConflicts);if(!c.retrieved)append(i,"candidate:"+c.candidateId+"="+c.display()+"@"+c.source);Models.CandidateScore legacy=legacyCandidate(c);if(c.rejected){id.rejectedCandidates.add(legacy);}else if(c.retrieved){id.candidates.add(legacy);if(c.disproofPassed&&c.totalScore>=45)grounded++;if("WINNER".equals(c.status))first=c;}if(c.retrieved&&!"WINNER".equals(c.status))append(rejected,c.candidateId+"@"+c.sourceUrl+":"+c.status+":"+first(c.rejectionReason,c.disproofReason));}
        if(first!=null&&ranked!=null)for(IdentityCandidateV2 c:ranked)if(c!=first&&!c.rejected&&c.retrieved&&sameLevel(first,c)){second=c;break;}
        id.v2InferredFacts=i.toString();
        id.v2CandidateTrace=cs.toString();id.retrievedRejectedSources=rejected.toString();id.canonicalCandidateCount=id.candidates.size();id.candidateIsolationStatus="PASS";id.candidateCanonicalizationSummary="isolated_records="+(ranked==null?0:ranked.size())+"; surviving_grounded="+grounded;
        if(first!=null){id.candidateWinnerId=first.candidateId;id.candidateWinnerSource=first.sourceUrl;}if(second!=null)id.candidateRunnerUpId=second.candidateId;id.tournamentMargin=first==null?0:Math.max(0,first.totalScore-(second==null?0:second.totalScore));
        StringBuilder cf=new StringBuilder();if(conflicts!=null)for(ConflictResolverV2.Conflict c:conflicts)append(cf,c.field+":"+c.valueA+c.evidenceIdsA+" vs "+c.valueB+c.evidenceIdsB);id.v2TrueConflicts=cf.toString();id.numberConflicts=cf.toString();
    }

    private static Models.CandidateScore legacyCandidate(IdentityCandidateV2 c){Models.CandidateScore x=new Models.CandidateScore();x.brand=first(c.value("manufacturer"),c.value("brand"));x.family=first(c.value("setName"),c.value("productLine"));x.subSeries=c.value("subSeries");x.model=first(c.value("cardName"),c.value("athlete"),c.value("model"));x.year=c.value("productReleaseYear");x.cardNumber=c.value("catalogCardNumber");x.language=c.value("language");x.edition=c.value("edition");x.finish=c.value("finish");x.format=c.value("commercialFormat");x.configuration=c.value("configuration");x.productType=c.value("productType");x.sourceUrl=c.sourceUrl;x.sourceAuthority=c.sourceAuthority;x.identifierScore=c.observedIdentifierMatch;x.physicalIdentifierScore=c.observedIdentifierMatch;x.textScore=c.observedTextMatch;x.printedTextScore=c.observedTextMatch;x.layoutScore=c.layoutMatch;x.catalogScore=c.catalogMatch;x.webScore=c.webSourceQuality;x.webEvidenceScore=c.webSourceQuality;x.conflictPenalty=c.contradictionPenalty;x.totalScore=c.totalScore;x.hardRejected=c.rejected;x.candidateFacts.add("candidate_id="+c.candidateId);x.candidateFacts.add("source_record_id="+c.sourceRecordId);x.candidateFacts.add("identity_level="+c.identityLevel);x.candidateFacts.add("disproof="+c.disproofResult+":"+c.disproofReason);x.candidateFacts.add("relations="+c.fieldRelations);x.contradictions.addAll(c.trueConflicts);return x;}

    private static void classifyWinnerSource(Models.Identification id,IdentityCandidateV2 winner,List<IdentityCandidateV2>ranked){if(winner!=null&&!empty(winner.sourceUrl)){if(!SourceClassificationPolicy.mark(id,winner.sourceUrl,"catalog",Math.max(65,winner.webSourceQuality))){Models.Source s=new Models.Source();s.url=winner.sourceUrl;s.title=winner.sourceTitle;s.snippet=winner.display();s.sourceType="catalog";s.relevance=Math.max(65,winner.webSourceQuality);s.strong=true;id.sources.add(s);}}}
    private static void ensureStructuredViews(Models.Identification id,ImmutableEvidenceLedgerV2 ledger){if(id.photoViews.isEmpty()&&id.uploadedImageCount>0){java.util.LinkedHashSet<Integer>indexes=new java.util.LinkedHashSet<>();for(EvidenceAtom a:ledger.byLevel(EvidenceAtom.EpistemicLevel.OBSERVED))if(a.localized())indexes.add(a.imageIndex);for(Integer index:indexes)id.photoViews.add("image="+index+":observed");}id.evidenceLedgerStatus=id.photoViews.isEmpty()?"UNSTRUCTURED":"STRUCTURED";}
    private static int categoryConfidence(ImmutableEvidenceLedgerV2 ledger){int best=0;for(EvidenceAtom a:ledger.byLevel(EvidenceAtom.EpistemicLevel.OBSERVED))if(a.localized())best=Math.max(best,a.confidence);return Math.max(70,Math.min(99,best));}
    private static int confidence(ImmutableEvidenceLedgerV2 ledger,IdentityCandidateV2 c,boolean core){int physical=0;for(EvidenceAtom a:ledger.all())if(a.epistemicLevel==EvidenceAtom.EpistemicLevel.OBSERVED&&a.localized())physical=Math.max(physical,a.confidence);int score=c==null?0:c.totalScore;return core?Math.max(82,Math.min(99,(physical*2+score)/3)):Math.min(79,Math.max(physical,score));}
    private static String summary(Models.Identification id,DomainProfileRouterV2.Profile p,boolean catalog,boolean physical){return "Identità ridotta una sola volta da prove "+(physical?"fotografiche localizzate":"disponibili")+(catalog?" e fonte catalografica con disproof superato":"")+"; gli attributi secondari restano separati.";}
    private static String title(Models.Identification id,DomainProfileRouterV2.Profile p){String year=titleYear(id);if(p==DomainProfileRouterV2.Profile.TELEVISION_REMOTE_CONTROL)return phrase("Telecomando",id.brand,"per TV",empty(id.model)?"":id.model);if(p==DomainProfileRouterV2.Profile.SEALED_TRADING_CARD_PRODUCT){String hierarchy=compatibleHierarchy(compatibleHierarchy(id.family,first(id.observedSubSeries,id.sourceConfirmedSubSeries)),id.sealedFormat);return containsWords(hierarchy,id.brand)?phrase(year,hierarchy):phrase(year,id.brand,hierarchy);}String number=first(id.physicalCollectorNumber,id.physicalCardNumber,id.sourceConfirmedCatalogNumber);String displayBrand=p==DomainProfileRouterV2.Profile.TCG_CARD?first(id.game,id.brand):id.brand;String brand=containsWords(id.family,displayBrand)?"":displayBrand;return phrase(year,brand,id.family,id.model,empty(number)?"":"#"+number);}
    private static String resolvedFormat(String observed,IdentityCandidateV2 candidate){
        String physical=safe(observed);
        if(physical.toLowerCase(Locale.ROOT).matches("(?:sealed |standard |retail )?(?:box|package|product|pack)"))physical="";
        if(physical.isEmpty()&&candidate!=null&&candidate.domain==DomainProfileRouterV2.Profile.SEALED_TRADING_CARD_PRODUCT)
            for(String unknown:candidate.unknownFields)
                if(unknown.toLowerCase(Locale.ROOT).matches(".*(format|hobby|jumbo|blaster|box configuration).*"))return "";
        return first(physical,candidate==null?"":candidate.value("commercialFormat"));
    }
    private static String titleYear(Models.Identification id){
        String physical=safe(id.physicalReleaseYear),catalog=safe(id.sourceConfirmedReleaseYear);
        if(physical.matches("[0-9]{4}")&&catalog.matches("[0-9]{4}-[0-9]{2,4}")
                &&SemanticRelationV3.compatible(SemanticRelationV3.relate("productReleaseYear",physical,catalog)))return catalog;
        return first(physical,catalog);
    }
    private static String family(Models.Identification id){return first(id.family,id.sourceConfirmedProductLine);}
    private static boolean observedDesign(ImmutableEvidenceLedgerV2 l){return l.hasObserved("controlLayout")||l.hasObserved("shortcutButtons")||l.hasObserved("printedLabel")||l.hasObserved("layoutSignature")||l.hasObserved("numericKeypad")||l.hasObserved("navigationLayout");}
    private static String value(ImmutableEvidenceLedgerV2 l,String...f){EvidenceAtom a=l.strongest(f[0],EvidenceAtom.EpistemicLevel.OBSERVED,EvidenceAtom.EpistemicLevel.RETRIEVED,EvidenceAtom.EpistemicLevel.INFERRED);if(a!=null)return a.normalizedValue;for(int x=1;x<f.length;x++){a=l.strongest(f[x],EvidenceAtom.EpistemicLevel.OBSERVED,EvidenceAtom.EpistemicLevel.RETRIEVED,EvidenceAtom.EpistemicLevel.INFERRED);if(a!=null)return a.normalizedValue;}return "";}
    private static String observed(ImmutableEvidenceLedgerV2 l,String...f){for(String x:f){EvidenceAtom a=l.strongest(x,EvidenceAtom.EpistemicLevel.OBSERVED);if(a!=null&&a.localized())return a.normalizedValue;}return "";}
    private static String inferred(ImmutableEvidenceLedgerV2 l,String...f){for(String x:f){EvidenceAtom a=l.strongest(x,EvidenceAtom.EpistemicLevel.INFERRED);if(a!=null)return a.normalizedValue;}return "";}
    private static String observedSource(ImmutableEvidenceLedgerV2 l,String f){EvidenceAtom a=l.strongest(f,EvidenceAtom.EpistemicLevel.OBSERVED);return a!=null&&a.localized()?a.source:"";}
    private static int observedConfidence(ImmutableEvidenceLedgerV2 l,String f){EvidenceAtom a=l.strongest(f,EvidenceAtom.EpistemicLevel.OBSERVED);return a!=null&&a.localized()?a.confidence:0;}
    private static String retrieved(ImmutableEvidenceLedgerV2 l,String...f){for(String x:f){EvidenceAtom a=l.strongest(x,EvidenceAtom.EpistemicLevel.RETRIEVED);if(a!=null)return a.normalizedValue;}return "";}
    private static String values(ImmutableEvidenceLedgerV2 l,String f){StringBuilder b=new StringBuilder();for(EvidenceAtom a:l.current(f))append(b,a.normalizedValue);return b.toString();}
    private static String humanCategory(DomainProfileRouterV2.Profile p){switch(p){case TCG_CARD:return "Carta TCG";case SPORTS_CARD:return "Carta sportiva";case SEALED_TRADING_CARD_PRODUCT:return "Prodotto sigillato";case TELEVISION_REMOTE_CONTROL:return "Telecomando per televisore";case SMARTPHONE:return "Smartphone";case APPLIANCE:return "Elettrodomestico";case CONSUMER_ELECTRONICS:return "Elettronica di consumo";case BARCODE_PRODUCT:return "Prodotto con barcode";case GENERIC_COLLECTIBLE:return "Collezionabile";default:return "Oggetto";}}
    private static void append(StringBuilder b,String value){if(empty(value))return;if(b.length()>0)b.append(" | ");b.append(value);}
    private static String join(String...values){StringBuilder b=new StringBuilder();for(String v:values)append(b,safe(v));return b.toString();}
    private static String phrase(String...values){StringBuilder b=new StringBuilder();for(String v:values)if(!empty(v)){if(b.length()>0)b.append(' ');b.append(safe(v));}return b.toString();}
    private static String joinList(List<String> values){StringBuilder b=new StringBuilder();if(values!=null)for(String v:values)append(b,safe(v));return b.toString();}
    private static boolean containsWords(String haystack,String needle){String h=" "+safe(haystack).toUpperCase(Locale.ROOT).replaceAll("[^A-Z0-9]+"," ").trim()+" ",n=safe(needle).toUpperCase(Locale.ROOT).replaceAll("[^A-Z0-9]+"," ").trim();return !n.isEmpty()&&h.contains(" "+n+" ");}
    private static String compatibleHierarchy(String parent,String child){if(empty(parent))return safe(child);if(empty(child)||containsWords(parent,child))return safe(parent);return phrase(parent,child);}
    private static String matchedFieldNames(IdentityCandidateV2 candidate){StringBuilder b=new StringBuilder();if(candidate!=null)for(java.util.Map.Entry<String,SemanticRelationV3.Relation> entry:candidate.fieldRelations.entrySet())if(SemanticRelationV3.compatible(entry.getValue()))append(b,entry.getKey()+"="+entry.getValue().name());return b.toString();}
    private static String disproofSummary(List<IdentityCandidateV2> ranked){boolean retrieved=false,failed=false;if(ranked!=null)for(IdentityCandidateV2 candidate:ranked)if(candidate!=null&&candidate.retrieved){retrieved=true;if("FAILED".equals(candidate.disproofResult)||candidate.rejected)failed=true;}return !retrieved?"NOT_EXECUTED":failed?"FAILED":"INSUFFICIENT";}
    private static boolean sameLevel(IdentityCandidateV2 a,IdentityCandidateV2 b){return a!=null&&b!=null&&(safe(a.identityLevel).equals(safe(b.identityLevel))||empty(a.identityLevel)||empty(b.identityLevel));}
    private static String first(String...values){for(String v:values)if(!empty(v))return safe(v);return "";}
    private static boolean empty(String v){return safe(v).isEmpty();}private static String safe(String v){return v==null?"":v.trim();}
}
