package com.flipcheck.nativebeta;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import org.json.JSONObject;

/** v1.33 production route: ground -> normalize -> recover -> isolate -> disprove -> reduce once. */
final class UniversalIdentityEngineV2 {
    private UniversalIdentityEngineV2() {}
    static boolean enabled(){return true;}

    static Models.Identification identify(Models.LocalScan local,List<String>images,String details,OpenAiClient client,Models.Usage usage)throws Exception{
        Models.Identification id=new Models.Identification();id.localScan=local;id.finalStateReducerVersion=FinalStateReducerV2.VERSION;id.uploadedImageCount=originalImageCount(local,images);
        ImmutableEvidenceLedgerV2 ledger=new ImmutableEvidenceLedgerV2();ObservationExtractorV2.ingestLocal(local,ledger);id.localOcrFactCount=modalityCount(ledger,EvidenceAtom.Modality.LOCAL_OCR);
        String technical="";ObservationExtractorV2.Result primary=new ObservationExtractorV2.Result();List<IdentityCandidateV2>focusedHypotheses=new ArrayList<>();
        if(images==null||images.isEmpty()){id.missingDiscriminativeFields="complete_object_photo";id.pipelineFailureDomain="NO_IMAGE";return finish(id,ledger,DomainProfileRouterV2.Profile.GENERIC_OBJECT,new ArrayList<>(),"",usage);}
        OpenAiClient.Response first=null;
        try{first=client.observe(new ArrayList<>(images),primaryPrompt(local,details));collect(id,usage,first,"v132_primary_observation");}
        catch(Exception failure){technical=technicalStatus(failure);id.v2CallReasons=append(id.v2CallReasons,"primary_vision:"+technical);}
        if(needsTechnicalRetry(first)&&first!=null&&first.payload!=null&&first.payload.length()>0){primary=ObservationExtractorV2.ingestPrimary(first.payload,ledger);TypedFieldNormalizerV2.normalize(ledger);id.v2RecoveryTrace=append(id.v2RecoveryTrace,"partial_primary_facts_salvaged");}
        if(needsTechnicalRetry(first)&&usage!=null&&usage.costUsd+.004d<=.025d){
            try{OpenAiClient.Response retry=client.observeTechnicalRecovery(new ArrayList<>(images),primaryPrompt(local,details)+"\nTECHNICAL_RETRY=compact_valid_json");collect(id,usage,retry,"v132_primary_technical_retry");id.technicalRetryCount++;first=retry;technical="";}
            catch(Exception failure){technical=technicalStatus(failure);}
        }
        if(first!=null&&first.payload!=null){primary=ObservationExtractorV2.ingestPrimary(first.payload,ledger);id.visionResponseStatus=first.technicalStatus;id.visionFinishReason=first.incompleteReason;recordViews(id,primary.views,ledger,id.uploadedImageCount);}
        if(first==null||needsTechnicalRetry(first)){id.pipelineFailureDomain=empty(technical)?"PRIMARY_VISION_INVALID":technical;return finish(id,ledger,DomainProfileRouterV2.route(primary.category,ledger),primary.hypotheses,id.pipelineFailureDomain,usage);}
        TypedFieldNormalizerV2.normalize(ledger);DomainProfileRouterV2.Profile profile=DomainProfileRouterV2.route(primary.category,ledger);id.v2Profile=DomainProfileRouterV2.categoryKey(profile);id.categoryKey=id.v2Profile;
        if(!primary.contentSufficient){id.missingDiscriminativeFields="identity_bearing_surface";return finish(id,ledger,profile,primary.hypotheses,"",usage);}

        AdaptiveRecoveryPlannerV2.Plan plan=AdaptiveRecoveryPlannerV2.afterPrimary(profile,ledger,usage);id.v2RecoveryTrace=trace(plan);
        if(plan.action==AdaptiveRecoveryPlannerV2.Action.FOCUSED_VISION){
            ImagePreparationV2.Prepared prepared=ImagePreparationV2.focused(images,profile,plan.discriminator);id.v2ImagePreparationTrace=prepared.trace.toString();id.additionalVisionReason=plan.reason+":"+plan.discriminator;id.v2CallReasons=append(id.v2CallReasons,"focused_vision:"+plan.reason+":"+plan.discriminator);
            if(!prepared.images.isEmpty())try{OpenAiClient.Response focused=client.observeFocusedV2(prepared.images,focusedPrompt(profile,plan.discriminator,ledger));collect(id,usage,focused,"v133_focused_"+plan.discriminator);id.discriminativeVisionCount++;if(focused!=null&&focused.payload!=null){ObservationExtractorV2.Result f=ObservationExtractorV2.ingestFocused(focused.payload,ledger,profile,prepared.cropId);focusedHypotheses.addAll(f.hypotheses);TypedFieldNormalizerV2.normalize(ledger);recordViews(id,f.views,ledger,id.uploadedImageCount);}}
            catch(Exception failure){id.v2RecoveryTrace=append(id.v2RecoveryTrace,"focused_failed="+technicalStatus(failure));}
            plan=AdaptiveRecoveryPlannerV2.afterFocused(profile,ledger,usage);id.v2RecoveryTrace=append(id.v2RecoveryTrace,trace(plan));
        }
        List<IdentityCandidateV2>hypotheses=HypothesisGeneratorV2.merge(primary.hypotheses,focusedHypotheses);List<IdentityCandidateV2>all=new ArrayList<>(hypotheses);
        if(plan.action==AdaptiveRecoveryPlannerV2.Action.IDENTITY_WEB||AdaptiveRecoveryPlannerV2.needsWeb(profile,ledger)&&usage!=null&&usage.webCalls==0&&usage.costUsd+.008d<=.025d){
            id.v2CallReasons=append(id.v2CallReasons,"identity_web:"+plan.reason+":"+plan.discriminator);try{String retrievalPrompt=CandidateRetrieverV2.prompt(profile,ledger,hypotheses);OpenAiClient.Response web=client.identityWebSearchV2(images,retrievalPrompt);collect(id,usage,web,"v133_identity_web_multimodal");id.webStatus=web==null?"FAILED":"COMPLETED";if(web!=null&&web.payload!=null){for(String q:CandidateRetrieverV2.queries(web.payload))if(!contains(id.webQueries,q))id.webQueries.add(q);String neutralViolation=CandidateRetrieverV2.neutralQueryViolation(web.payload,profile,hypotheses,ledger);List<IdentityCandidateV2>parsed=CandidateRetrieverV2.parse(web.payload,profile,ledger);CandidateRetrieverV2.bindToolSources(parsed,web.sources);if(!empty(neutralViolation)){rejectBatch(parsed,"neutral_query_policy:"+neutralViolation);id.v2RecoveryTrace=append(id.v2RecoveryTrace,"identity_web_rejected="+neutralViolation);if(usage!=null&&usage.costUsd+.008d<=.025d){OpenAiClient.Response retry=client.identityWebSearchV2(images,retrievalPrompt+"\nNEUTRAL_QUERY_RETRY: query[0] must contain no brand, model or site filter.");collect(id,usage,retry,"v133_identity_web_neutral_retry");if(retry!=null&&retry.payload!=null){for(String q:CandidateRetrieverV2.queries(retry.payload))if(!contains(id.webQueries,q))id.webQueries.add(q);List<IdentityCandidateV2>retryParsed=CandidateRetrieverV2.parse(retry.payload,profile,ledger);CandidateRetrieverV2.bindToolSources(retryParsed,retry.sources);String retryViolation=CandidateRetrieverV2.neutralQueryViolation(retry.payload,profile,hypotheses,ledger);if(!empty(retryViolation))rejectBatch(retryParsed,"neutral_query_policy:"+retryViolation);parsed.addAll(retryParsed);}}}all.addAll(parsed);}}
            catch(Exception failure){id.webStatus="FAILED";id.v2RecoveryTrace=append(id.v2RecoveryTrace,"identity_web_failed="+technicalStatus(failure));}
        }else if(AdaptiveRecoveryPlannerV2.needsWeb(profile,ledger)&&usage!=null&&usage.webCalls==0){id.webStatus="SKIPPED_BUDGET";id.v2RecoveryTrace=append(id.v2RecoveryTrace,"identity_web_skipped=budget_cap");}
        List<IdentityCandidateV2>ranked=CandidateVerifierV2.verify(all,ledger,profile);return finish(id,ledger,profile,ranked,"",usage);
    }

    static Models.Identification replay(Models.LocalScan local,JSONObject primaryPayload,JSONObject focusedPayload,JSONObject webPayload,Models.Usage usage){Models.Identification id=new Models.Identification();id.localScan=local;ImmutableEvidenceLedgerV2 ledger=new ImmutableEvidenceLedgerV2();ObservationExtractorV2.ingestLocal(local,ledger);ObservationExtractorV2.Result p=ObservationExtractorV2.ingestPrimary(primaryPayload,ledger);id.uploadedImageCount=Math.max(1,p.views.size());recordViews(id,p.views,ledger,id.uploadedImageCount);TypedFieldNormalizerV2.normalize(ledger);DomainProfileRouterV2.Profile profile=DomainProfileRouterV2.route(p.category,ledger);List<IdentityCandidateV2>focus=new ArrayList<>();if(focusedPayload!=null){ObservationExtractorV2.Result f=ObservationExtractorV2.ingestFocused(focusedPayload,ledger,profile,"replay-focused");focus.addAll(f.hypotheses);recordViews(id,f.views,ledger,id.uploadedImageCount);TypedFieldNormalizerV2.normalize(ledger);}List<IdentityCandidateV2>all=HypothesisGeneratorV2.merge(p.hypotheses,focus);if(webPayload!=null)all.addAll(CandidateRetrieverV2.parseReplay(webPayload,profile,ledger));return finish(id,ledger,profile,CandidateVerifierV2.verify(all,ledger,profile),"",usage);}

    private static Models.Identification finish(Models.Identification id,ImmutableEvidenceLedgerV2 ledger,DomainProfileRouterV2.Profile profile,List<IdentityCandidateV2>ranked,String technical,Models.Usage usage){List<ConflictResolverV2.Conflict>conflicts=ConflictResolverV2.resolve(ledger,profile);id.estimatedAnalysisCostUsd=usage==null?0d:usage.costUsd;FinalStateReducerV2.reduce(id,ledger,profile,ranked,conflicts,technical);return id;}
    private static void collect(Models.Identification id,Models.Usage usage,OpenAiClient.Response r,String stage){if(r==null)return;if(usage!=null&&r.usage!=null)usage.add(r.usage);if(!contains(id.webStages,stage))id.webStages.add(stage);for(String q:r.queries)if(!contains(id.webQueries,q))id.webQueries.add(q);for(Models.Source incoming:r.sources){if(incoming==null)continue;boolean duplicate=false;for(Models.Source existing:id.sources)if(!empty(incoming.url)&&incoming.url.equals(existing.url)){duplicate=true;break;}if(!duplicate)id.sources.add(incoming);}id.v2CallReasons=append(id.v2CallReasons,stage);}
    private static String primaryPrompt(Models.LocalScan local,String details){return "UNIVERSAL IDENTITY ENGINE V2 / v1.33 grounding contract. Section A contains only literal localized observations. A catalog label inferred from a symbol (set name, brand or product family) belongs in candidates unless the literal text/logo is actually visible. Never describe a symbol as a catalog set name in facts. Each fact must include image, side, exact region and raw visible value. Section B candidates are isolated hypotheses and never become facts. Separate product release season from release year and statistics season; card/collector number from jersey/statistics/serial; card role BASE from edition; sealed configuration from card number. Preserve stable remote-control labels and topology. USER_HINT_SOFT="+clip(details,300)+" LOCAL_OCR_SIZE="+(local==null?0:local.joinedText().length());}
    private static String focusedPrompt(DomainProfileRouterV2.Profile profile,String field,ImmutableEvidenceLedgerV2 ledger){String task="Inspect only the named discriminator";if(profile==DomainProfileRouterV2.Profile.TCG_CARD)task="Transcribe card name, exact collector number, raw set-symbol appearance, First Edition mark, finish, language and copyright from the supplied crops";else if(profile==DomainProfileRouterV2.Profile.SPORTS_CARD)task="Transcribe exact card number and full set season; keep jersey, graphic and statistics numbers separate";else if(profile==DomainProfileRouterV2.Profile.SEALED_TRADING_CARD_PRODUCT)task="Transcribe literal manufacturer logo/text, full product line including subseries, season and printed configuration";else if(profile==DomainProfileRouterV2.Profile.TELEVISION_REMOTE_CONTROL)task="Transcribe visible brand text only if present and record the complete distinctive button topology; shape-only brands remain candidates";return "PROFILE="+DomainProfileRouterV2.categoryKey(profile)+" DECISIVE_FIELD="+field+". "+task+". Never turn a catalog interpretation into an observed fact. EXISTING_OBSERVED="+clip(observedSummary(ledger),900);}
    private static String observedSummary(ImmutableEvidenceLedgerV2 l){StringBuilder b=new StringBuilder();for(EvidenceAtom a:l.byLevel(EvidenceAtom.EpistemicLevel.OBSERVED))if(a.localized()){if(b.length()>0)b.append(" | ");b.append(a.field).append('=').append(a.normalizedValue);}return b.toString();}
    private static boolean needsTechnicalRetry(OpenAiClient.Response r){return r==null||!r.complete||!empty(r.parseError)||r.payload==null||r.payload.length()==0;}
    private static String trace(AdaptiveRecoveryPlannerV2.Plan p){return p.action+":"+p.discriminator+":"+p.reason+":gain="+p.expectedInformationGain+":cost="+p.estimatedCost;}
    private static String technicalStatus(Exception x){String m=safe(x.getMessage()).toLowerCase(Locale.ROOT);return m.contains("timeout")?"TIMEOUT":m.contains("json")?"INVALID_JSON":m.contains("network")||m.contains("connect")?"NETWORK_ERROR":"VISION_TECHNICAL";}
    private static boolean contains(List<String>values,String v){for(String x:values)if(x.equalsIgnoreCase(v))return true;return false;}
    private static int originalImageCount(Models.LocalScan local,List<String>images){if(local!=null&&!local.textByImage.isEmpty())return local.textByImage.size();return images==null?0:images.size();}
    private static void recordViews(Models.Identification id,List<String>reported,ImmutableEvidenceLedgerV2 ledger,int count){if(reported!=null)for(String v:reported)if(!empty(v)&&!contains(id.photoViews,v))id.photoViews.add(v);if(id.photoViews.isEmpty()&&count>0){boolean observed=false;for(EvidenceAtom a:ledger.byLevel(EvidenceAtom.EpistemicLevel.OBSERVED))if(a.localized()){observed=true;break;}if(observed)for(int i=0;i<count;i++)id.photoViews.add("image="+i+":uploaded");}id.evidenceLedgerStatus=id.photoViews.isEmpty()?"UNSTRUCTURED":"STRUCTURED";}
    private static void rejectBatch(List<IdentityCandidateV2>candidates,String reason){if(candidates==null)return;for(IdentityCandidateV2 c:candidates){c.rejected=true;c.rejectionReason=reason;c.disproofResult="FAILED";c.disproofReason=reason;}}
    private static int modalityCount(ImmutableEvidenceLedgerV2 ledger,EvidenceAtom.Modality modality){int count=0;for(EvidenceAtom atom:ledger.all())if(atom.modality==modality)count++;return count;}
    private static String append(String a,String b){return empty(a)?safe(b):empty(b)?safe(a):safe(a)+" | "+safe(b);}
    private static String clip(String v,int n){String x=safe(v);return x.length()<=n?x:x.substring(0,n);}
    private static boolean empty(String v){return safe(v).isEmpty();}private static String safe(String v){return v==null?"":v.trim();}
}
